front-6 Added routing
hhru/hh-dep-monitoring pull request #10
Opened 2019-03-13 19:52 UTC by K-ksenia

На данный момент контент присутствует только на вкладке Repositories и корневой

2019-03-14 08:11 UTC, SuhoyVasya approved these changes

2019-03-14 08:55 UTC, gooverdian requested changes

2019-03-14 08:55 UTC, gooverdian commented on frontend/src/Header/Navbar.js
> +        'text-decoration': 'none',
лучше везде camelCase
И, есть подозрение, что большинство ссылок будет выглядеть именно так, так что можно сразу создать оберточный компонент ссылки, который будет содержать эти стили, либо вынести этот стиль в отдельный файл и подгружать его везде

2019-03-14 08:55 UTC, gooverdian commented on frontend/src/MainBlock/MainBlock.js
> +                <Route path="/Repositories" component={Repositories} />
Лучше создать из navbarItems массив объектов, содержащий path, label и component, так будет очевиднее, и будет один источник истины. А то в Navbar.js поменяете название, а тут забудете.
```
const routing = [
    {
        'path': '/Repositories',
        'exact': false,
        'label': 'Repositories',
        'component': Repositories
    }, ...
];
...
<Switch>
    <Route exact path="/" component={Repositories} /> <!-- главную можно отдельным правилом -->
    {routing.map(...)}
</Switch>
```

2019-03-14 09:01 UTC, gooverdian commented on frontend/.eslintrc.js
> +        "react/prop-types": 0,
А собираешься обратно включать? Проптайпс вообще полезная вещь, смотрешь на компонент и понимаешь, что ему можно передать, плюс ворнинг, если че-то не то передал

2019-03-14 09:19 UTC, alinkov requested changes

2019-03-14 09:19 UTC, alinkov commented on frontend/package.json
> +    "dev": "react-scripts start & yarn start",
а точно так должно быть?

2019-03-14 09:19 UTC, alinkov commented on frontend/package.json
> +    "dev": "react-scripts start & yarn start",
И добавь еще 
```js
"lint-js": "eslint src"
```

2019-03-14 09:19 UTC, alinkov commented on frontend/package.json
> +    "dev": "react-scripts start & yarn start",
Надо бы еще stylelint настроить
и тогда будет еще
```js
"lint-css": "stylelint src"
```

2019-03-14 09:36 UTC, gooverdian commented on frontend/package.json
> +    "dev": "react-scripts start & yarn start",
эта строка по сути дважды выполнит react-scripts start

2019-03-14 19:47 UTC, K-ksenia commented on frontend/.eslintrc.js
> +        "react/prop-types": 0,
Да я с отступами 2ухпробельными боролась и откуда-то скопировала видимо лишнее
Включила обратно

2019-03-14 19:47 UTC, K-ksenia commented on frontend/package.json
> +    "dev": "react-scripts start & yarn start",
про yarn dev - https://github.com/AndreyGladkov/hh-school-react отсюда брала (там в Readme внизу описание)

2019-03-14 19:47 UTC, K-ksenia commented on frontend/package.json
> +    "dev": "react-scripts start & yarn start",
stylelint добавила

2019-03-14 19:47 UTC, K-ksenia commented on frontend/src/Header/Navbar.js
> +        'text-decoration': 'none',
я как-то свойства стилей воспринимала как фиксированные названия. Спасибо, исправила на camelCase

2019-03-14 19:47 UTC, K-ksenia commented on frontend/src/MainBlock/MainBlock.js
> +                <Route path="/Repositories" component={Repositories} />
Да, тоже хотела сделать как-то так, импортировала сюда navbarItems, но не смогла придумать как из строки сделать название компонента.. Спасибо🙂

2019-03-14 19:47 UTC, K-ksenia commented on frontend/src/Header/Navbar.js
> +        'text-decoration': 'none',
для Link сделала styled сomponent

2019-03-14 21:12 UTC, alinkov approved these changes

2019-03-14 22:28 UTC, gooverdian commented on frontend/package.json
> +    "dev": "react-scripts start & yarn start",
Там у Андрея другой скрипт для действия start, в итоге dev выполняет разные вещи - стартует ноду и стартует create-react-app, у тебя тут первая команда выполнит react-scripts start, а вторая - действие start из этого файла, которое тоже равно react-scripts start

2019-03-15 04:33 UTC, K-ksenia commented on frontend/package.json
> +    "dev": "react-scripts start & yarn start",
А, поняла, спасибо

2019-03-15 08:41 UTC, gooverdian requested changes

2019-03-15 08:41 UTC, gooverdian commented on frontend/src/MainBlock/MainBlock.js
> +                    <Route path={item.path} component={item.component} />
Зачем добавлять exact в объект routing, если его не использовать потом тут? Надо либо добавить сюда, либо убрать оттуда

2019-03-15 08:41 UTC, gooverdian commented on frontend/src/MainBlock/Repositories.js
> +                      Repositories
Все еще непонятный отступ в 10 (?)

2019-03-15 08:41 UTC, gooverdian commented on frontend/src/MainBlock/MainBlock.js
> +            <Switch>
Header не входит в Switch, так и хотели?

2019-03-15 13:52 UTC, K-ksenia commented on frontend/src/MainBlock/MainBlock.js
> +            <Switch>
Да, так как он отображается в любом случае

2019-03-15 13:52 UTC, K-ksenia commented on frontend/src/MainBlock/MainBlock.js
> +                    <Route path={item.path} component={item.component} />
На данном этапе он не нужен, оставляла "на будущее"
Убрала

2019-03-15 13:52 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories.js
> +                      Repositories
Убрала

2019-03-15 14:19 UTC, gooverdian approved these changes

2019-03-15 14:30 UTC, merged