back-7 Add Database migration tool
hhru/hh-dep-monitoring pull request #13
Opened 2019-03-17 15:37 UTC by SuhoyVasya

Для теста:
Все скрипты для миграции должны складываться в папку java/resources/db/migration.
Имя файла должно быть форматировано - V2__create_table.sql 
То есть сначала буква V, затем порядковый номер версии, затем двойное подчеркивание, затем произвольное имя. Расширение файла - .sql

2019-03-17 16:20 UTC, K-ksenia commented on hh-dep-monitoring-service/pom.xml
>  </project>
А не нужно сделать еще плагин для запуска?

2019-03-17 16:20 UTC, K-ksenia commented on hh-dep-monitoring-service/src/etc/service.properties
> +github.oauth=���������������������������
Так должно быть?

2019-03-17 16:20 UTC, K-ksenia commented on hh-dep-monitoring-service/pom.xml
>  </project>
Типа как тут https://habr.com/ru/post/141354/

2019-03-17 17:23 UTC, alinkov requested changes

2019-03-17 17:23 UTC, alinkov commented on hh-dep-monitoring-service/src/etc/service.properties
> +github.oauth=���������������������������
Нет, это нужно убрать

Но можно добавить комментарий
Т.е. что-то вроде этого
`#github.oauth=Вставьте ваш токен и расскоментируйте`

2019-03-17 17:23 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/DBMigrateUtil.java
> +public class DBMigrateUtil {
Так не пойдет.
Бины объявляем только в классах конфигурации

2019-03-17 17:23 UTC, alinkov commented on hh-dep-monitoring-service/src/main/resources/db/migration/V1__init.sql
> +    'CRITICAL',
Зачем скрипты заново создавать?

2019-03-17 17:23 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/DBMigrateUtil.java
> +    @Order(Ordered.HIGHEST_PRECEDENCE)
Через `@DependsOn` надёжнее

2019-03-17 17:40 UTC, Afftobus reviewed
...

2019-03-17 17:40 UTC, Afftobus commented on hh-dep-monitoring-service/src/etc/service.properties
> +github.oauth=���������������������������
эта штука временная, делаем чтоб запускалась, но, по большому счету в продакшене не нужна

2019-03-18 04:43 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/etc/service.properties
> +github.oauth=���������������������������
я оставил чтоб у вас сразу из ветки запустилось. Уберу

2019-03-18 04:44 UTC, SuhoyVasya commented on hh-dep-monitoring-service/pom.xml
>  </project>
С помощью flyway можно и с помощью кода  и с помощью плагина выполнять миграции. Я выбрал первый способ

2019-03-18 04:47 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/DBMigrateUtil.java
> +public class DBMigrateUtil {
Ты имеешь ввиду - не создавать отдельный класс, а перенести метод в один из *Config?

2019-03-18 05:41 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/resources/db/migration/V1__init.sql
> +    'CRITICAL',
Потомучто имя файла должно быть специфическим образом отформатировано. По дефолту папка со скриптами должна быть resources/db/migration. 
Предлагаю в программе папку изменить на уже существующую resources/scripts, а уже сделанные скрипты переименовать

2019-03-18 06:06 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/DBMigrateUtil.java
> +    @Order(Ordered.HIGHEST_PRECEDENCE)
ты вроде говорил что ru.hh.nab.hibernate.NabHibernateCommonConfig#sessionFactoryBean не должен стартовать, пока flyway не выполнит миграцию. по логике @DependsOn нужно вешать именно на него, а он библиотечный

2019-03-18 07:34 UTC, alinkov commented on hh-dep-monitoring-service/src/main/resources/db/migration/V1__init.sql
> +    'CRITICAL',
так их можно было переименовать и перенести в нужную папку

2019-03-18 07:41 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/DBMigrateUtil.java
> +public class DBMigrateUtil {
создай лучше отдельный 
MigrationConfig

2019-03-18 07:41 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/DBMigrateUtil.java
> +    @Order(Ordered.HIGHEST_PRECEDENCE)
Сделай так
```java
@Bean
@Primary
@DependsOn("flyway")
protected SessionFactory sessionFactory(@Named("sessionFactoryBean") SessionFactory sessionFactory) {
return sessionFactory;
}
```

Немного костыльно, но зато надежно

2019-03-18 07:41 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/DBMigrateUtil.java
> +    public Flyway migration(DataSource dataSource){
`migration` - переименуй. Не очень название для бина

2019-03-18 08:46 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/DBMigrateUtil.java
> +    public Flyway migration(DataSource dataSource){
переименовал во flyway

2019-03-18 08:46 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/DBMigrateUtil.java
> +    @Order(Ordered.HIGHEST_PRECEDENCE)
добавил метод в MigrateConfig

2019-03-18 08:46 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/resources/db/migration/V1__init.sql
> +    'CRITICAL',
сделал

2019-03-18 08:46 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/DBMigrateUtil.java
> +public class DBMigrateUtil {
сделал

2019-03-18 08:46 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/etc/service.properties
> +github.oauth=���������������������������
убрал под комментарий

2019-03-18 20:16 UTC, alinkov requested changes

2019-03-18 20:16 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/MigrationConfig.java
> +public class MigrationConfig {
допиши `@Configuration`

2019-03-18 20:16 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/MigrationConfig.java
> +        Flyway flyway = Flyway.configure().dataSource(dataSource).load();
сразу возвращай

2019-03-18 20:16 UTC, alinkov commented on hh-dep-monitoring-service/src/etc/service.properties
> +#github.oauth=deletecomment
комментарий то напиши)

2019-03-19 07:37 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/etc/service.properties
> +#github.oauth=deletecomment
исправил на другую строку

2019-03-19 07:37 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/MigrationConfig.java
> +        Flyway flyway = Flyway.configure().dataSource(dataSource).load();
сделал

2019-03-19 07:37 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/MigrationConfig.java
> +public class MigrationConfig {
дописал

2019-03-19 08:15 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +        MigrationConfig.class
Давай разобьем отдельно.
Вначале конфги, потом дао, потом сервисы, потом ресурсы.
И желательно пустой строкой раздели.
Конфиг точно не должен быть внизу

2019-03-19 09:16 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +        MigrationConfig.class
переставил, разделил

2019-03-19 09:45 UTC, alinkov approved these changes

2019-03-19 11:52 UTC, anickishin approved these changes

2019-03-19 11:58 UTC, K-ksenia approved these changes

2019-03-19 13:28 UTC, merged