back-9 Add resource to sync with github
hhru/hh-dep-monitoring pull request #14
Opened 2019-03-18 07:32 UTC by anickishin

2019-03-18 07:46 UTC, alinkov requested changes

2019-03-18 07:46 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/SyncService.java
> +            if (repositoryEntity == null) {
Лучше так
```java
            if (repositoryEntity == null) {
                repositoryDao.create(toEntity(repositoryDto));
                count++;
            } else if (!Object.equals(repositoryDto.getUpdatedAt(), repositoryEntity.getUpdatedAt())) {
                repositoryDao.update(toEntity(repositoryDto));
                count++;
            }
```

2019-03-18 07:46 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/SyncService.java
> +            if (!repositoryDto.getUpdatedAt().equals(repositoryEntity.getUpdatedAt())) {
тут NPE может быть
замени на Object.equals

2019-03-18 07:46 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/SyncService.java
> +    private static Repository toEntity(ru.hh.school.depmonitoring.dto.github.Repository dto) {
давай сделаем отдельные классы мапперов.
Синхронизируйтесь с @Afftobus

2019-03-18 07:46 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/GithubResource.java
> +    public long syncGH() {
ну уж лучше какую-то более ясную dto возвращай.
Сколько добавлено, сколько обновлено.

2019-03-18 07:46 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/GithubResource.java
> +    @Inject
решите, будете добавлять @Inject перед конструктором или нет
Чтобы везде было одинаково

2019-03-18 07:46 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/github/Repository.java
> +            return date.toInstant()
возможный NPE
И вообще можно в какие-нибудь утилиты

2019-03-18 07:46 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/github/Repository.java
> +            this.htmlUrl = htmlUrl.toString();
тоже может быть NPE

2019-03-18 07:53 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/GithubResource.java
> +        return syncService.syncGithub();
здесь мне кажется сомнительным формат ответа. 
в plain тексте цифра... 
может для унификации тут тоже возвращать JSON ?

2019-03-18 07:53 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/SyncService.java
> +    private static Repository toEntity(ru.hh.school.depmonitoring.dto.github.Repository dto) {
Вчера с Александром говорили по этому поводу. 
Мапить entity на dto нужно отдельным классом.

2019-03-18 20:14 UTC, alinkov requested changes

2019-03-18 20:14 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/github/Repository.java
> +            try {
зачем так?
Не нужно Exception  ловить
```java
if(htmlUrl != null) {
} else {
}
```
Либо через Optional

2019-03-18 20:14 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/github/Repository.java
> +            return date.toInstant()
в утилиты унеси. И вроде в параллельном PR это уносит Артем

2019-03-18 20:14 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/SyncService.java
> +import ru.hh.school.depmonitoring.dto.github.Repository;
переименуй название класса, чтобы не мучаться

2019-03-18 20:14 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/Mapper.java
> +public class Mapper {
давай через интерфейс, который обговаривали

2019-03-19 08:02 UTC, alinkov requested changes

2019-03-19 08:02 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/GHRepositoryMapper.java
> +public class GHRepositoryMapper implements Mapper<GHRepositoryDto, Repository> {
сделай бином, и там где нужен, используй как бин

2019-03-19 08:22 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/github/GHRepositoryDto.java
> +            }
все-таки наверное else нужно и затирать на null

2019-03-19 08:22 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/github/GHRepositoryDto.java
> +        private LocalDateTime toLocalDateTime(Date date) {
Сделай DateUtils и туда
тут точно не нужно

2019-03-19 08:22 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/SyncService.java
> +            Repository repositoryEntity = repositoryDao.findOne(repositoryDto.getRepositoryId()).orElse(null);
Давай работать с Optional правильно
```java
var repositoryOptional = repositoryDao.findOne(repositoryDto.getRepositoryId());
if (repositoryOptional.isEmpty()) {
repositoryDao.create(mapper.toEntity(repositoryDto));
} else if (!Objects.equals(repositoryDto.get().getUpdatedAt(), repositoryEntity.getUpdatedAt())) {
                repositoryDao.update(mapper.toEntity(repositoryDto));
}
```

2019-03-19 09:06 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/ProdConfig.java
> +        return fileSettings.getString("github.organization");
Выкидывай ошибку, если этого поля нет и пиши текстом, что именно не так

И почему это в прод конфиге

2019-03-19 09:06 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/DateUtils.java
> +public class DateUtils {
тест на это дело и приватный конструктор

2019-03-19 09:31 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +                .orElseThrow(() -> new RuntimeIOException("Error in getting github.organization from service.properties"));
```suggestion
                .orElseThrow(() -> new IllegalArgumentException("Error in getting github.organization from service.properties"));
```

2019-03-19 09:31 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/GithubResource.java
> +public class GithubResource {
нужен тест на ресурс

2019-03-19 09:31 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/SyncService.java
> +public class SyncService {
тоже нужен тест

2019-03-19 09:31 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/GHRepositoryMapper.java
> +public class GHRepositoryMapper implements Mapper<GHRepositoryDto, Repository> {
по-хорошему тоже нужен тест

2019-03-19 12:17 UTC, alinkov requested changes

2019-03-19 12:17 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/GHRepositoryMapperTest.java
> +    private void assertObjects(Repository entity, GHRepositoryDto dto) {
название не очень.
`assertDtoEqualsEntity`

2019-03-20 12:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +public abstract class AbstractDao<T, I extends Serializable> implements Dao<T, I> {
в интерфейсе дао тоже бы подправил

2019-03-20 13:46 UTC, alinkov approved these changes

2019-03-20 19:11 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/GHRepositoryMapper.java
> +        } else {
если по if ты сделал return то я считаю, что else уже избыточно.

2019-03-20 20:57 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/GHRepositoryMapper.java
> +        } else {
не обязательно. Тут уже дело вкуса

2019-03-21 05:44 UTC, K-ksenia approved these changes

2019-03-21 05:53 UTC, Afftobus approved these changes

2019-03-21 05:54 UTC, merged