Front 2 - Display repositories
hhru/hh-dep-monitoring pull request #15
Opened 2019-03-18 13:04 UTC by K-ksenia

На данный момент в компонент ShowRepositories передается объект repositoriesData, как пример результата вызова fetchRepositories(). Впоследствии будет исправлено на вызов функции fetchRepositories.
<img width="1440" alt="Снимок экрана 2019-03-18 в 15 52 04" src="https://user-images.githubusercontent.com/18597504/54531857-667f0300-4997-11e9-9d94-ea1ac3b7b2a5.png">

2019-03-18 20:09 UTC, alinkov requested changes

2019-03-18 20:09 UTC, alinkov commented on frontend/src/MainBlock/Repositories.js
> +    fetch('http://localhost:8080/repositories/all')
`http://localhost:8080/`
надо в конфиги

2019-03-18 20:09 UTC, alinkov commented on frontend/src/DateTime.js
> +    fontSize: 12,
думаю эти стили лучше куда-нибудь в общий кусок вынести

2019-03-18 20:09 UTC, alinkov commented on frontend/src/MainBlock/Repositories.js
> +const archivedRepositoryColor = '#6c6c6c';
в общие константы лучше, чтобы потом было проще цветовые гаммы менять

2019-03-19 08:55 UTC, gooverdian requested changes

2019-03-19 08:55 UTC, gooverdian commented on frontend/src/DateTime.js
> +    fontSize: 12,
На эту тему говорили в слаке, да, лучше унести

2019-03-19 08:55 UTC, gooverdian commented on frontend/src/MainBlock/Repositories.js
> +    fetch('http://localhost:8080/repositories/all')
Возможно, пригодится axios в качестве фетчера, он удобный
И лучше хранить все запросы к бэкенду в отдельном файле как функции, которые импортируются и вызываются

2019-03-19 08:55 UTC, gooverdian commented on frontend/src/MainBlock/Repositories.js
> +function ListItemTitle(props) {
Это уже тянет на отдельный компонент

2019-03-19 08:55 UTC, gooverdian commented on frontend/src/MainBlock/Repositories.js
> +                    width="19"
Воу воу, не надо так, стилей не должно быть в вызове, надо как-то по-другому

2019-03-19 08:55 UTC, gooverdian commented on frontend/src/MainBlock/Repositories.js
> +                <Fragment key={repo.repositoryId}>
Не хочешь вот этот фрагмент и его содержимое сделать отдельным компонентом?

2019-03-19 08:55 UTC, gooverdian commented on frontend/src/MainBlock/Repositories.js
> +            <ShowRepositories repositories={repositoriesData} />
Компонент лучше называть существительным, или существительными, глаголы повелительного наклонения больше подходят для функций. Например, тут подошел бы RepositoriesList

2019-03-19 08:55 UTC, gooverdian commented on frontend/src/MainBlock/Repositories.js
>  Repositories.propTypes = {
4 компонента в одном файле - перебор

2019-03-19 08:55 UTC, gooverdian commented on frontend/src/icons.js
> +        <svg style={{ ...props }} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 14">
Выглядит прям не очень. Кажется, лучше в этот компонент лучше передавать что-то вроде класса, по которому он сам нагенерит стиль.

Причем можно сделать компонент чуть универсальнее, и передавать в него пропсами, какую картинку ему грузить, создав мэппинг (имя -> картинка)

2019-03-19 09:38 UTC, gooverdian commented on frontend/src/MainBlock/Repositories.js
> +function fetchRepositories() {
У этой функции нет использований, зачем он здесь?

2019-03-20 08:54 UTC, SuhoyVasya commented on frontend/src/MainBlock/Repositories.js
> +const archivedRepositoryColor = '#6c6c6c';
в material UI есть цветовые темы, их можно использовать чтобы не выносить цвета. Но при этом придется написать немного кода

2019-03-20 08:56 UTC, SuhoyVasya approved these changes

2019-03-20 18:08 UTC, K-ksenia commented on frontend/src/DateTime.js
> +    fontSize: 12,
Вынесла

2019-03-20 18:08 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories.js
> +const archivedRepositoryColor = '#6c6c6c';
Вынесла в файл со стилями

2019-03-20 18:08 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories.js
> +function fetchRepositories() {
А я там писала в комментарии к пулл реквесту. Убрала, так как все равно буду на axios менять

2019-03-20 18:08 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories.js
> +                    width="19"
Вынесла

2019-03-20 18:08 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories.js
> +            <ShowRepositories repositories={repositoriesData} />
Переименовала

2019-03-20 18:08 UTC, K-ksenia commented on frontend/src/icons.js
> +        <svg style={{ ...props }} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 14">
Теперь передаю имя класса и имя иконки. Что правильно сделала мэппинг, не уверенна

2019-03-20 18:08 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories.js
> +const archivedRepositoryColor = '#6c6c6c';
угу, видела, но мне показалось так удобнее. Пипеткой ткнул, и не надо на сайт material заходить смотреть какой оттенок как называется) 
Но с точки зрения восприятия кода адекватные названия цветов, наверное, читабельнее 
Подумаю еще, мб поменяю

2019-03-20 18:08 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories.js
> +                <Fragment key={repo.repositoryId}>
Сделала

2019-03-20 18:08 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories.js
>  Repositories.propTypes = {
Разбила на несколько файлов

2019-03-21 11:43 UTC, gooverdian requested changes
Стало круче, но есть нюансы )

2019-03-21 11:43 UTC, gooverdian commented on frontend/src/icons.js
> +        default: return <div />;
Зачем пустой div? Можно вернуть null, или убрать это, ворнинг все равно будет

upd: в итоге ниже откомментил про весь компонент

2019-03-21 11:43 UTC, gooverdian commented on frontend/src/Utils/date.js
> +export default function formatDate(date) {
в наборах функций лучше не использовать default, можно заимпортить не то, что хочется, если забыть `{}`

2019-03-21 11:43 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/Repositories.js
> +function Repositories(props) {
Когда заработают остальные ссылки из верхнего меню - этот компонент стоит сделать универсальным контейнером для них, в который пропсом можно будет передать RepositoriesList и его пропсы, сейчас смысла в нем довольно мало

2019-03-21 11:43 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/Repositories.js
> +    const { classes } = props;
`const { root } = props.classes`
.. `classes={root}`

2019-03-21 11:43 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/Repositories.js
> +    classes: PropTypes.string.isRequired,
string? тогда откуда там .root?

2019-03-21 11:43 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/RepositoryItem.js
> +import React from 'react';
опционально, желательно сортировать импорты, при этом реакт, обычно, первый, а остальные сортируются по пути, а потом по алфавиту

2019-03-21 11:43 UTC, gooverdian commented on frontend/src/icons.js
> +        case 'archive':
гораздо проще иметь объект вида
```
{
  archive: ( svg ),
}
```
и просто `return icons[iconName] || null;`

2019-03-21 11:43 UTC, gooverdian commented on frontend/src/icons.js
> +    className: Object.isRequired,
неподходящее название пропса

2019-03-21 11:47 UTC, gooverdian commented on frontend/src/icons.js
> +        case 'archive':
А, стоп, там надо еще стиль передать, тогда
```
{
   archive: (style) => ( svg with style ),
}
```
и
`return icons[iconName] ? icons[iconName](style) : null`

2019-03-21 16:06 UTC, gooverdian commented on frontend/src/MainBlock/Repositories.js
> +const archivedRepositoryColor = '#6c6c6c';
а, да, про цвета - лучше использовать HEX цвета - поначалу они непривычные, но потом оказывается, что их воспринимать гораздо проще, чем "тридцать седьмой оттенок серого", потому как они однозначно определяют цвет, в отличие от его названия. 

Однако, в конечном счете, набирается 5-7 цветов, которые используются почти везде - вот им, обычно, дают названия и используют потом в брендбуке. Но в любом случае, они определены как hex, и занесены в переменную, которая и используется.

2019-03-21 16:07 UTC, gooverdian commented on frontend/src/MainBlock/Repositories.js
> +const archivedRepositoryColor = '#6c6c6c';
Другое дело - что hex цвета лучше брать откуда-то не с потолка, есть куча сайтов, где можно глянуть сочетаемые палитры

2019-03-23 21:02 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/Repositories.js
> +function Repositories(props) {
Объединила Repositories с RepositoriesList

2019-03-23 21:02 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/Repositories.js
> +    classes: PropTypes.string.isRequired,
вот тут https://simonsmith.io/handling-props-and-class-names-in-react советуют PropTypes.string делать

2019-03-23 21:02 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/RepositoryItem.js
> +import React from 'react';
Сгруппировала

2019-03-23 21:02 UTC, K-ksenia commented on frontend/src/Utils/date.js
> +export default function formatDate(date) {
ESLint ругается на отсутствие default(

2019-03-23 21:02 UTC, K-ksenia commented on frontend/src/icons.js
> +    className: Object.isRequired,
Переименовала в styles

2019-03-23 21:02 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/Repositories.js
> +    classes: PropTypes.string.isRequired,
могу исправить
Object должен быть?

2019-03-23 21:02 UTC, K-ksenia commented on frontend/src/icons.js
> +        case 'archive':
Так намного красивее) спасибо!

2019-03-23 21:02 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/Repositories.js
> +    const { classes } = props;
там у меня еще редаксовские пропсы добавились, так что не стала менять

2019-03-24 09:22 UTC, gooverdian requested changes

2019-03-24 09:22 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/Repositories.js
> +function Repositories(props) {
Можно `function Repositories({ classes, repositories, getRepositories }) {`
и убрать следующую строку

в общем-то, так можно везде, я что-то сначала не обратил внимания

2019-03-24 09:22 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/Repositories.js
> +    classes: PropTypes.string.isRequired,
Возвращаюсь к обсуждению проптайпс для classes - вопрос "Что должно быть?" не должен возникать, по идее, если возникает, значит есть какое-то непонимание.

В этот компонент в проп classes - передается объект с классами, например, classes.root - какой проптайп у classes?

2019-03-24 09:22 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/Repositories.js
> +export default connect(mapStateToProps, mapDispatchToProps)(withStyles(styles)(Repositories));
Можно вот так, чтобы не плодить переменные:
```
export default connect(
    (state) => ({ repositories: state.repositories }), 
    { fetchRepositories }
)(withStyles(styles)(Repositories))
````
ну и да, смысла иметь и getRepositories и fetchRepositories никакого

2019-03-24 09:22 UTC, gooverdian commented on frontend/src/Utils/date.js
> +export default function formatDate(date) {
ок

опционально, можно загнать функцию в объект и экспортировать только его )
```
const dateUtils = {
    formatDate: (date) => { ... }
}

export default dateUtils;
```
Тогда мы гарантировано импортируем то, что надо и сразу все, но это вкусовщина, пока там одна функция - точно не надо

2019-03-24 09:22 UTC, gooverdian commented on frontend/src/redux/repositoriesActions.js
> +export const ADD_REPOSITORIES = 'ADD_REPOSITORIES';
Лучше назвать экшен так, чтобы было понятно, что в пэйлоаде, например `REPOSITORIES_DATA`

2019-03-24 09:22 UTC, gooverdian commented on frontend/src/redux/repositoriesReducer.js
> +    switch (action.type) {
здесь можно поступить также, как в иконке архива, тоже станет красивее ) Можно написать маленький хелпер, который будет создавать редьюсер из переданного ему мэппинга экшенов к стейтам

В итоге, во всех редьюсерах, можно будет писать примерно так без switch:
```
export default createReducer(initialState, {
    [ADD_REPOSITORIES]: (state, action) => ({ ...state, repositories: action.payload }),
});
```
сам createReducer, соответственно, возвращает функцию, принимающую state и action, и возвращающую либо сам экшен, либо initialState, если его нет

2019-03-24 17:21 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/Repositories.js
> +function Repositories(props) {
Переделала

2019-03-24 17:21 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/Repositories.js
> +export default connect(mapStateToProps, mapDispatchToProps)(withStyles(styles)(Repositories));
Выключила no-shadow в ESLint, чтобы можно было просто { fetchRepositories } использовать

2019-03-24 17:21 UTC, K-ksenia commented on frontend/src/redux/repositoriesActions.js
> +export const ADD_REPOSITORIES = 'ADD_REPOSITORIES';
Исправила

2019-03-24 17:21 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/Repositories.js
> +    classes: PropTypes.string.isRequired,
Исправила на Object

2019-03-24 17:21 UTC, K-ksenia commented on frontend/src/Utils/date.js
> +export default function formatDate(date) {
Пока не меняла

2019-03-24 17:21 UTC, K-ksenia commented on frontend/src/redux/repositoriesReducer.js
> +    switch (action.type) {
Пока оставила как есть

2019-03-24 18:29 UTC, gooverdian approved these changes
Все хорошо, микрофикс для забытого проптайпс - и можно мерджить

2019-03-24 18:29 UTC, gooverdian commented on frontend/src/Utils/icons.js
> +    styles: Object.isRequired,
один остался

2019-03-25 10:11 UTC, alinkov approved these changes

2019-03-25 12:29 UTC, merged