Back 15 RepositoryService
hhru/hh-dep-monitoring pull request #16
Opened 2019-03-20 19:49 UTC by Afftobus

2019-03-20 21:04 UTC, alinkov requested changes
Сделай ребейз на мастер. Много конфликтущих моментов, которые не нужны

И лучше основываться на ветку от Андрея.
Там более удачно настроили интеграционные тесты

2019-03-20 21:04 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/ProdConfig.java
> +    protected DataSource dataSource(DataSourceFactory dataSourceFactory, FileSettings fileSettings) {
зачем это в прод?

2019-03-20 21:04 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +public class PageDto<T> {
лучше убери пока

2019-03-20 21:04 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/TestConfig.java
> +    PropertiesFactoryBean serviceProperties() {
он уже есть

2019-03-20 21:04 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/TestConfig.java
> +    DataSource dataSource() throws Exception {
убирай

2019-03-20 21:04 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +        assertEquals(0, result.size());
assertFalse(result.isEmpty())

2019-03-20 21:04 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +    private final RepositoryDto repositoryDto;
зачем так?
Сделай метод, который создает эту сущность

2019-03-20 21:04 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/LocalDateDeserializer.java
> +public class LocalDateDeserializer extends StdDeserializer<LocalDateTime> {
а точно этого нету?
По-моему это уже есть и никаких плясок не нужно

2019-03-21 05:20 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +    private final RepositoryDto repositoryDto;
как раз тот самый билдер?

2019-03-21 05:23 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/LocalDateDeserializer.java
> +public class LocalDateDeserializer extends StdDeserializer<LocalDateTime> {
я погуглил, мне интернет сказал, что так надо делать.
мне же где-то нужно привести к формату.
стандартные форматы сериализуют с большим количеством знаков после секунд, а мы договорились передавать без таковых

2019-03-21 05:25 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/ProdConfig.java
> +    protected DataSource dataSource(DataSourceFactory dataSourceFactory, FileSettings fileSettings) {
так у нас в тестах свой датасорс... или я не правильно понял идею...

2019-03-21 06:22 UTC, anickishin requested changes

2019-03-21 06:22 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +        if (!dto1.getRepositoryId().equals(dto2.getRepositoryId())) {
А если dto1.getRepositoryId вернёт null?

2019-03-21 06:22 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +    private final RepositoryDto repositoryDto;
Нет. Посмотри в моём ПР в тестах utils/StructCreator.

2019-03-21 06:22 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryMapperTest.java
> +    private final RepositoryDto repositoryDto;
Эту сущность можно будет создавать тем же методом

2019-03-21 06:22 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryMapperTest.java
> +        Repository entity = repositoryMapper.toEntity(repositoryDto);
Мне кажется, что так немного неправильно. Тесты должны быть независимыми. А у тебя получается, что в проверяемом методе toDto должен правильно работать проверяемый метод toEntity.

2019-03-21 06:22 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +        repositoryService.update(repositoryDto);
Зачем тебе здесь update?

2019-03-21 06:22 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/ProdConfig.java
> +    protected DataSource dataSource(DataSourceFactory dataSourceFactory, FileSettings fileSettings) {
посмотри мой ПР

2019-03-21 06:22 UTC, anickishin commented on hh-dep-monitoring-service/src/test/resources/service-test.properties
> +serviceName=checkUp
Возьми лучше наши properties

2019-03-21 08:18 UTC, anickishin requested changes
Сделай ребейз на мастер

2019-03-21 17:29 UTC, alinkov requested changes

2019-03-21 17:29 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +    public RepositoryDto getOneItem(Long id) {
Давай лучше тоже Optional.
Чтобы как можно меньше работать с null
И давайте все-таки по возможности контракт указывать.
Я про аннотации @Nonnul и @Nullable
Просто потом будет себя тяжело переучить

2019-03-21 17:29 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        final List<RepositoryDto> result = new ArrayList<>();
Зачем так?
```java
return repositoryDao.findAll().stream()
.map(repositoryMapper::toDto)
.collect(Collectors.toList());

```

2019-03-21 17:29 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/LocalDateDeserializer.java
> +public class LocalDateDeserializer extends StdDeserializer<LocalDateTime> {
Лучше ObjectMapper переопределить.
Через немного скину пример

2019-03-21 17:52 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/LocalDateDeserializer.java
> +public class LocalDateDeserializer extends StdDeserializer<LocalDateTime> {
Лучше добавить зависимость https://github.com/FasterXML/jackson-modules-java8
ObjectMapper переопределить в провайдере
```java
@Provider
public class ObjectMapperContextResolver implements ContextResolver<ObjectMapper> {
//
}
```

А затем добавить это в Main
```java
    return NabApplication.builder()
        .configureJersey()
            .registerResources(ObjectMapperContextResolver.class)
            .bindToRoot()
        .build();
```

И переопределить это в тестах, везде где переопределяется ru.hh.nab.testbase.NabTestBase#getApplication. А лучше выделить это в абстрактный класс

2019-03-21 20:43 UTC, alinkov requested changes

2019-03-21 20:43 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/EntityDtoMapper.java
> +public interface EntityDtoMapper<E, D> {
уже есть `ru.hh.school.depmonitoring.service.mapper.Mapper`

2019-03-21 20:43 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +        if (!dto1.getRepositoryId().equals(dto2.getRepositoryId())) {
в тестах лучше писать
`assertEquals(dto1.getField(), dto2.getField())`

2019-03-21 20:43 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +    @Sql("/clear-repository.sql")
это лучше запихнуть в `@After` и для всех тестов выполнять

2019-03-21 20:43 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +public class RepositoryServiceTest extends NabTestBase {
Сделай абстрактный класс, чтобы это не дублировать
```java
@ContextConfiguration(classes = TestConfig.class)
public abstract class DepMonitoringTestBase extends NabTestBase {

}
```

2019-03-22 05:30 UTC, anickishin requested changes

2019-03-22 05:30 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryMapperTest.java
> +    private final RepositoryDto repositoryDto;
Убирай это

2019-03-22 05:30 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryMapperTest.java
> +    public RepositoryMapperTest() {
И конструктор не нужен

2019-03-22 05:30 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryMapperTest.java
> +        Repository entity = repositoryMapper.toEntity(repositoryDto);
А здесь добавляй
`RepositoryDto repositoryDto = StructCreator.createRepositoryDto();`

2019-03-22 05:30 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryMapperTest.java
> +        Repository entity = repositoryMapper.toEntity(repositoryDto);
```suggestion
        Repository entity = StructCreator.createRepositoryEntity(...);
```

2019-03-22 05:30 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +    public RepositoryServiceTest() {
Убирай конструктор и repositoryDto из класса

2019-03-22 05:30 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +    @Before
Зачем нужен пустой Before?

2019-03-22 05:30 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/config/TestConfig.java
> +        RepositoryService.class,
А нам эти сервис с маппером в проде будут не нужны?

2019-03-23 19:28 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/MigrationConfig.java
> +        return Flyway.configure().dataSource(dataSource).baselineOnMigrate(true).load();
OK

2019-03-23 19:28 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/EntityDtoMapper.java
> +public interface EntityDtoMapper<E, D> {
поправил, наследуюсь от него же

2019-03-23 19:28 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/LocalDateDeserializer.java
> +public class LocalDateDeserializer extends StdDeserializer<LocalDateTime> {
сделал, но есть ощущение, что что-то делаю нетак

2019-03-23 19:28 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryMapperTest.java
> +    private final RepositoryDto repositoryDto;
сделал

2019-03-23 19:28 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryMapperTest.java
> +    public RepositoryMapperTest() {
конструктор убрал

2019-03-23 19:28 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryMapperTest.java
> +        Repository entity = repositoryMapper.toEntity(repositoryDto);
ОК

2019-03-23 19:28 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryMapperTest.java
> +        Repository entity = repositoryMapper.toEntity(repositoryDto);
поправил

2019-03-23 19:28 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +public class RepositoryServiceTest extends NabTestBase {
вынес в абстрактный

2019-03-23 19:28 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +    private final RepositoryDto repositoryDto;
ОК

2019-03-23 19:28 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +    public RepositoryServiceTest() {
убрал

2019-03-23 19:28 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/config/TestConfig.java
> +        RepositoryService.class,
вынес в Common

2019-03-24 07:00 UTC, alinkov commented on hh-dep-monitoring-service/pom.xml
> +            <version>2.9.8</version>
Версию в константу.
И в набережных такая же?

2019-03-24 07:00 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RepositoryDto.java
> +//import ru.hh.school.depmonitoring.utils.LocalDateSerializer;
Удаляй. Не нужно комментировать

2019-03-24 07:00 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/Resource.java
>  public class Resource {
Удаляй его вообще. Теперь не нужен.
А то тут уже что-то непонятное

2019-03-24 07:00 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/LocalDateDeserializer.java
> +public class LocalDateDeserializer extends StdDeserializer<LocalDateTime> {
Удаляй класс

2019-03-24 07:00 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/ObjectMapperContextResolver.java
> +
А что модули не зарегистрировал?

2019-03-24 07:00 UTC, alinkov commented on hh-dep-monitoring-service/src/test/resources/clear_repository.sql
> +DELETE FROM repository;
Truncate

2019-03-24 07:00 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +    @Sql(
Сделай это в after

2019-03-24 07:00 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/GithubResourceTest.java
>      protected NabApplication getApplication() {
Это должно быть в DepMonitoringTestBase

2019-03-25 04:53 UTC, anickishin requested changes

2019-03-25 04:53 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +        RepositoryMapper.class
Какое разделение у нас тут идёт? Я думал по типам (настройки, ДАО, сервисы, ресурсы).

2019-03-25 04:53 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RepositoryDto.java
> +    private boolean hasRelatedTo;
Мне кажется, что должно быть однообразно (везде NotNull или nullable)

2019-03-25 04:53 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryMapperTest.java
> +        assertEquals(entity.getRepositoryId(), repositoryDto.getRepositoryId());
Можно вынести это сравнение в отдельную функцию, чтобы код не дублировать (как в RepositoryServiceTest).

2019-03-25 04:53 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +    private final RepositoryDto repositoryDto;
Можно не держать поле в классе, а, при необходимости, вызывать StructCreator (как в RepositoryMapperTest).

2019-03-25 20:24 UTC, alinkov requested changes

2019-03-25 20:24 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +    RepositoryService repositoryService;
```suggestion
    private RepositoryService repositoryService;
```

2019-03-25 20:24 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +    DBUtils dbUtils;
```suggestion
    private DBUtils dbUtils;
```

2019-03-25 20:24 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +        dbUtils.cleanTable(Repository.class);
это точно не тут должно быть.
Это должно быть в `@After` и для всех тестов
Хорошо бы чистить все таблички

2019-03-25 20:24 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +        repositoryService.update(repositoryDto);
зачем тут вообще что-то создавать?

2019-03-25 20:24 UTC, alinkov commented on hh-dep-monitoring-service/pom.xml
> +            <artifactId>jackson-datatype-jsr310</artifactId>
а где остальные зависимости?
нужно добавить все те, что есть в набе
https://github.com/hhru/nuts-and-bolts/blob/master/nab-starter/pom.xml#L71-L99

2019-03-26 05:56 UTC, anickishin requested changes

2019-03-26 05:56 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    private Session getSession() {
А зачем private сделал?

2019-03-26 05:56 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +    @Test(expected = javax.persistence.PersistenceException.class)
```suggestion
    @Test(expected = PersistenceException.class)
```

2019-03-26 05:56 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RepositoryDto.java
> +    private boolean hasRelatedTo;
https://github.com/hhru/hh-dep-monitoring/pull/16/files#r268487752

2019-03-26 08:07 UTC, alinkov requested changes

2019-03-26 08:07 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/ObjectMapperContextResolver.java
> +    }}
а не ругается, что 2 скобки на одной строке?

2019-03-26 08:07 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    private Session getSession() {
Видимо идея подсказала, потому что еще нигде не используется

Но тут лучше вернуть, потому что это потом точно будет использоваться

2019-03-26 08:07 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RepositoryDto.java
> +    private boolean hasRelatedTo;
Это boolean, он null быть не может

2019-03-26 08:07 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +        dbUtils.cleanTable(Repository.class);
Перенеси это в `DepMonitoringTestBase` и чисть все таблички.

2019-03-26 08:07 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/MigrationConfig.java
> +        return Flyway.configure().dataSource(dataSource).baselineOnMigrate(true).load();
А без этого разве не работает?
Просто это не тот флаг, который стоит просто так добавлять

2019-03-26 11:01 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RepositoryDto.java
> +    private boolean hasRelatedTo;
а `private String description`?

2019-03-26 11:04 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RepositoryDto.java
> +    private boolean hasRelatedTo;
а `private String description`?

2019-03-26 12:59 UTC, alinkov approved these changes

2019-03-26 13:20 UTC, anickishin approved these changes

2019-03-26 13:33 UTC, merged