Back 8 Add auto sync with github
hhru/hh-dep-monitoring pull request #17
Opened 2019-03-21 10:58 UTC by anickishin

2019-03-21 11:27 UTC, SuhoyVasya approved these changes

2019-03-21 12:22 UTC, alinkov requested changes

2019-03-21 12:22 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/ScheduledTasks.java
> +@EnableScheduling
А зачем тут?

2019-03-21 12:22 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/ScheduledTasks.java
> +    public void syncTask() {
В самом loader бы оставил

2019-03-21 15:50 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/ScheduledTasks.java
> +    @Scheduled(fixedDelay = 15*60*1000L)
думаю, что еще стоит initialDelay поставить.
чтобы не сразу при старте начинало работать.

2019-03-22 06:03 UTC, K-ksenia approved these changes

2019-03-22 07:50 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/StructCreator.java
> +        List<GHRepositoryDto> repositoryDtoList = new LinkedList<>();
LinkedList тут точно не нужен, учитывая, что ты заранее знаешь какого размера будет результат.
А так вообще можно делать так
```java
return LongStream.range(1, count + 1)
            .mapToObj(StructCreator::createGHRepositoryDto)
            .collect(Collectors.toList());
```

2019-03-22 07:50 UTC, alinkov approved these changes

2019-03-22 08:59 UTC, merged