Back 9
hhru/hh-dep-monitoring pull request #18
Opened 2019-03-22 10:30 UTC by SuhoyVasya

add Repository Resource

2019-03-22 16:16 UTC, alinkov requested changes
Нужно починить сборку и написать тесты

2019-03-22 16:16 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    public PageDto(List<T> list,int perPage, int page){
пробелов и дефолтный конструктор

2019-03-22 16:16 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +public class PageDto<T> {
добавь implements Serializable

2019-03-22 16:16 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private List<T> items;
лучше на всякий случай массив сделать.
Просто с List могут быть проблемы при десериализации, т.к. там откуда-нибудь может появиться не ArrayList,  какая-нибудь неведомая реализация

2019-03-22 16:16 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        this.found=list.size();
передавай полем в конструктор

2019-03-22 16:16 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        this.pages = this.found / perPage;
нужно проверять, что perPage > 0

2019-03-22 16:16 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        int stopIndex= startIndex+perPage;
```suggestion
        int stopIndex= Math.min(startIndex+perPage, this.found);
```

2019-03-22 16:16 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        this.items = list.subList(startIndex,stopIndex);
этого не надо

2019-03-22 16:16 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        this.items = list.subList(startIndex,stopIndex);
Сделай сразу класс таким, чтобы его потом не приходилось менять.

А вообще неплохо было бы сделать builder для него

2019-03-22 16:16 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/MigrationConfig.java
> +        return Flyway.configure().dataSource(dataSource).baselineOnMigrate(true).load();
для чего?

2019-03-22 16:16 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +public class RepositoryResource {
нужен тест на это дело

2019-03-24 05:55 UTC, K-ksenia commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +@Path("/")
Предлагаю тут сделать /repositories

2019-03-24 05:55 UTC, K-ksenia commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/allRepositories")
тут соответственно можно просто /all

2019-03-24 05:55 UTC, K-ksenia commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/repository/{repository_id}")
тут /{repository_id}

2019-03-24 05:55 UTC, K-ksenia commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/repository")
и тут тоже /{repository_id} нужен, мы же по id репозиторий находим?

2019-03-24 06:40 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +public class PageDto<T> {
зачем?

2019-03-24 06:48 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private List<T> items;
Как у нас могут вылезти проблемы при десериализации - это вроде страницы и мы впринципе их не должны с клиента забирать. Плюс даже если у нас встала такая проблема, почему нам может помешать неведомая рализация листа? Она же всеравно будет листом. В ООП ведь впринципе не нужно погружаться в детали реализации?

2019-03-24 06:48 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        this.found=list.size();
Зачем лишний аргумент? эта информацию можно получить моим способом

2019-03-24 06:48 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        this.items = list.subList(startIndex,stopIndex);
Как вообще будет работать PageDto?
В моем понимании это объект страница т.е. на вход передаем ей весь массив а PageDto выбирает из этого часть и хранит ее.
Почему нужен builder?

2019-03-24 06:48 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +@Path("/")
согласен

2019-03-24 06:48 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +public class RepositoryResource {
что должен проверять тест? код 204?

2019-03-24 06:48 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/repository")
Мне кажется это лишнее. как PathParam мы этот  id не используем. У нас приходит json в котором уже есть id

2019-03-24 06:50 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/MigrationConfig.java
> +        return Flyway.configure().dataSource(dataSource).baselineOnMigrate(true).load();
без этого он вылетает если есть непустая база, но нет его служебной таблицы с историей миграций

2019-03-24 07:13 UTC, alinkov requested changes
Сборку необходимо починить

2019-03-24 07:13 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/MigrationConfig.java
> +        return Flyway.configure().dataSource(dataSource).baselineOnMigrate(true).load();
А ты читал доку для метода?
Не стоит просто так этот параметр добавлять

2019-03-24 07:13 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +public class PageDto<T> {
Потому что этот объект у тебя будет сериализоваться и десериализоваться.
Поэтому лучше добавить implements Serializable и соблюдать его контракт. Иначе потом могут быть неожиданные проблемы

2019-03-24 07:13 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private List<T> items;
Вот поэтому и не ставь лист.
Потому что лист тебе не гарантирует того, что он может быть засериализован.
Ты туда можешь передать любую реализацию, а она уже потом приведет к ошибкам

2019-03-24 07:13 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        this.found=list.size();
А когда будет часть списка?

2019-03-24 07:13 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        this.items = list.subList(startIndex,stopIndex);
Зачем нам получать весь список чтобы получать страницу?
Нужно получать только необходимую страницу.
Или ты думаешь, что для постраничности миллиона записей нужно каждый раз это миллион получать?

2019-03-24 07:13 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +public class RepositoryResource {
Что ресурс работает корректно.

2019-03-24 07:18 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +public class PageDto<T> {
так ведь вся сериализация проводится сторонними библиотеками которые этот интерфейс просто проигнорят

2019-03-24 07:19 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        this.found=list.size();
А как узнавать какая это часть списка? тогда нужно еще и позицию этого подсписка в списке. Чтобы корректно отображать страницы

2019-03-24 07:36 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +public class PageDto<T> {
Интерфейс игнорят, а контракт используют такой же.
Интерфейс никому не нужен, всем нужен контракт.
В общем, если хочешь упростить себе жизнь, делай implements Serializable и поддерживай контракт. Либо надейся на сторонние библиотеки, которые при изменении версии могут вызвать ошибки

2019-03-24 07:36 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        this.found=list.size();
Да, нужно

2019-03-24 09:17 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    public PageDto(List<T> list,int perPage, int page){
добавил дефолтный конструктор

2019-03-24 09:18 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +public class PageDto<T> {
добавил implements Serializable

2019-03-24 09:18 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private List<T> items;
поменял на массив

2019-03-24 09:19 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        this.found=list.size();
сделал PageDtoBuilder, все параметры передаю через него, offset не добавлял

2019-03-24 09:19 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        this.pages = this.found / perPage;
проверяется в PageDtoBuilder

2019-03-24 09:20 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        int stopIndex= startIndex+perPage;
Поменял, этот код теперь в RepositoryResource

2019-03-24 09:20 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        this.items = list.subList(startIndex,stopIndex);
убрал из PageDto

2019-03-24 09:20 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/MigrationConfig.java
> +        return Flyway.configure().dataSource(dataSource).baselineOnMigrate(true).load();
убрал

2019-03-24 09:21 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +@Path("/")
поменял

2019-03-24 09:21 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/allRepositories")
поменял

2019-03-24 09:21 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/repository/{repository_id}")
поменял

2019-03-24 09:21 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/repository")
не трогал

2019-03-24 16:48 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +public class RepositoryResource {
добавил тесты

2019-03-25 05:25 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/repository")
Мне кажется, что, если придерживаться REST, /{repository_id} будет правильнее

2019-03-25 07:26 UTC, alinkov requested changes

2019-03-25 07:26 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/{repository_id}")
давай однотипно именовать.
Выше у тебя camelCase 
`perPage`, а тут через нижнее подчеркивание

2019-03-25 07:26 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/all")
Лучше просто `/`

2019-03-25 07:26 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/")
`@PUT` чаще всего делают с id, чтобы через него новые не проходили

2019-03-25 07:26 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +            return null;
давай не возвращать null
всегда возвращай PageDto. Лучше засовывай пустые items.
Так будет проще работать

2019-03-25 07:26 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +        items = list.subList(startIndex, stopIndex).toArray(items);
можно передавать массив пустого размера

2019-03-25 07:26 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/config/TestConfig.java
> +    protected RepositoryService repositoryService(){
не. Его сюда не нужно.
Этот сервис тоже будет тестироваться.

2019-03-25 10:08 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/{repository_id}")
переписал под camelCase

2019-03-25 10:08 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/all")
переделал

2019-03-25 10:08 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/")
добавил PathParam repositoryId и проверку

2019-03-25 10:09 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +            return null;
переделал под возврат PageDto с пустым массивом Items

2019-03-25 10:09 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +        items = list.subList(startIndex, stopIndex).toArray(items);
переделал под возврат PageDto с пустым массивом Items

2019-03-25 10:09 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/config/TestConfig.java
> +    protected RepositoryService repositoryService(){
переместил в RepositoryResourceTest

2019-03-25 12:28 UTC, K-ksenia approved these changes

2019-03-25 17:53 UTC, colorbash requested changes

2019-03-25 17:53 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private T[] items;
а почему не лист? удобнее же?

2019-03-25 17:53 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        public PageDtoBuilder<T> withFound(int found){
`){ -> ) {`
@alinkov кажется чекстайл плагин сломался?

2019-03-25 17:53 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        public PageDtoBuilder<T> withFound(int found){
еще мне не оч нравится что у нас отступы - 4 пробела

2019-03-25 17:53 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +        if(dto != null && id == dto.getRepositoryId()){
если id содержится в RepositoryDto то зачем нам его дублировать в пас параме?
кстати если уж и дублируем то условие не правильное - если оставить как сейчас при   id != dto.getRepositoryId() вернется 200 - что запутает пользователя, надо вернуть ошибку

2019-03-25 17:53 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    private static PageDto<RepositoryDto> getPage(List<RepositoryDto> list, int page, int perPage){
давай не лист, а repositoryDtos или как-то так

2019-03-25 17:53 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    private static PageDto<RepositoryDto> getPage(List<RepositoryDto> list, int page, int perPage){
ой стоп это вообще надо делать через базу а не вручную

2019-03-25 17:53 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RepositoryMapper.java
> +        if (dto == null) {
а не исключение было бы правельнее кидать?

2019-03-25 17:53 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RepositoryMapper.java
> +
много отступов

2019-03-25 17:53 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RepositoryMapper.java
> +        dto.setHasRelatedFrom(entity.getRelatedFrom() != null && !entity.getRelatedFrom().isEmpty());
!StringUtils.isBlank(entity.getRelatedFrom())

2019-03-25 17:53 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +        if (dto1 == dto2) {
очень странно проверять ссылки на обьекты на равенство...
что ты хочешь оптимизировать? случай когда вызывается этот кейс? `testIsDtoEqual(dto1, dto1);`
давай уберем

2019-03-25 17:53 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +        if (dto1 == null || dto2 == null) {
много кооода
давай сделаем на подобии
```java
    return Objects.equals(id, that.id) &&
        Objects.equals(state, that.state) &&
        Objects.equals(employerState, that.employerState) &&
        Objects.equals(createdAt, that.createdAt) &&
        Objects.equals(updatedAt, that.updatedAt) &&
        Objects.equals(resume, that.resume) &&
        Objects.equals(messagesUrl, that.messagesUrl) &&
        Objects.equals(viewedByOpponent, that.viewedByOpponent) &&
        Objects.equals(hasUpdates, that.hasUpdates) &&
        Objects.equals(templates, that.templates) &&
        Objects.equals(actions, that.actions) &&
        (o instanceof EmployerNegotiationTopicFullDto || Objects.equals(url, that.url));
  }
```

2019-03-25 17:54 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private T[] items;
Для сериализации.
Открой обсуждение

2019-03-25 18:35 UTC, alinkov requested changes

2019-03-25 18:35 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private T[] items;
https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/domain/Chunk.java

Вот пример из спринга примерно такой же штуки.
Делают через List, НО используют ArryaList и копируют в него содеражние передаваемого. Можно сделать также. Просто с ArrayList'ом проблем не будет + не будет использоваться входной List

2019-03-25 18:35 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        public PageDtoBuilder<T> withFound(int found){
работает. Но  там нет ничего жесткого по отступам
и тут вроде сборка не прошла

2019-03-25 18:35 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    private static PageDto<RepositoryDto> getPage(List<RepositoryDto> list, int page, int perPage){
это в отдельной задаче.

2019-03-26 07:59 UTC, SuhoyVasya reviewed
пробую

2019-03-26 08:03 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RepositoryMapper.java
> +
код из другой ветки

2019-03-26 08:22 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +        if (dto1 == null || dto2 == null) {
код из другой ветки back-15

2019-03-26 08:22 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +        if (dto1 == dto2) {
код из другой ветки back-15

2019-03-26 08:22 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RepositoryMapper.java
> +        dto.setHasRelatedFrom(entity.getRelatedFrom() != null && !entity.getRelatedFrom().isEmpty());
код из другой ветки back-15

2019-03-26 08:22 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RepositoryMapper.java
> +
код из другой ветки back-15

2019-03-26 08:22 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RepositoryMapper.java
> +        if (dto == null) {
код из другой ветки back-15

2019-03-26 08:22 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        public PageDtoBuilder<T> withFound(int found){
наш чекстайл игнорит эти пробелы

2019-03-26 08:22 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +        if(dto != null && id == dto.getRepositoryId()){
добавил возврат ошибки 400 если id в pathParam не совпадате с id из dto

2019-03-26 08:22 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private T[] items;
не исправлял, Подумаю над этим

2019-03-26 08:22 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    private static PageDto<RepositoryDto> getPage(List<RepositoryDto> list, int page, int perPage){
не трогал

2019-03-26 11:25 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryServiceTest.java
> +        if (dto1 == null || dto2 == null) {
так может делать пр тогда не на мастер, а на 15?

2019-03-27 16:12 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +        assertEquals(controlPageDto, resultPageDto);
вот лучше не надеяться на equals каких-то сложных объектов...
лучше отдельно поля сверить

2019-03-27 16:12 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/config/TestConfig.java
> +        DBUtils.class,
зачем запятая?

2019-03-27 16:12 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/config/TestConfig.java
> +import java.util.List;
зачем импорты переставлять?
тем более были в нормальном порядке

2019-03-27 16:12 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +        protected RepositoryService repositoryService() {
думаю, что лучше будет добавлять данные в БД

2019-03-28 12:49 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +        assertEquals(controlPageDto, resultPageDto);
переделал

2019-03-28 12:49 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +        protected RepositoryService repositoryService() {
переделал

2019-03-28 12:49 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/config/TestConfig.java
> +        DBUtils.class,
убрал

2019-03-28 12:49 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/config/TestConfig.java
> +import java.util.List;
делал ребейз и накосячил с разрешением конфликтов.
Попробую исправить через автоформатирование

2019-03-28 18:32 UTC, alinkov reviewed
В общем норм. Нужно только с импортами разобраться

2019-03-28 18:32 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +        items = list.subList(startIndex, stopIndex).toArray(items);
```suggestion
        items = list.subList(startIndex, stopIndex).toArray(new RepositoryDto[0]);
```

2019-03-28 18:32 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +        repositoryDtoArray = StructCreator.createRepositoryDtoList().toArray(repositoryDtoArray);
```suggestion
        repositoryDtoArray = StructCreator.createRepositoryDtoList().toArray(new RepositoryDto[0]);
```

2019-03-28 18:32 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/config/TestConfig.java
> +import java.util.List;
Настрой сортировку имортов по дефолту и лишнее убери

2019-03-28 18:32 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/StructCreator.java
> +        List<RepositoryDto> dtoList = new ArrayList<>();
можно сделать по аналогии
```java
    public static List<GHRepositoryDto> createGHRepositoryDtoList(long count) {
        return LongStream.rangeClosed(1, count)
                .mapToObj(StructCreator::createGHRepositoryDto)
                .collect(Collectors.toList());
    }
```

2019-03-28 19:12 UTC, alinkov approved these changes

2019-03-28 19:12 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +public class PageDto<T> implements Serializable {
```suggestion
public class PageDto<T extends Serializable> implements Serializable {
```

2019-03-28 19:12 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        public PageDtoBuilder() {
обычно приватным делают

2019-03-28 19:12 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +            this.items = items;
Можно так
```suggestion
            this.items = Objects.requireNonNull(items, "Page items must not be null");
```

2019-03-29 07:07 UTC, anickishin requested changes

2019-03-29 07:07 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +        if (dto != null && id == dto.getRepositoryId()) {
Мне кажется, что стоит проверять существование записи с таким id.

2019-03-29 07:07 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +        int startIndex = perPage * page;
А если perPage <= 0?

2019-03-29 07:07 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private Integer found;
Зачем везде использовать Integer?

2019-03-29 07:07 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +        PageDto.PageDtoBuilder<RepositoryDto> builder = PageDto.builder();
А зачем создавать переменную? Можно просто return PageDto.builder().withFound(found) ... .build();

2019-03-29 07:07 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +@ContextConfiguration(classes = TestConfig.class)
А разве DepMonitoringTestBase не подгружает TestConfig?

2019-03-29 07:07 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +        PageDto.PageDtoBuilder<RepositoryDto> builder = PageDto.builder();
Зачем этот промежуточный этап? Можно просто `controlPageDto = PageDto.builder() ... .build();`

2019-03-29 09:30 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private Integer found;
безобразно но единообразно)

2019-03-29 09:30 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +            this.items = items;
поменял

2019-03-29 09:30 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +        if (dto != null && id == dto.getRepositoryId()) {
не думаю что в этом есть смысл если у нас есть несовпадение этих id

2019-03-29 09:30 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +        PageDto.PageDtoBuilder<RepositoryDto> builder = PageDto.builder();
поправил

2019-03-29 09:30 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +@ContextConfiguration(classes = TestConfig.class)
исправил

2019-03-29 09:30 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +        int startIndex = perPage * page;
этим будет заниматься сервис. Пока поправил

2019-03-29 09:30 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +        PageDto.PageDtoBuilder<RepositoryDto> builder = PageDto.builder();
поправил

2019-03-29 09:30 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private Integer found;
исправил

2019-03-29 09:30 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +        public PageDtoBuilder() {
исправил

2019-03-29 10:23 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +        PageDto.PageDtoBuilder<RepositoryDto> builder = PageDto.builder();
а зачем оставил builder?

2019-03-29 10:24 UTC, anickishin approved these changes

2019-03-29 10:24 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    public Integer getFound() {
```suggestion
    public int getFound() {
```
и в остальных геттерах

2019-03-29 10:35 UTC, merged