back-17 RepositoryLink Entity
hhru/hh-dep-monitoring pull request #19
Opened 2019-03-27 20:21 UTC by Afftobus

2019-03-27 20:54 UTC, alinkov requested changes

2019-03-27 20:54 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RepositoryDto.java
> +    @Nullable
Давай лучше notnull, лучше с пустой коллекцией работать.

2019-03-27 20:54 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RepositoryDto.java
> +    private Set<RepositoryLink> linkUrls;
Почему не DTO?

2019-03-27 20:54 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/Repository.java
> +    @OneToMany(mappedBy = "repositoryId", fetch = FetchType.EAGER)
Давай начнем с Lazy

2019-03-27 20:54 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/RepositoryLink.java
> +    private String linkType;
enum

2019-03-27 20:54 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/RepositoryLink.java
> +public class RepositoryLink {
у тебя они в set лежат, а equals и hashcode пуст.
P.S. все поля туда засовывать не надо. Думаю, что id будет достаточно

2019-03-28 18:00 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/RepositoryLink.java
> +public class RepositoryLink {
Добавил

2019-03-28 18:22 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RepositoryDto.java
> +    @NotNull
`@Nonnull`

2019-03-28 18:22 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/Repository.java
> +
не добавляй кучи пустых пробелов

2019-03-28 18:22 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RepositoryMapper.java
> +        if (urls == null) {
Предлагаю в Mapper добавить 2 метода
```java
    default List<D> toDto(List<E> entities) {
        return Stream.ofNullable(entities)
                .flatMap(List::stream)
                .map(this::toDto)
                .collect(Collectors.toList());
    }
    
    default List<E> toEntity(List<D> entities) {
        return Stream.ofNullable(entities)
                .flatMap(List::stream)
                .map(this::toEntity)
                .collect(Collectors.toList());
    }
```
И использовать их

2019-03-28 18:22 UTC, alinkov commented on hh-dep-monitoring-service/src/main/resources/db/migration/V3__create_repository_link.sql
> +CREATE TYPE repository_link_type AS ENUM (
Давай без типов. Пусть все на уровне Java разруливается. А то потом запутаемся

2019-03-29 06:49 UTC, anickishin requested changes

2019-03-29 06:49 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/RepositoryLink.java
> +        return Objects.equals(repositoryLinkId, repositoryLink.repositoryLinkId);
```suggestion
        return Objects.equals(repositoryLinkId, repositoryLink.getRepositoryLinkId());
```

2019-03-29 06:49 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/Mapper.java
> +//import java.util.stream.StreamSupport;
Забыл убрать

2019-03-29 06:49 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RepositoryMapper.java
> +//import ru.hh.school.depmonitoring.entities.RepositoryLink;
Убирай комментарии

2019-03-29 10:53 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/resources/db/migration/V2__create_relation.sql
> +    priority VARCHAR(255) NOT NULL
так наверное нельзя. У нас для этого настроены миграции

2019-03-29 18:46 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RepositoryDto.java
> +        return linkUrls == null ? new ArrayList<>() : linkUrls;
```suggestion
        return Optional.ofNullable(linkUrls).orElseGet(List::of);
```

2019-03-29 18:46 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RepositoryDto.java
> +        this.linkUrls = linkUrls;
Можно так делать
```suggestion
        this.linkUrls = Objects.requireNonNull(linkUrls);
```

2019-03-29 18:46 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/GHRepositoryMapperTest.java
> -    @Test
а почему убрал? Что тут не так

2019-03-29 18:46 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryMapperTest.java
> -        RepositoryDto dto = repositoryMapper.toDto(null);
укажи явно типы, скорее всего в них проблема
```java
RepositoryDto dto = repositoryMapper.toDto((Repository) null);
```

2019-03-29 19:28 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RepositoryMapper.java
> +    private final RepositoryLinkMapper repositoryLinkMapper = new RepositoryLinkMapper();
Это же бины. Нужно их инжектить

2019-03-29 19:28 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/GHRepositoryMapperTest.java
> +        assertNull(mapper.toDto((Repository)null));
пробелов добавь

2019-03-29 19:28 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/GHRepositoryMapperTest.java
> -    public void toEntityWithNull() {
вернул бы

2019-03-29 20:57 UTC, alinkov approved these changes

2019-03-30 18:22 UTC, anickishin approved these changes

2019-03-30 18:22 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryMapperTest.java
> +    //private final RepositoryMapper repositoryMapper = new RepositoryMapper();
Зачем оставил?

2019-03-31 09:43 UTC, merged