back-11 Add relation resource
hhru/hh-dep-monitoring pull request #20
Opened 2019-03-29 11:33 UTC by anickishin

Тесты пока не делал

2019-03-29 11:55 UTC, alinkov requested changes

2019-03-29 11:55 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RelationDao.java
> +    List<Relation> findByIdFrom(long repositoryId);
Рекомендую передавать полноценный Repository.
Чтобы потом понятнее было, что именно за long требуется и возможно предотвратит от лишних ошибок

2019-03-29 11:55 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RelationDao.java
> +    List<Relation> findByIdFrom(long repositoryId);
И `from` и `to` в названиях не особо нравится.
Но возможно это только моё мнение...

2019-03-29 11:55 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/GetRelationDto.java
> +public class GetRelationDto {
лучше по-другому назови.
Что-нибудь `DependentRelation` 
т.е. чтобы было понятно, в какую сторону связь идет.

2019-03-29 11:55 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RelationMapper.java
> +public class RelationMapper {
имплементируй интерфейс Mapper и работай с бином.
А то у тебя статические методы

2019-03-29 11:55 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +        if (relationDao.findOne(relationDto.getRelationId()).isPresent()) {
Все-таки лучше при update править существующую сущность, а не целиком из мапера получать...

2019-03-29 13:31 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RelationMapper.java
> +public class RelationMapper {
А как интерфейс это сделать? Там ведь один метод превращения в ДТО, а у меня может быть 2 варианта?

2019-03-29 13:59 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RelationMapper.java
> +public class RelationMapper {
сделай 2 маппера.

2019-03-29 15:03 UTC, colorbash requested changes

2019-03-29 15:03 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/GetRelationDto.java
> +public class GetRelationDto {
тут 3 варианта - 
1) париться со сторонами - разделить на InputRelationDto и OutputRelationDto 
2) сделать 1 дто но на заполнении инфы по Связи репы просто заполнять это дто не полностью
3) сделать на вход RelationDtoShort  с relationId, repositoryFromId, repositoryToId и заекстендить от него RelationDtо который можно будет возвращать с доп инфой на внешку при запросах

2019-03-29 15:03 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/GetRelationDto.java
> +public class GetRelationDto {
последний мне лично нравится больше

2019-03-29 15:03 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/SetRelationDto.java
> +        if (o == null || getClass() != o.getClass()) {
можно instanseof юзать)

2019-03-29 15:03 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/SetRelationDto.java
> +        if (o == null || getClass() != o.getClass()) {
и на нал не надо проверять

2019-03-29 15:03 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RelationResource.java
> +            return Response.status(Response.Status.NO_CONTENT).build();
кажется это особо не имеет смысла, 200 с телом - пустым массивом нормально бы работало
мое мнение что условие лишнее, только нагромождает код, его придется обрадатывать на фронте например
204 наверное больше нужно когда ты постишь что-то и тебе может вернуться 200 с телом если есть варнинги или месседж или же вернется 204 но без тела)
готов к дискуссии)

2019-03-29 15:03 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +    public void deleteRelation(int relationId) {
кажется что не нужно, можно напрямую к дао, никто не запрещал)

2019-03-29 15:10 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RelationDao.java
> +    List<Relation> findByIdFrom(long repositoryId);
ну если смотреть перевод то dependOn и dependOut (зависимый и зависящий), можно так

2019-03-29 16:18 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +    public void deleteRelation(int relationId) {
Смотря откуда. Из ресурса нельзя.
Т.к. там нет транзакции и она не должна начинаться в ресурсах.
Да и в общем плохо обращаться в дао из ресурсов. Если из сервиса, то норм

2019-03-30 13:30 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RelationResource.java
> +        if (relationDto != null && relationId == relationDto.getRelationId()) {
не пойму зачем вот эта двойная проверка. 
одновременно idдолжен быть и в path и в объекте и они должы совпадать.... не избыточно ли?

2019-03-31 08:04 UTC, SuhoyVasya approved these changes

2019-04-01 11:21 UTC, alinkov requested changes

2019-04-01 11:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RelationDto.java
> +    private final boolean repositoryToHasRelations;
а нам это разве нужно?
И думаю, что лучше для этих полей использовать Boolean, чтобы понимать было значение передано или оно просто не было проставлено

2019-04-01 11:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RelationDao.java
> +    List<Relation> findByIdDependOn(long repositoryId);
все-таки это название тоже не особо нравится.
Я бы попробовал что-нибудь вроде `main` и `dependent`
findRelationsByMainRepository()
findRelationsByDependentRepository()

Но лучше спроси у ребят. Если им так понятно, то оставь лучше так

2019-04-01 11:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +        RelationMapper.class,
уже есть

2019-04-01 12:08 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RelationDto.java
> +    private final boolean repositoryToHasRelations;
Это нужно для отображения дерева зависимостей (чтобы плюсик был только там, где можно раскрыть)

2019-04-01 14:25 UTC, alinkov requested changes

2019-04-01 14:25 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +            if (relationDto.getRepositoryFromId() != null && relationDto.getRepositoryFromId().equals(relation.getRepositoryFromId())) {
ты тут точно ничего не попутал?
`relationDto.getRepositoryFromId().equals(relation.getRepositoryFromId())` должно быть с `!` и во всех остальных

2019-04-01 14:26 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RelationDto.java
> +    private final boolean repositoryToHasRelations;
Так зачем он в обе стороны то? 
Вроде как + может быть только в одну сторону

2019-04-02 09:33 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RelationServiceTest.java
> +        relationService.deleteRelation(1);
Вот не очень мне нравится вот эти случайные id

2019-04-02 09:33 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RelationServiceTest.java
> +                .withRepositoryFromId(2L)
Тут тоже случайные id

2019-04-02 09:33 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RelationMapperTest.java
> +    public RelationMapperTest() {
Не так делается. @Setup

2019-04-02 09:33 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RelationDao.java
> +    List<Relation> findRelationsByMainRepositoryId(long repositoryId);
Всё-таки сейчас получается в разных местах по-разному...
Лучше все к одному типу привести

2019-04-02 09:33 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RelationServiceTest.java
> +        relationService.insertRelation(StructCreator.createRelationDto(null));
А что проверяется?

2019-04-02 19:02 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RelationServiceTest.java
> +        relationService.insertRelation(StructCreator.createRelationDto(null));
Не такая проверка не пойдет.
Надо хотя бы по id проверять
```java
var relation = StructCreator.createRelationDto(null);
relationService.insertRelation(StructCreator.createRelationDto(null));
assertNotNull(relation.getId());
assertTrue(dbUtils.getAll(Relation.class).stream().containsAny(r -> r.getId().equals(relation.getId());
```

2019-04-02 19:02 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RelationServiceTest.java
> +                .withRepositoryFromId(2L)
А почему зарезолвил? не увидел никаких действий

2019-04-04 06:30 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RelationDto.java
> +    private final boolean repositoryToHasRelations;
А я думал в обе
https://hh-school.slack.com/messages/GG95RMFFS/convo/GG95RMFFS-1553779855.013600/

2019-04-04 09:57 UTC, alinkov requested changes

2019-04-04 09:57 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/service/RelationServiceTest.java
> +        List relationList = dbUtils.getAll(Relation.class);
Почему List без дженерика? Так делать не стоит

2019-04-04 09:57 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/service/RelationServiceTest.java
> +        assertTrue(relationList.get(0) instanceof Relation);
И с дженериком это будет не нужно

2019-04-04 09:57 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/service/RelationServiceTest.java
> +        assertFalse(relationService.updateRelation(1, StructCreator.createRelationDto(null)));
Сделай в 2 строки

2019-04-04 09:57 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    public List<?> getAll(@Nonnull Class clazz) {
Сделай типизацию.
А так вообще можно через дао все это делать

2019-04-04 09:57 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    public Relation addRelation(RelationDto relationDto) {
Не нужно. Используй дао

2019-04-04 20:48 UTC, alinkov approved these changes
Апрув поставил авансом, т.к. не уверен, что завтра смогу быть на связи.
Но работу с исключениями стоит поправить

2019-04-04 20:48 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +        return relationMapper.toDto(relationDao.findRelationsByMainRepositoryId(repositoryDao.findOne(repositoryId).orElseThrow()));
Давай лучше в 2 строчки
И пиши нормально ошибку.
В данном случае `orElseThrow` не особо подойдет.
Делай какой-нибудь IllegalArgumentException и пиши нормальный текст

2019-04-04 20:48 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +        return relationMapper.toDto(relationDao.findRelationsByDependentRepositoryId(repositoryDao.findOne(repositoryId).orElseThrow()));
тут тоже

2019-04-04 20:48 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RelationMapper.java
> +        entity.setRepositoryFrom(repositoryDao.findOne(dto.getRepositoryFromId()).orElseThrow());
`orElseThrow()` лучше делать, когда этого вообще не может быть.
А так лучше `orElseThrow(() -> new SomeException("Error msg"));

2019-04-04 20:48 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    public <T> T doInReadOnlyTransaction(Supplier<T> func) {
Этот метод не нужен.
Используй метод выше. Скорее всего только запутает

2019-04-08 06:20 UTC, colorbash approved these changes

2019-04-08 06:20 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RelationMapper.java
> +        if (dto == null) {
давай кидать исключение, это полюбому ошибка, зачем дальше ее предавать?

2019-04-08 06:20 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +    private Repository getRepositoryDate(long repositoryId) {
почему называется так? getRepositoryDate

2019-04-08 06:20 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +            if (relationDto.getRepositoryFromId() != null &&
может так случится что часть ифов из этих четырех будет выполняться а часть нет?  это нормально?

2019-04-08 06:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RelationMapper.java
> +        if (dto == null) {
ну или пусть падает с НПЕ

2019-04-08 06:44 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +            if (relationDto.getRepositoryFromId() != null &&
да, нормально

2019-04-08 06:45 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +    private Repository getRepositoryDate(long repositoryId) {
Получение данных о репозитории.

2019-04-08 06:48 UTC, merged

2019-04-08 07:16 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RelationMapper.java
> +        if (dto == null) {
у нас все мапперы придерживаются этой логики

2019-04-08 11:38 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +    private Repository getRepositoryDate(long repositoryId) {
@anickishin тогда Data !
а не date

2019-04-08 11:39 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +    private Repository getRepositoryDate(long repositoryId) {
в мастер закоммить фикс, путает же конкретно

2019-04-08 11:39 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/RelationMapper.java
> +        if (dto == null) {
а ты уверен что это хорошо?