Front 10 Repository page
hhru/hh-dep-monitoring pull request #21
Opened 2019-03-31 14:31 UTC by K-ksenia

<img width="1440" alt="Снимок экрана 2019-03-31 в 17 22 55" src="https://user-images.githubusercontent.com/18597504/55290271-f7af9a00-53d9-11e9-98bf-92ea88e9ea49.png">
При нажатии на одну из Relations открываются принадлежащие выбранному репозиторию связи

<img width="1218" alt="Снимок экрана 2019-03-31 в 17 25 56" src="https://user-images.githubusercontent.com/18597504/55290277-1150e180-53da-11e9-984d-adac4f2b29a6.png">
У архивного репозитория, если наводим на значок, то появляется подсказка, что он означает.

2019-03-31 19:25 UTC, alinkov requested changes
Нужно починить сборку

2019-03-31 19:25 UTC, alinkov commented on frontend/src/MainBlock/Repository/ListItemDate.js
> +    created: PropTypes.string.isRequired,
а в чем разница между 
` PropTypes.object.isRequired` и ` PropTypes.string.isRequired` ?
почему в одном месте 1ое, а в другом 2ое?

2019-03-31 19:25 UTC, alinkov commented on frontend/src/MainBlock/Repository/PriorityLabel.js
> +import React, { Fragment } from 'react';
почему часть в `{}`, а часть без?

2019-03-31 19:25 UTC, alinkov commented on frontend/src/MainBlock/Repository/PriorityLabel.js
> +        backgroundColor: 'rgba( 245, 70, 0, 0.7)',
вроде hex в остальных местах используется.

2019-03-31 19:25 UTC, alinkov commented on frontend/src/MainBlock/Repository/RelationItem.js
> +        relation.hasRelations && !open ? setOpen(true) : setOpen(false);
можно так
```javascript
setOpen(relation.hasRelations && !open);
```

2019-03-31 21:19 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/ListItemDate.js
> +    created: PropTypes.string.isRequired,
разница в типе передаваемого параметра
В одном месте и в другом это ты про classes и created?

2019-03-31 21:19 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/PriorityLabel.js
> +import React, { Fragment } from 'react';
Потому что в реакте для React объявлен export default, а для Fragment просто export

2019-03-31 21:19 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/PriorityLabel.js
> +        backgroundColor: 'rgba( 245, 70, 0, 0.7)',
Да, но я хотела уменьшить насыщенность выбранных цветов путем добавления прозрачности.
В принципе получившиеся цвета все равно можно хексом представить
Если критично, исправлю

2019-03-31 21:19 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationItem.js
> +        relation.hasRelations && !open ? setOpen(true) : setOpen(false);
красота, спасибо!

2019-04-01 15:10 UTC, gooverdian requested changes

2019-04-01 15:10 UTC, gooverdian commented on frontend/src/Header/Navbar.js
> +    noDecoratedButton,
какое-то неподходящее название, класс используется на элементе Link и в самом классе нет никаких стилей, делающих его похожим на кнопку

2019-04-01 15:10 UTC, gooverdian commented on frontend/src/MainBlock/MainBlock.js
> +                <Route exact path="/Repositories/:repositoryId" component={Repository} />
это выбивается из логики routing, какой смысл иметь отдельный конфиг роутинга и все равно хардкодить путь тут?

2019-04-01 15:10 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/Repositories.js
> +import { fetchRepositories } from '../../redux/models/Repository/repositoriesActions';
лучше использовать абсолютные пути
вот так можно включить:
https://onoblog.com/absolute-path-imports-create-react-app/

2019-04-01 15:10 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/Repositories.js
> +    state => ({ repositories: state.repositories.repositories }),
уровень вложенности кажется лишним

2019-04-01 15:10 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/RepositoryItem.js
> +    return <ListItem button component={Link} {...props} />;
Теперь, когда это компонент более не стилизован, есть ли в нем смысл?

2019-04-01 15:10 UTC, gooverdian commented on frontend/src/MainBlock/Repository/ListItemDate.js
> +        <ListItemIcon>
Почему ты решила использовать компонент иконки для отображения текста?

2019-04-01 15:10 UTC, gooverdian commented on frontend/src/MainBlock/Repository/ListItemDate.js
> +            <div>
и зачем тут лишний div?

2019-04-01 15:10 UTC, gooverdian commented on frontend/src/MainBlock/Repository/PriorityLabel.js
> +    OPTIONAL: {
Какое-то усложнение, у элемента же может быть несколько классов, почему бы не
```
{
    priorityMark,
    CRITICAL: {
        backgroundColor: 'rgba( 245, 70, 0, 0.7)'
    },
    PARTIAL: {...},
    ...
}

className={classNames(priorityMark, classes[priority])}
```

Про rgba - норм, но если ты управляешь альфа-каналом для выбора цвета - знай, что из-за полупрозрачности на другом фоне это будет выглядет по-другому и так лучше не делать

2019-04-01 15:10 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationItem.js
> +                            visibility={relation.hasRelations ? 'inherit' : 'hidden'}
Нельзя стили в коде, надо классом

И вообще - эта иконка никогда не будет показана, если условие выполняется, зачем ее тогда вообще возвращать в jsx?

2019-04-01 15:10 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationItem.js
> +    const changeOpen = () => {
обычно, такие штуки называются toggle

2019-04-01 15:10 UTC, gooverdian commented on frontend/src/MainBlock/Repository/Repository.js
> +    }, [match.params]);
лучше вынести match.params.repositoryId в переменную и использовать ее

2019-04-01 15:10 UTC, gooverdian commented on frontend/src/Utils/commonStyles.js
> +        textDecoration: 'underline',
эта строка заставляет название тоже быть неподходящим

2019-04-01 15:10 UTC, gooverdian commented on frontend/src/redux/models/Relation/relationsActions.js
> +};
хочется уже посмотреть без тестовых данных

2019-04-01 15:10 UTC, gooverdian commented on frontend/src/redux/models/Repository/repositoriesReducer.js
> +    repositories: {},
чтобы не было repositories.repositories, можно переименовать, например в list

2019-04-02 21:15 UTC, K-ksenia commented on frontend/src/Header/Navbar.js
> +    noDecoratedButton,
суть класса в том, чтобы его использовать в кнопках-ссылках
Он отличается от noDecoratedLink только тем, что при наведении у него не будет подчеркиваться ссылка. Так как кнопки в matererial-ui и так подсвечиваются при наведении, и дополнительное подчеркивание будет излишним.
Как можно назвать в таком случае?

2019-04-02 21:15 UTC, K-ksenia commented on frontend/src/MainBlock/MainBlock.js
> +                <Route exact path="/Repositories/:repositoryId" component={Repository} />
Да, я согласна
Но так получилось, что роутинг у нас чисто для Navbar. Т.е. в компоненте Navbar лэйблы ссылок берутся отсюда. Так что у меня было 2 варианта 
1) переименовать routing в routingNavbar, а новый routing сделать для остальных ссылок
2) добавить в структуру routing флаг forNavbar, и в компоненте Navbar сделать фильтрацию по этому флагу
Но я вижу минусы и в том, и другом методе 
Как можно еще тут поступить?

2019-04-02 21:15 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/Repositories.js
> +import { fetchRepositories } from '../../redux/models/Repository/repositoriesActions';
Спасибо, исправила

2019-04-02 21:15 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/RepositoryItem.js
> +    return <ListItem button component={Link} {...props} />;
Убрала

2019-04-02 21:15 UTC, K-ksenia commented on frontend/src/Utils/commonStyles.js
> +        textDecoration: 'underline',
я могу noDecoratedButton переименовать тогда в noDecoratedLink, а noDecoratedLink в noDecoratedLinkWithHover?
Хотя noDecoratedLinkWithHover звучит длинновато

2019-04-02 21:15 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationItem.js
> +    const changeOpen = () => {
спасибо, переименовала

2019-04-02 21:15 UTC, K-ksenia commented on frontend/src/redux/models/Repository/repositoriesReducer.js
> +    repositories: {},
Переименовала

2019-04-02 21:15 UTC, K-ksenia commented on frontend/src/redux/models/Relation/relationsActions.js
> +};
Плюсую! Но у нас пока не готов ресурс на бэке

2019-04-02 21:15 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/PriorityLabel.js
> +    OPTIONAL: {
Спасибо, упростила
Про rgba буду иметь в виду. У нас все на белом фоне планируется пока

2019-04-02 21:15 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationItem.js
> +                            visibility={relation.hasRelations ? 'inherit' : 'hidden'}
Стили вынесла.

А если условие не выполняется, то будет показана
У нас `open` изначально `=false` и показывается `+` (если есть дальнейшие связи). Как на иконку нажимаем, `open` меняется на `true` и показывается `-` и т д. Так что все иконки будут показаны

2019-04-02 21:15 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/Repository.js
> +    }, [match.params]);
Вынесла

2019-04-02 21:15 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/ListItemDate.js
> +        <ListItemIcon>
У меня были проблемы с тем, чтобы вывести все так, как выводится сейчас. Т.е. название компонентом Typography и справа вверху (визуально на этой же линии) в 2 строчки 2 даты
Потому что хотелось использовать material ui и не переходить на дивы и флексы. В общем это единственный способ, который я нашла, чтобы выводилось именно так, как задумано 
Если лучше переделать на флексы или есть какие-то предложения с удовольствием выслушаю, потому что мне самой так не очень нравится

2019-04-02 21:15 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/ListItemDate.js
> +            <div>
Если его убираю, то даты схлопываются в одну строку

2019-04-02 21:15 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/ListItemDate.js
> +            <div>
сейчас поняла, что можно `ListItemIcon` просто убрать и оставить внутри дивов все, и оно тоже работает...

2019-04-02 21:15 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/ListItemDate.js
> +            <div>
Оставила только дивы в общем
Можно это как-то лучше сделать?

2019-04-04 13:02 UTC, gooverdian requested changes

2019-04-04 13:02 UTC, gooverdian commented on frontend/src/Header/Navbar.js
> +    noDecoratedButton,
по-английски было бы nonDecorated, или notDecorated, но тут дело не в этом, класс, который применяется к ссылке не должен называться button - если это кнопка-ссылка, то можно так и назвать buttonLink без упоминания о декорировании, название класса должно описывать не стиль, а то, к чему этот класс применяется.

2019-04-04 13:02 UTC, gooverdian commented on frontend/src/MainBlock/MainBlock.js
> +                <Route exact path="/Repositories/:repositoryId" component={Repository} />
Можно добавить в объекты routing массив inner, в котором перечислить внутренние роуты и перебрать их внутри map еще одним map, или, создать компонент-роутер внутри Repositories, который будет решать, отрисовать Repositories или Repository.. вариантов много, вот тот, который сейчас в коде - выглядит как-то костыльно, что будет, когда путей будет больше?

2019-04-04 13:02 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationItem.js
> +                            ? classes.icon : classNames(classes.icon, classes.hidden)}
у classnames есть замечательная возможность показывать или не показывать классы в зависимости от переменной:
```
className={classNames(classes.icon, {[classes.hidden]: !relation.hasRelations})}
```
и все еще непонятно, почему мы должны иметь иконку в DOM структуре, когда она гарантировано не будет показана для этого объекта

2019-04-04 13:02 UTC, gooverdian commented on frontend/src/MainBlock/Repository/Repository.js
> +    }, [match.params]);
и добавить ее в это условие, наверное, вроде, больше ни от чего не зависит вызов useEffect

2019-04-04 13:02 UTC, gooverdian commented on frontend/src/Utils/commonStyles.js
> +        textDecoration: 'underline',
я к тому, что нельзя одновременно говорить, что она не декорируется, и декорировать )

2019-04-04 13:05 UTC, gooverdian commented on frontend/src/Header/Navbar.js
>  import { routing } from '../MainBlock/MainBlock';
Раз теперь можно не использовать ../, то его лучше выпилить для красоты )

2019-04-04 21:08 UTC, K-ksenia commented on frontend/src/Header/Navbar.js
> +    noDecoratedButton,
Переименовала в buttonLink

2019-04-04 21:08 UTC, K-ksenia commented on frontend/src/Header/Navbar.js
>  import { routing } from '../MainBlock/MainBlock';
Сделала

2019-04-04 21:08 UTC, K-ksenia commented on frontend/src/MainBlock/MainBlock.js
> +                <Route exact path="/Repositories/:repositoryId" component={Repository} />
Сделала не так костыльно, но если подскажешь, как можно сделать лучше, буду очень благодарна
Потому что я часа 3 пыталась придумать, как сделать это за один обход или через какую-то рекурсивную функцию, и безуспешно..

2019-04-04 21:08 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationItem.js
> +                            ? classes.icon : classNames(classes.icon, classes.hidden)}
Переделала на добавление margin вместо иконки

2019-04-04 21:08 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/Repository.js
> +    }, [match.params]);
👌

2019-04-04 21:08 UTC, K-ksenia commented on frontend/src/Utils/commonStyles.js
> +        textDecoration: 'underline',
тогда назвала clickableLink
хотя, наверное, можно было и просто link назвать

2019-04-05 09:04 UTC, gooverdian requested changes

2019-04-05 09:04 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationItem.js
> +                    : relation.hasRelations && <AddIcon className={classes.icon} />
забавный тернарник

2019-04-05 09:04 UTC, gooverdian commented on frontend/src/MainBlock/MainBlock.js
> +                {routing && routing.map(item => (
Воу воу, зачем так сложно? почему бы не вызвать inner.map в первом routing.map?
По поводу рекурсии - можно, например, вот так https://codepen.io/gooverdian/pen/JVXwXg?editors=0010

их порядок же не так важен, он просто определяет приоритет для совпадающих путей

2019-04-05 09:05 UTC, gooverdian commented on frontend/src/Utils/commonStyles.js
> +        textDecoration: 'underline',
да, link подразумевает кликабельность, если кажется, что link - мало, то можно добавить универсальное слово generic

2019-04-05 15:36 UTC, gooverdian approved these changes
Теперь норм )

2019-04-07 09:59 UTC, alinkov approved these changes

2019-04-07 09:59 UTC, merged