Back-12 add pagination service
hhru/hh-dep-monitoring pull request #22
Opened 2019-03-31 19:19 UTC by SuhoyVasya

2019-03-31 19:56 UTC, alinkov requested changes

2019-03-31 19:56 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    public List<T> findPage(PageRequestDto pageRequestDto) {
`@Nonnull` и проверяй, что не null пришел

2019-03-31 19:56 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        return getSession()
Можно так сделать. Но это на твое усмотрение
```java
        CriteriaBuilder cb = getSession().getCriteriaBuilder();
        CriteriaQuery<Long> cq = cb.createQuery(Long.class);
        cq.select(cb.count(cq.from(clazz)));
        return getSession().createQuery(cq).getSingleResult();
```

2019-03-31 19:56 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    @DefaultValue("1")
1 не очень. Штук 20 делай

2019-03-31 19:56 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +            if(this.perPage<=0){
добавь пробелов

2019-03-31 19:56 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    public PageDto<RepositoryDto> getRepositriesPage(@DefaultValue("0") @QueryParam("page") int page,
PageRequestDto делай входным параметром
и тогда билдер не нужен будет

2019-03-31 19:56 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        if (pageRequestDto.getPerPage() <= 0 || pageRequestDto.getPage() < 0) {
ошибку в таком случае возвращай

2019-03-31 19:56 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +            RepositoryDto[] repositoryDtos = repositoryDao.findPage(pageRequestDto).stream()
```java
RepositoryDto[] repositoryDtos = repositoryDao.findPage(pageRequestDto).stream()
                .map(repositoryMapper::toDto)
                .toArray(RepositoryDto[]::new);
```

2019-03-31 19:56 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        int pages = found / pageRequestDto.getPerPage();
```suggestion
        int pages = (int) Math.ceil((double) found / pageRequestDto.getPerPage());
```

2019-03-31 19:56 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +                .withItems(StructCreator.createRepositoryDtoList().subList(0, 5).toArray(RepositoryDto[]::new))
можно сделать withItems, который будет List принимать

2019-03-31 19:56 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +                .readEntity(new GenericType<PageDto<RepositoryDto>>() {
```suggestion
                .readEntity(new GenericType<>() {
```

2019-03-31 19:56 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +        return target("/repository/page?page=" + page + "&perPage=" + perPage)
`?page=" + page + "&perPage=" + perPage`
задавай через queryParam

2019-04-01 09:40 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +                .withItems(StructCreator.createRepositoryDtoList().subList(0, 5).toArray(RepositoryDto[]::new))
сделал

2019-04-01 09:40 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    public List<T> findPage(PageRequestDto pageRequestDto) {
сделал

2019-04-01 09:40 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        return getSession()
не меняю

2019-04-01 09:40 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    @DefaultValue("1")
поменял

2019-04-01 09:40 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +            if(this.perPage<=0){
добавил

2019-04-01 09:40 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +            RepositoryDto[] repositoryDtos = repositoryDao.findPage(pageRequestDto).stream()
изменение не понадобилось

2019-04-01 09:40 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        int pages = found / pageRequestDto.getPerPage();
поменял

2019-04-01 09:40 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +        return target("/repository/page?page=" + page + "&perPage=" + perPage)
сделал

2019-04-01 09:40 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +                .readEntity(new GenericType<PageDto<RepositoryDto>>() {
не убирал. Без этого не проходит компиляция

2019-04-01 09:40 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        if (pageRequestDto.getPerPage() <= 0 || pageRequestDto.getPage() < 0) {
сделал

2019-04-01 10:38 UTC, alinkov approved these changes
Только почини ошибку сонара

2019-04-01 13:14 UTC, colorbash requested changes

2019-04-01 13:14 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private ArrayList<T> items;
зачем именно  ArrayList?

2019-04-01 13:14 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        } else {
а тут нужен else?

2019-04-01 13:14 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +        assertRepositoryDtoListIsEqual(StructCreator.createRepositoryDtoList(), controlRepositoryDtoList);
тут проверяется что 1 метод возвращает 2 одинаовых результата если его 2 раза вызвать?)

2019-04-01 13:14 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +    private Integer perPage;
зачем perPage - NotNull интегер, а page - инт

2019-04-02 05:21 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private ArrayList<T> items;
Как самый понятный из листов. Я что-то упускаю здесь?

2019-04-02 05:21 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +    private Integer perPage;
в PageDto изменил, здесь забыл, исправляю

2019-04-02 05:21 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        } else {
убрал

2019-04-02 05:21 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/RepositoryResourceTest.java
> +        assertRepositoryDtoListIsEqual(StructCreator.createRepositoryDtoList(), controlRepositoryDtoList);
Ахахах, вот это я доисправлялся) Переписываю

2019-04-02 05:42 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private ArrayList<T> items;
В примере, который я скидывал, было
`List page = new ArrayList ()`

2019-04-02 05:59 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private ArrayList<T> items;
До этого мы с тобой еще обговаривали десериализацию этого поля. Если оставить Лист то по твоим словам тут может оказаться неведомая реализация листа. Поэтому из конкретных листов я выбирал ArrayList

2019-04-02 07:56 UTC, colorbash approved these changes

2019-04-02 07:56 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +            if (items == null) {
у тебя эта проверка тут и в build(). зачем?
давай оставим одну

2019-04-02 08:09 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/Dao.java
> +    List<T> findPage(PageRequestDto pageRequestDto);
тоже бы `@Nonnull` пометил

2019-04-02 08:09 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private ArrayList<T> items;
Так ее снаружи никто не передаст. Посмотри внимательно пример.
Неведомая реализация может получиться, если ты List принимаешь снаружи, а если ты полностью с ним работаешь внутри, то никакой неведоемой реализации быть не может

2019-04-02 08:47 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +    private ArrayList<T> items;
Понял, поменяю

2019-04-02 08:47 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageDto.java
> +            if (items == null) {
хорошо, оставляю только финальные проверки

2019-04-02 08:47 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/Dao.java
> +    List<T> findPage(PageRequestDto pageRequestDto);
сделал

2019-04-03 05:38 UTC, merged