Back 20 RepositoryLink Resource
hhru/hh-dep-monitoring pull request #24
Opened 2019-04-06 19:41 UTC by Afftobus

2019-04-06 21:50 UTC, SuhoyVasya approved these changes

2019-04-06 21:50 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResource.java
> +    @Path("/add")
думаю "/add" - лишнее

2019-04-06 21:50 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/add")
тогда уж по аналогии с Put добавить в путь repository_id

2019-04-07 06:49 UTC, colorbash requested changes

2019-04-07 06:49 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +            return 0;
давай хотя бы нулл будем отдавать и возвращать Integer, тут ты знаешь что 0 ид не может быть, а другой чувак придет и дого будет разбираться почему не работатет

2019-04-07 06:49 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResource.java
> +                orElse(null);
если нет это 404

2019-04-07 06:49 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +        if (!repositoryLinkDao.isIdExist(repositoryLinkDto.getRepositoryLinkId())) {
на сколько я помню есть у сессии  - update, save и saveOrUpdate кажется update должен не выполнится если в бд нет записи с таким ид, и это условие не нужно, не помню только он исключение кинет или как узнать что операция не произошла.

2019-04-07 06:49 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +        if (dto != null
на нул вмето проверки можно аннотацию повесить в сигнатуре

2019-04-07 06:49 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +        if (dto != null && service.create(dto)) {
вообще я бы делал проверки на то что обновилось/создалось что-то в сервисе через исключения, вроде как это действительно редкий кейс и нужно через несколько эшелонов перепрыгнуть, кидаешь WebApplicationException(тут статус и месседж) и вроде как удобнее
но может я и не прав

2019-04-07 06:49 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        if (repositoryDao.isIdExist(dto.getRepositoryId())) {
у нас ид совпадает с ид из внешнего источника? если нет, ты не должен давать пользователю задвать ид как ему хочется, нужно проверять на входе в ресурс что ид == нул и тогда только сохранять дто в бд, при сохранении бд сама назначит ему ид.

2019-04-07 10:15 UTC, alinkov requested changes

2019-04-07 10:15 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    public boolean isIdExist(I id) {
зачем?
особого смысла нет

2019-04-07 10:15 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        getSession().save(entity);
что решаешь этим?
почему persist на save поменял

2019-04-07 10:15 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryLinkDaoImpl.java
> +    public List<RepositoryLink> findForRepository(@Nonnull long repositoryId) {
`@Override` и добавь сортировку

2019-04-07 10:15 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResource.java
> +@Path("/repository_link")
нижнее подчеркивание обычно не используется в пути
Определитесь как будете camelCase или через `-`

2019-04-07 10:15 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResource.java
> +        return Response.status(Response.Status.BAD_REQUEST).build();
можно кидать IllegalArgumentException
оно вроде мапится на BAD_REQUEST

2019-04-07 10:15 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResource.java
> +    public RepositoryLinkDto addOne(RepositoryLinkDto repositoryLinkDto) {
почему не просто save или saveRepositoryLink

2019-04-07 10:15 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +        return repositoryLinkMapper
что-то как-то странно переносы сделаны

2019-04-07 10:15 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResourceTest.java
> +        dbUtils.addItemToRepositoryTable(1L);
`1L` в переменную

2019-04-07 10:15 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResourceTest.java
> +        assertEquals(0, resultListRepositoryLinkDto.size());
isEmpty  используй

2019-04-07 10:15 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResourceTest.java
> +                .acceptEncoding("identity")
зачем?

2019-04-08 06:49 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResource.java
> +    public RepositoryLinkDto addOne(RepositoryLinkDto repositoryLinkDto) {
была идея явно разделить добавление нового и редактирование старого. Save не раскрывает сути и может относиться к обоим вариантам

2019-04-08 06:49 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +        if (dto != null && service.create(dto)) {
я проверяю на наличие изменяемого id, так что логичнее было бы, наверное, IllegalArgumentException.... не?

2019-04-08 06:50 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        if (repositoryDao.isIdExist(dto.getRepositoryId())) {
по репозиториям да, мы получаем ID извне

2019-04-09 06:32 UTC, colorbash commented
надо поребейзится

2019-04-09 11:18 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RepositoryLinkDao.java
> +    public List<RepositoryLink> findForRepository(long repositoryID);
Лучше писать так `repositoryId`
Тем более в реализации именно так и называется

2019-04-09 11:18 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> -    public int getFirstExistingIdOfrepositoryLink() {
Сделай optional

2019-04-09 11:18 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryLinkDaoImpl.java
> +                .createQuery("from RepositoryLink where repositoryId = :repositoryId order by repositoryLinkId", RepositoryLink.class)
А почему по repositoryLinkId ?

2019-04-09 11:18 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +        Optional<RepositoryLink> oldEntityOpt = repositoryLinkDao.findOne(newEntity.getRepositoryLinkId());
`oldEntityOpt` как-то странно звучит

уж лучше `currentRepositoryLink`
И от optional'а лучше сразу избавляться
```java
var currentRepositoryLink = repositoryLinkDao.findOne(newEntity.getRepositoryLinkId())
.orElseThrow(() -> new IllegalArgumentException("Incorrect repository link id"));
```

2019-04-09 11:18 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +            throw new IllegalArgumentException("Illegal parameters");
С таким исключением ты потом голову взорвешь, что же произошло

2019-04-09 18:15 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +        Optional<RepositoryLink> oldEntityOpt = repositoryLinkDao.findOne(newEntity.getRepositoryLinkId());
мне тут надо дёрнуть из базы, проверить на isEmpty и использовать дальше. 
если я буду делать что-то типа 
if (!repositoryDao.findOne(dto.getRepositoryId()).isEmpty())
   throw ... 
Repository oldRepository = repositoryDao.findOne(dto.getRepositoryId()).iget()

то это 2 похода в базу. Поэтому я сделал такую странную переменную. 
можно как-то красивее?

2019-04-10 11:47 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +        Optional<RepositoryLink> oldEntityOpt = repositoryLinkDao.findOne(newEntity.getRepositoryLinkId());
Так я тебе итак прислал вариант. Там не нужно никакого второго похода в БД

2019-04-10 18:27 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/rs/RepositoryResourceTest.java
> +                .queryParam("per-page", perPage)
А аргументы то зачем переименовать?
Мы про урлы же говорили

2019-04-10 18:27 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResource.java
> +    public RepositoryLinkDto addOne(RepositoryLinkDto repositoryLinkDto) {
Лучше переименуй

2019-04-10 18:27 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/add")
А зачем тут вообще этот `add` сделай просто `/` и все

2019-04-10 18:33 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/rs/RepositoryResourceTest.java
> +                .queryParam("per-page", perPage)
это же GET`ом прилетает. тоже в адресной строке....
поговорили, решили поменять... не правильно?

2019-04-10 18:35 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/rs/RepositoryResourceTest.java
> +                .queryParam("per-page", perPage)
ну смотрите. Можно и так оставить, главное, чтобы потом везде одинаково было

2019-04-10 18:51 UTC, alinkov approved these changes

2019-04-10 20:35 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/rs/RepositoryResourceTest.java
> +                .queryParam("per-page", perPage)
не ну это точно через - никто не пишет

2019-04-10 20:36 UTC, colorbash approved these changes

2019-04-11 06:03 UTC, anickishin requested changes

2019-04-11 06:03 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        return entity;
Здесь не нужен return

2019-04-11 06:03 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RepositoryLinkDto.java
> +    private Integer repositoryLinkId;
А почему на Integer поменял? По логике если в репозиториях лонг, то здесь должно быть не меньше

2019-04-11 06:03 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RelationResource.java
> +    @Produces(MediaType.APPLICATION_JSON)
А зачем Relation трогаешь? Это же моя задача

2019-04-11 06:19 UTC, anickishin requested changes

2019-04-11 06:19 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +        RepositoryLink newEntity = repositoryLinkMapper.toEntity(repositoryLinkDto);
Зачем создавать entity? Можно и с Dto работать

2019-04-11 06:19 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        Repository newEntity = repositoryMapper.toEntity(dto);
Тоже самое. Можно с Dto работать

2019-04-11 06:19 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        if (repositoryDao.findOne(dto.getRepositoryId()).isPresent()) {
При создании вообще не должно быть id у сущности. Иначе ошибка.

2019-04-11 06:19 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResource.java
> +    public Response findOne(@PathParam("id") int id) {
Для какого случая нужна эта функция?

2019-04-11 06:19 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
>          return service.getRepositoryPage(requestDto);
Может стоит уйти от getAllRepositories и работать только с постраничной отдачей?

2019-04-11 06:19 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    public int repositoryLinkCount() {
Можно делать такие функции в DBUtils.doInTransaction

2019-04-11 06:38 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        return entity;
а как ты получишь ещё ID свежесозданной записи?

2019-04-11 06:39 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/RepositoryLinkDto.java
> +    private Integer repositoryLinkId;
я так понял, что у нас лонг не потому, что мы хотим содержать > MAX_INT записей, а потому что именно так он приходит из гитхаба, а по сути инта нам вполне хватит

2019-04-11 06:39 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RelationResource.java
> +    @Produces(MediaType.APPLICATION_JSON)
я всё потрогал, чтоб сделать однообразно.

2019-04-11 06:47 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +        RepositoryLink newEntity = repositoryLinkMapper.toEntity(repositoryLinkDto);
по большому счету да, но в DAO я буду всё равно пихать entity

2019-04-11 06:47 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        if (repositoryDao.findOne(dto.getRepositoryId()).isPresent()) {
эт как?
мы же везде ведём курс на notnull параметры, так что запрещать передавать id по-моему не правильно.

2019-04-11 06:47 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    public int repositoryLinkCount() {
а мы не получим каких-либо спецэффектов от этого? 
чем тебе не нравится такой вариант?

2019-04-11 06:51 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResource.java
> +    public Response findOne(@PathParam("id") int id) {
чтоб было О_о
ты считаешь, что не нужно давать возможности дёрнуть сущность по ID?

2019-04-11 06:54 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
>          return service.getRepositoryPage(requestDto);
может быть... вопрос к фронту. 
при открытии, например, всех связанных мы тоже будем отдавать постранично?

2019-04-11 07:32 UTC, anickishin requested changes

2019-04-11 07:32 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +        return repositoryLinkMapper.toDto(repositoryLinkDao.create(repositoryLinkMapper.toEntity(repositoryLinkDto)));
Разбей на строки

2019-04-11 07:33 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        return entity;
В сущности, которую ты передаёшь в этот метод, он появится

2019-04-11 07:34 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +        RepositoryLink newEntity = repositoryLinkMapper.toEntity(repositoryLinkDto);
Будешь пихать entity, но другой. А это действие, по большому счёту, бесполезное.

2019-04-11 07:36 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        if (repositoryDao.findOne(dto.getRepositoryId()).isPresent()) {
При persist, если у тебя в entity есть id, вылетит ошибка.

2019-04-11 07:48 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        if (repositoryDao.findOne(dto.getRepositoryId()).isPresent()) {
у меня же тесты именно  так и делают
и проходят норм

2019-04-11 07:49 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +        return repositoryLinkMapper.toDto(repositoryLinkDao.create(repositoryLinkMapper.toEntity(repositoryLinkDto)));
по началу у меня было разбито, но там вложенность и строки будут начинаться по диагонали, поэтому 
![image](https://user-images.githubusercontent.com/22192804/55939857-8678ae00-5c47-11e9-9dad-dec7d1044d30.png)

2019-04-11 08:22 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +        return repositoryLinkMapper.toDto(repositoryLinkDao.create(repositoryLinkMapper.toEntity(repositoryLinkDto)));
```suggestion
        repositoryLink entity = repositoryLinkMapper.toEntity(repositoryLinkDto);
        repositoryLinkDao.create(entity);
        return repositoryLinkMapper.toDto(entity);
```

2019-04-11 08:26 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        if (repositoryDao.findOne(dto.getRepositoryId()).isPresent()) {
Я забыл, что у тебя id берутся из github. Если бы был SERIAL, то такое бы не прошло. А в каких тогда ситуациях в ресурсе нужно добавление новых репозиториев?

2019-04-11 09:05 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +        return repositoryLinkMapper.toDto(repositoryLinkDao.create(repositoryLinkMapper.toEntity(repositoryLinkDto)));
а тут создавать дополнительную работу для GC О_о ?

2019-04-11 09:21 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        if (repositoryDao.findOne(dto.getRepositoryId()).isPresent()) {
вообще - для тех случаев, когда у нас есть проект зависимый/зависящий от чего либо, но не полученный из гитхаба. 
но на той встрече постановили, что такого не будет.... не знаю... запрещать такую возможность? оставлять только изменение?

2019-04-11 10:50 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +        return repositoryLinkMapper.toDto(repositoryLinkDao.create(repositoryLinkMapper.toEntity(repositoryLinkDto)));
Какую доп. работу? Ты создаёшь ровно столько же объектов. Просто так ты сохраняешь указатель на один из них (в обоих случаях создаются RepositoryLinkDto, RepositoryLink и ещё один RepositoryLinkDto).

2019-04-11 10:51 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    public int repositoryLinkCount() {
Спецэффектов не должны получить, но так код немного почище получится

2019-04-11 10:52 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
>          return service.getRepositoryPage(requestDto);
Насколько я понимаю, мы всё равно не должны использовать эту функцию. Другой вопрос, что это немного не по твоей задаче. А про связанные - так там другая история.

2019-04-11 10:53 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResource.java
> +    public Response findOne(@PathParam("id") int id) {
Мне кажется, что не нужно создавать функции, которые не требуются на фронте. Из тестов ты можешь дёргать другими способами.

2019-04-11 10:54 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        if (repositoryDao.findOne(dto.getRepositoryId()).isPresent()) {
Мне кажется, что стоит исключить. При необходимости будет несложно добавить.

2019-04-11 12:07 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        return entity;
это не принципиальный момент.
Делайте, как считаете удобным

2019-04-11 12:07 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResource.java
> +    public Response findOne(@PathParam("id") int id) {
Это нормальная возможность для REST. Так что в этой функции нет ничего плохого.
Но название тут явно лучше бы поменять

2019-04-11 12:07 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResource.java
> +    public RepositoryLinkDto addOne(RepositoryLinkDto repositoryLinkDto) {
`addOne` не очень в названии
Сделай лучше `saveRepositoryLink`

2019-04-11 17:55 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResource.java
> +public class RepositoryLinkResource {
Добавляй
```java
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
```
над классом, тогда не нужно будет над каждым методом повторять

2019-04-11 17:55 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +        if (repositoryLinkDto.getLinkUrl() != null) {
а зачем тут проверка?
эти поля разве не обязательно должны придти с клиента?

2019-04-11 17:55 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +    public RepositoryLinkDto addOne(RepositoryLinkDto repositoryLinkDto) {
`saveRepositoryLink`

2019-04-11 17:55 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    public int getTableCount(Class clazz) {
название не верное.
Тут `getEntitiesCount` или как-то так. Потому что table тут никак не фигурирует

2019-04-11 17:55 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    public Integer getFirstExistingIdOfrepositoryLink() {
лучше Optional

2019-04-11 18:53 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +        if (repositoryLinkDto.getLinkUrl() != null) {
так тыж сам говорил, что если некоторые поля не приходят, то их не апдейтим вообще. 
а что такое "не приходят" с точки зрения кода? 
вот я и проверяю на null

2019-04-11 18:58 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +        if (repositoryLinkDto.getLinkUrl() != null) {
Ну смотря как планируется обновление. Тут неверное особого смысла нет в этой логике. Прости нужно понимать, что будет обновляться, а что нет

2019-04-11 20:37 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryLinkService.java
> +    public Optional<RepositoryLinkDto> findOne(int id) {
тоже findOne
переименуй

2019-04-11 20:37 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResourceTest.java
> +                .orElseThrow(() -> new WebApplicationException("No entity found in base!"));
`WebApplicationException` тут не нужно. Оно не для этих целей создано. Лучше что-нибудь другое.
А так вообще достаточно просто `orElseThrow()`
В тестах так можно делать, но в production коде так делать не стоит, т.к. потом тяжело будет найти концы.
А в тестах будет все понятно.

2019-04-12 07:25 UTC, anickishin requested changes

2019-04-12 07:25 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        currentRepository.setUpdatedAt(LocalDateTime.now());
У нас updatedAt завязан с гитхабом.

2019-04-12 07:40 UTC, anickishin approved these changes

2019-04-12 13:00 UTC, merged