Back 24 Add sorting to relation resource
hhru/hh-dep-monitoring pull request #26
Opened 2019-04-11 08:52 UTC by anickishin

2019-04-11 09:18 UTC, colorbash requested changes

2019-04-11 09:18 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +        relationDtoList.sort(
не, давай сделаем сортировку через sql запрос, зачем код писать если база за тебя сделает, еще и в 1м месте.

2019-04-11 09:18 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    @Transactional
а эти аннотации работают не на бинах разве?

2019-04-11 10:44 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +        relationDtoList.sort(
Я думал об этом, но нам нужна сортировка по приоритету, который хранится в виде строки.

2019-04-11 11:56 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RelationResource.java
> +    @Produces(MediaType.APPLICATION_JSON)
```java
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
```
можно на весь ресурс повесить, чтобы над каждым методом не писать

2019-04-11 11:56 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +        relationDtoList.sort(
выдели хотя бы этот кусок кода в отдельный метод. Сейчас у тебя в 2 местах

2019-04-11 18:16 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +        relationDtoList.sort(
там сортировка разная

2019-04-12 13:04 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +        relationDtoList.sort(
Что-то как-то все-таки не очень получается.
Вот наверное лучше было группировать по типу. И думаю, что это для фронта будет удобнее.
И тогда сортировку можно будет сделать в БД

Т.е. возвращать `Map<RepositoryRelationPriority, List<RelationDto>>`
Чтобы потом можно было даже разбить по группам

2019-04-14 20:26 UTC, alinkov approved these changes
Ладно, пусть пока будет так...

2019-04-15 06:26 UTC, colorbash approved these changes

2019-04-15 09:11 UTC, merged