Back 27 Add Repository Type
hhru/hh-dep-monitoring pull request #27
Opened 2019-04-12 18:42 UTC by Afftobus

2019-04-12 20:17 UTC, colorbash approved these changes
небольшие замечания

2019-04-12 20:17 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResource.java
> +        return new ArrayList<>(Arrays.asList(RepositoryLinkType.values()));
зачем оборачивать в new ArrayList<>( если Arrays.asList и так вернет иммутабельный аррейлист
если бы возвращал другое, надор было бы кастить а не в конструктор передавать

2019-04-12 20:17 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/valid-types")
можно просто types

2019-04-13 06:37 UTC, alinkov requested changes

2019-04-13 06:37 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/RepositoryType.java
> +    LIBRUARY,
```suggestion
    LIBRARY,
```

2019-04-13 06:37 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryLinkResource.java
> +        return new ArrayList<>(Arrays.asList(RepositoryLinkType.values()));
Слишком сложно...
Возвращал бы тогда вообще массив
```java
public RepositoryLinkType[] getValidRepositoryTypes() {
    return RepositoryLinkType.values();
}
```
Ну или так
```java
public List<RepositoryLinkType> getValidRepositoryTypes() {
    return List.of(RepositoryLinkType.values());
}
```

2019-04-13 06:37 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    public ArrayList<RepositoryType> getValidRepositoryTypes() {
тоже упрощай

2019-04-13 06:42 UTC, SuhoyVasya approved these changes

2019-04-13 08:20 UTC, alinkov approved these changes

2019-04-13 10:26 UTC, merged