Back 25
hhru/hh-dep-monitoring pull request #28
Opened 2019-04-14 18:08 UTC by SuhoyVasya

Добавил инструкицю как запустить все приложение в контецнерах с помощью Docker compose

2019-04-14 20:25 UTC, alinkov requested changes

2019-04-14 20:25 UTC, alinkov commented on hh-dep-monitoring-service/dockerfile
> +COPY /target/hh-dep-monitoring-service-1.0-SNAPSHOT-shaded.jar /backend/
Давай имя поменяем. Чтобы версия не участвовала

2019-04-14 20:25 UTC, alinkov commented on README.md
> +2) Собираем сервич в uber-jar. В папке hh-dep-monitoring-service:
Сервис

2019-04-14 20:25 UTC, alinkov commented on README.md
> +3)  Собираем докер образ сервиса. В папке hh-dep-monitoring-service:
Добавил бы docker maven plugin, чтобы одной командой все это делалось

2019-04-14 20:25 UTC, alinkov commented on docker-compose.yml
> +    image: "suhoyvasya/postgres-monitoring"
зачем? Опиши тут весь конфиг. 
`suhoyvasya/postgres-monitoring` чем отличается от дефолтного?

2019-04-15 06:27 UTC, colorbash commented on hh-dep-monitoring-service/.dockerignore
> +!target/
пустая строка

2019-04-15 08:03 UTC, SuhoyVasya commented on README.md
> +2) Собираем сервич в uber-jar. В папке hh-dep-monitoring-service:
исправил

2019-04-15 08:03 UTC, SuhoyVasya commented on docker-compose.yml
> +    image: "suhoyvasya/postgres-monitoring"
сделал

2019-04-15 08:03 UTC, SuhoyVasya commented on hh-dep-monitoring-service/dockerfile
> +COPY /target/hh-dep-monitoring-service-1.0-SNAPSHOT-shaded.jar /backend/
поменял на hh-dep-monitoring-service.jar

2019-04-15 08:03 UTC, SuhoyVasya commented on README.md
> +3)  Собираем докер образ сервиса. В папке hh-dep-monitoring-service:
добавил

2019-04-15 08:06 UTC, SuhoyVasya commented on hh-dep-monitoring-service/.dockerignore
> +!target/
исправил

2019-04-17 17:47 UTC, alinkov commented on frontend/nginx.conf
> +http {
Что-то отступы везде разные

2019-04-17 17:47 UTC, alinkov commented on frontend/dev_nginx.conf
> +		  	rewrite ^/api/(.*)$ /$1 break;
А зачем это?

2019-04-17 17:47 UTC, alinkov commented on frontend/nginx.conf
> +		  	rewrite ^/api/(.*)$ /$1 break;
И тут

2019-04-18 05:25 UTC, SuhoyVasya commented on frontend/dev_nginx.conf
> +		  	rewrite ^/api/(.*)$ /$1 break;
чтобы транслировать "localhost/api/repositories...." в "containeradress/repositories...."

2019-04-18 05:25 UTC, SuhoyVasya commented on frontend/nginx.conf
> +http {
отформатировал

2019-04-18 05:25 UTC, SuhoyVasya commented on frontend/nginx.conf
> +		  	rewrite ^/api/(.*)$ /$1 break;
см выше

2019-04-18 06:15 UTC, alinkov commented on frontend/dev_nginx.conf
> +		  	rewrite ^/api/(.*)$ /$1 break;
А proxy_pass разве недостаточно?

2019-04-18 06:30 UTC, SuhoyVasya commented on frontend/dev_nginx.conf
> +		  	rewrite ^/api/(.*)$ /$1 break;
без этого будет
"localhost/api/repositories...." в "containeradress/api/repositories...."

2019-04-18 08:55 UTC, alinkov commented on frontend/dev_nginx.conf
> +		  	rewrite ^/api/(.*)$ /$1 break;
ты уверен, что это будет так?

2019-04-18 09:57 UTC, SuhoyVasya commented on frontend/dev_nginx.conf
> +		  	rewrite ^/api/(.*)$ /$1 break;
я проверял

2019-04-18 10:32 UTC, SuhoyVasya commented on frontend/dev_nginx.conf
> +		  	rewrite ^/api/(.*)$ /$1 break;
Подтверждаю. без этой строчки все перестает работать. Как вариант обхода могу предложить в сервисе сделать @Path("/api")

2019-04-18 13:51 UTC, alinkov approved these changes
ok, ставлю апрув, но забирать буду после того, как кто-нибудь из ребят выполнит эту инструкцию

2019-04-21 10:45 UTC, colorbash approved these changes

2019-04-21 10:45 UTC, colorbash commented on README.md
> +	    docker-compose up
у меня без судо не стартует

2019-04-21 15:52 UTC, alinkov commented on hh-dep-monitoring-service/pom.xml
> +                        <phase>package</phase>
а зачем на package?
давай хотя бы на install. А лучше в профиль отдельный

2019-04-22 07:46 UTC, alinkov commented on README.md
> +	    docker-compose up
@SuhoyVasya допиши, что нужно пользователя добавить в группу докера (хотя это возможно нужно только для linux/mac)

2019-04-23 08:06 UTC, SuhoyVasya commented on README.md
> +	    docker-compose up
Добавил ссыль в README где есть вся информация

2019-04-23 08:39 UTC, alinkov commented on docker-compose.yml
> +version: '2.1'
а зачем версию понизил?

2019-04-23 08:39 UTC, alinkov commented on README.md
> +   `https://www.digitalocean.com/community/tutorials/docker-ubuntu-16-04-ru`
давай лучше с офф сайта 
https://docs.docker.com/install/linux/linux-postinstall/

2019-04-23 08:39 UTC, alinkov commented on docker-compose.yml
> +    image: "postgres:11-alpine"
думаю, что Dockerfile постгреса можно удалить

2019-04-23 08:39 UTC, alinkov commented on frontend/dev_nginx.conf
> +      proxy_pass http://172.19.0.1:3000;
а всегда этот ip прокидывается?

2019-04-23 08:39 UTC, alinkov commented on frontend/nginx.conf
> +      root /frontend;
try files не забудь добавить

2019-04-23 10:42 UTC, SuhoyVasya commented on README.md
> +   `https://www.digitalocean.com/community/tutorials/docker-ubuntu-16-04-ru`
сделал

2019-04-23 10:42 UTC, SuhoyVasya commented on docker-compose.yml
> +version: '2.1'
в третьей убрали depends_on - condition

2019-04-23 10:42 UTC, SuhoyVasya commented on docker-compose.yml
> +    image: "postgres:11-alpine"
удалил

2019-04-23 10:42 UTC, SuhoyVasya commented on frontend/dev_nginx.conf
> +      proxy_pass http://172.19.0.1:3000;
Закостылил

2019-04-23 10:42 UTC, SuhoyVasya commented on frontend/nginx.conf
> +      root /frontend;
добавил

2019-04-23 17:40 UTC, alinkov commented on docker-compose.yml
> +version: '2.1'
может лучше через `wait-for-it` ?
Будет более надежно

2019-04-23 17:40 UTC, alinkov commented on hh-dep-monitoring-service/Dockerfile
> +CMD ["java", "-jar", "-DsettingsDir=/backend/configs","/backend/hh-dep-monitoring-service.jar"]
желательно еще xms и xmx указать

2019-04-23 17:41 UTC, alinkov commented
Разрули конфликты

2019-04-25 17:22 UTC, merged