back-26 Add maven dependency
hhru/hh-dep-monitoring pull request #29
Opened 2019-04-15 08:18 UTC by anickishin

2019-04-15 09:43 UTC, colorbash requested changes

2019-04-15 09:43 UTC, colorbash commented on hh-dep-monitoring-service/src/main/resources/db/migration/V5__create_dependency.sql
> +    artifact_version_id SERIAL PRIMARY KEY,
по идее тут отдельный ид не нужен, можно сделать парный ид(artifact_id, version)
но если очень лень можно оставить

2019-04-15 09:43 UTC, colorbash commented on hh-dep-monitoring-service/src/main/resources/db/migration/V5__create_dependency.sql
> +CREATE TABLE IF NOT EXISTS dependency (
а вообще по сути нам не нужна связь многие к многим, как что наверное эту таблицу не надо создавать
у каждой вепы может быть много версий, но у 1 версии только 1 репа
это 1 к многим, dependency не нужон

2019-04-15 10:31 UTC, anickishin commented on hh-dep-monitoring-service/src/main/resources/db/migration/V5__create_dependency.sql
> +CREATE TABLE IF NOT EXISTS dependency (
dependency - это таблица зависимостей наших реп от артефактов. То есть n реп могут быть завязаны на одном артефакте, а 1 репа может быть завязана на n артефактов.

2019-04-15 12:17 UTC, colorbash commented on hh-dep-monitoring-service/src/main/resources/db/migration/V5__create_dependency.sql
> +CREATE TABLE IF NOT EXISTS dependency (
ох у меня чет в глазах расплылось, да чет думал что вместо repository_id - artifact_id

2019-04-15 12:18 UTC, colorbash approved these changes

2019-04-17 12:13 UTC, alinkov approved these changes

2019-04-17 12:15 UTC, merged