Back 32 Add relation check before add or update
hhru/hh-dep-monitoring pull request #30
Opened 2019-04-17 16:30 UTC by Afftobus

2019-04-18 06:22 UTC, anickishin requested changes

2019-04-18 06:22 UTC, anickishin commented on hh-dep-monitoring-service/src/main/resources/db/migration/V4__create_unique_index_in_relation.sql
> +CREATE UNIQUE INDEX ON relation (repository_from_id, repository_to_id);
Перенос строки

2019-04-18 06:22 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/rs/RelationResourceTest.java
> +        assertEquals(Response.Status.INTERNAL_SERVER_ERROR.getStatusCode(), response.getStatus());
Мне кажется, что на существующую связь нужно возвращать BAD_REQUEST

2019-04-18 06:22 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    public Relation addRelation(long from, long to) {
Лучше так:
```
@Transactional
public Relation addRelation(RelationDto relationDto) {
    Relation result = relationMapper.toEntity(relationDto);
    sessionFactory.getCurrentSession().persist(result);
    return result;
}

public Relation addRelation() {
    return addRelation(StructCreator.createRelationDto(null));
}

public Relation addRelation(long from, long to) {
    return addRelation(StructCreator.createRelationDto(null, from, to));
}
```

2019-04-18 06:22 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/StructCreator.java
> +    public static RelationDto createRelationDto(Integer id, long from, long to) {
Тоже общую часть можно вынести

2019-04-18 06:49 UTC, anickishin requested changes

2019-04-18 06:49 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +    private boolean check(Repository repository, List<Long> ids) {
У тебя неправильно проверка работает. Может заблокировать вполне правильное добавление. Например, есть 4 репозитория и связи между [{2,3}, {2,4}, {3,4}]. Добавить к этому {1,2} не получится.

2019-04-18 07:03 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/rs/RelationResourceTest.java
> +        assertEquals(Response.Status.INTERNAL_SERVER_ERROR.getStatusCode(), response.getStatus());
мы ограничиваем уникальность на уровне базы. 
для того, чтобы выдавать BAD_REQUEST нам нужно либо делать дополнительную проверку кодом, либо ловить все ексепшены от базы и конвертировать их в другие. 
Как-то сомнительные варианты.

2019-04-18 07:19 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +    private boolean check(Repository repository, List<Long> ids) {
ну конечно! 
там же нужно стек мутить и иногда снимать вершину :-)

2019-04-18 11:02 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/rs/RelationResourceTest.java
> +        assertEquals(Response.Status.INTERNAL_SERVER_ERROR.getStatusCode(), response.getStatus());
как бы ни было здоровый сервис не должен отдавать пятисотки

2019-04-18 11:04 UTC, anickishin approved these changes

2019-04-18 11:04 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/rs/RelationResourceTest.java
> +        assertEquals(Response.Status.INTERNAL_SERVER_ERROR.getStatusCode(), response.getStatus());
А чем плохо ловить эксепшены от базы(которые касаются уникальности) и конвертировать их в другие? Насколько я понимаю, 500 ошибок не должно быть вообще.

2019-04-18 11:08 UTC, anickishin requested changes

2019-04-18 11:08 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    @Transactional
Транзакция нужна в addRelation(RelationDto relationDto), а здесь нет

2019-04-18 11:08 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    @Transactional
И тут тоже

2019-04-18 11:08 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/rs/RelationResourceTest.java
> +        assertEquals(Response.Status.INTERNAL_SERVER_ERROR.getStatusCode(), response.getStatus());
А чем плохо ловить эксепшены от базы(которые касаются уникальности) и конвертировать их в другие? Насколько я понимаю, 500 ошибок не должно быть вообще.

2019-04-18 11:15 UTC, colorbash requested changes

2019-04-18 11:15 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +    private boolean check(Repository repository, Deque<Long> ids) {
давай чтоб из названия метода было понятно что ты проверяешь

2019-04-18 11:15 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +                return false;
а можно было 1 исключение кинуть а в private boolean check(Relation relation) { поймать

2019-04-18 11:15 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +    private boolean check(Repository repository, Deque<Long> ids) {
вообще как то сложновато, разве просто обходить в цикле без очереди не работает?
```
check(Repository repository, long firstId) {
     for (Relation relation : relationDao.findRelationsByMainRepositoryId(repository)) {
          if (relation.getRepositoryTo() == firstId) {
               throw new ...
          }
          check(relation.getRepositoryTo(), firstId)
     }
}
```

2019-04-18 11:59 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +    private boolean check(Repository repository, Deque<Long> ids) {
я же циклы ищу, а цикл может быть через 10 репозиториев. 
так что приходится ходить рекурсией и помнить всё, что уже проходил

2019-04-18 13:04 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    @Transactional
не, без них ругается. Пробовал.

2019-04-18 13:35 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/rs/RelationResourceTest.java
> +        assertEquals(Response.Status.INTERNAL_SERVER_ERROR.getStatusCode(), response.getStatus());
там нужно отлавливать DataIntegrityViolationException, то есть более общую ошибку, которая. теоритически должна прилетать в тот момент, когда мы пытаемся создать релейшн между несуществующими репозиториями. 
но там генерится совсем другой ексепшн в мапере, который тоже приводит к 500

2019-04-19 05:23 UTC, SuhoyVasya approved these changes

2019-04-19 09:18 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +    private boolean check(Repository repository, Deque<Long> ids) {
ну так цыкл это когда мы нашли первый (верхний) ид в репах предка, я радве не так написал?

2019-04-19 09:18 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +    private boolean check(Repository repository, Deque<Long> ids) {
и рекурсия у меня есть

2019-04-19 10:56 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RelationResource.java
> +        } catch (DataIntegrityViolationException exeption) {
Я бы в сервисе ловил при обращении к ДАО

2019-04-19 12:55 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RelationResource.java
> +        } catch (DataIntegrityViolationException exeption) {
тут есть 2 нюанса. 
1) оно в сервисе не ловится. никак.
2) по большому счету сервису это и не должно быть интересно. Тут же вопрос формирования правильного HTTP ответа исходя из ответа с других уровней. К тому же впринципе конвертировать ексепшены без необходимости мне кажется неправильным. В ресурсе - другое дело, там уже деваться некуда.

2019-04-19 18:34 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +    private boolean check(Repository repository, Deque<Long> ids) {
да, точно. 
но мы не найдём циклы, если они уже были. 
то есть этот алгоритм будет смотреть не замыкает ли новый цикл вставляемая связь
хотя по большому счету этого должно быть вполне достаточно.
ок, поправлю.

2019-04-19 19:49 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> -        if (relationDto.getRepositoryFromId() != null &&
вот тут хотел бы прокомментировать. 
убираю этот блок т.к. полагаю, что замена полей repositoryTo и repositoryFrom  это уже по сути не изменение а создание другой связи. Так что предлагаю для таких целей убивать старую связь и создавать новую.

2019-04-20 21:06 UTC, alinkov approved these changes

2019-04-20 21:06 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +            throw new IllegalArgumentException("Relation can`t be null");
Можно делать `Objects.requireNonNull(relationDto, "Relation can`t be null")`

2019-04-20 21:06 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +            if (relation
Странная запись в несколько строк.
Лучше сделай отдельную переменную
```java
var repositoryToId = relation.getRepositoryTo().getRepositoryId();
...
```

2019-04-20 21:06 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    @Transactional
Здесь все правильно

2019-04-20 21:06 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    public Relation addRelation(long from, long to) {
так не получится.
Аннотации работают, когда выхов идет через бин. Когда идет через локальные вызовы, они ине работают

2019-04-21 10:41 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +            throw new IllegalArgumentException("Relation can`t be null");
только в этом случае мы получим 500, придётся городить ещё try/catch и получится сложнее :-)

2019-04-21 10:58 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +        long newRepositoryToId = newRelation.getRepositoryTo().getRepositoryId();
тогда немного по другому сделаю.
определю в качестве переменной newRepositoryToId, дабы минимизировать походы в дао.

2019-04-21 10:58 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    public Relation addRelation(long from, long to) {
вообще у меня была идея везде насовать @Transactional чтобы дать возможность дёргать из тестов любой метод. 
ну, если оптимизировать, то ОК, убираю где не надо.

2019-04-21 11:37 UTC, colorbash approved these changes

2019-04-21 11:38 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RelationService.java
> +            throw new IllegalArgumentException("Relation can`t be null");
Ну так null до сервиса и не должен доходить

2019-04-21 15:57 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    public Relation addRelation(long from, long to) {
На данный класс можно вешать целиком аннотацию.
Т.к. этот класс только для тестов, то это вполне нормально

2019-04-21 18:47 UTC, anickishin approved these changes

2019-04-22 06:00 UTC, merged