Front 3 Add relations administration
hhru/hh-dep-monitoring pull request #31
Opened 2019-04-18 10:42 UTC by K-ksenia

Добавлены 
1) добавление, редактирование и удаление связей между репозиториями
2) Snackbars для информирования об ошибках/успешных изменениях
3) Переключатель режима (Пользователь/Админ)
<img width="1440" alt="Снимок экрана 2019-04-18 в 13 33 46" src="https://user-images.githubusercontent.com/18597504/56355566-48e3ca00-61df-11e9-9be1-363e065d4dff.png">
<img width="1440" alt="Снимок экрана 2019-04-18 в 13 34 15" src="https://user-images.githubusercontent.com/18597504/56355570-4c775100-61df-11e9-8f9b-4154f571ff15.png">
<img width="1440" alt="Снимок экрана 2019-04-18 в 13 34 21" src="https://user-images.githubusercontent.com/18597504/56355572-513c0500-61df-11e9-8c07-b9c738fa3d64.png">
<img width="1440" alt="Снимок экрана 2019-04-18 в 13 34 39" src="https://user-images.githubusercontent.com/18597504/56355578-5600b900-61df-11e9-966a-b465bc5bba6b.png">
<img width="1440" alt="Снимок экрана 2019-04-18 в 13 34 43" src="https://user-images.githubusercontent.com/18597504/56355588-5ac56d00-61df-11e9-8aac-02ac8833d6e6.png">
<img width="1440" alt="Снимок экрана 2019-04-18 в 13 34 52" src="https://user-images.githubusercontent.com/18597504/56355591-5f8a2100-61df-11e9-880b-bd12c2f76754.png">
<img width="1440" alt="Снимок экрана 2019-04-18 в 13 35 03" src="https://user-images.githubusercontent.com/18597504/56355600-631da800-61df-11e9-9ded-8c2edb0a755c.png">

2019-04-18 12:48 UTC, gooverdian requested changes
Часть ревью, что-то можно поправить, остальное досмотрю позже

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/CommonComponents/Notifier.js
> +            if (displayed.includes(notification.key)) return;
всегда должны быть фигурные скобки и это правило нарушать нельзя, их отсутствие заставляет пропускать return при чтении кода

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/CommonComponents/Notifier.js
> +            removeSnackbar(notification.key);
диспетч этого экшена вызовет этот эффект и ререндер еще раз, потому что изменится состав notifications, как-то это не очень

в примере, из которого это взято, реализована функция shouldComponentUpdate, которая управляла этим. При переезде в функциональный компонент, функция потерялась и теперь отрисовок будет больше, чем должно быть.

можно попробовать удалять элемент из notifications после скрытия

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/CommonComponents/SelectComponents.js
> +    return <div ref={inputRef} {...props} />;
div, как inputComponent? что-то новенькое, почему тут div?

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/CommonComponents/Notifier.js
> +    state => ({ notifications: state.notifications.messages }),
углубление стейта для нотификаций кажется излишним, почему бы не оставить notifications массивом?
тогда тут будет конструкция вида `({ notifications }) => ({ notifications })` и редьюсер будет выглядеть проще

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/CommonComponents/SelectComponents.js
> +    innerProps: undefined,
это бесполезная строка, непереданный проп итак будет undefined, ниже тоже самое

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/CommonComponents/SelectComponents.js
> +};
Вся эта конструкция, я так понимаю, обязательна для ReactSelect..?

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/Header/AdminModeSwitch.js
> +    label: {
одинокий неиспользуемый всеми забытый и отринутый класс?

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/MainBlock/Repository/DeleteRelationDialog.js
> +import Delete from '@material-ui/icons/Delete';
default импорты можно импортить под любым именем, или добавить as. Для понимания, что это иконка, я бы добавил суффикс Icon здесь и вообще везде

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/MainBlock/Repository/DeleteRelationDialog.js
> +                    <Button onClick={handleSubmit} className={classes.formButton}>
опционально, лучше использовать разные типы кнопок для диаметральных действий, чтоб прям с первого взгляда было понятно, что есть что

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/Header/Header.js
> -                <UserBlock account={{ accountName: 'SuhoyVasya' }} />
Если эти компоненты более не будут использоваться - лучше их удалить физически. Из истории гита всегда можно вернуть, и дерево проекта не будет засорено неиспользуемыми вещами.

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/MainBlock/Repository/DeleteRelationDialog.js
> +function DeleteRelationDialog({ classes, relationId, repositoryId, deleteRelation }) {
я бы назвал компонент DeleteRelationButton. Диалог - это по сути, следствие. И еще, у тебя для каждого релейшена создается свой диалог, это кажется довольно избыточно, опционально, можно попробовать вынести его и создавать один, при клике на кнопку

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/DescriptionInput.js
> +            id="multiline-flexible"
мы вот говорили, что id необязателен, зачем он тут?

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +    const defaultField = (value, label) => ({
это можно унести в валидатор и как-то лучше назвать, раз уж это он диктует такой формат

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +        repositoryFrom: relation ? relation.repositoryFromId : repositoryId,
Можно для большего понимания, как это работает, добавить булево, вроде `const isNewRelation = !(relation)` и проверять его

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +            repository: repositoryTo, priority, description,
зачем в валидатор передавать description?

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +        setDescription(attributes.description);
Зачем эти строки здесь? По идее, последние значения уже в стейте, благодаря onChange

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +                <Button onClick={handleSubmit} className={classes.formButton}>
Тоже самое, лучше использовать разный тип кнопок
https://www.google.com/search?q=submit+cancel&newwindow=1&rlz=1C5CHFA_enRU806RU806&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjWmoLE1dnhAhXMdJoKHfMhCWsQ_AUIDigB&biw=1680&bih=835

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +                ? putRelation(relation.relationId, relation.repositoryFromId, repositoryTo.value,
опционально, можно добавить проверку, что поля менялись, чтобы не грузить бэк одинаковыми запросами

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +    repositoryName: undefined,
как и выше, и для всего, что ниже, если еще есть - undefined можно не указывать, как defaultProp

2019-04-18 12:48 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +)(withStyles(styles)(FormContent));
Дальше пока не смотрел.

2019-04-18 19:11 UTC, gooverdian requested changes
В целом, неплохо, но есть что улучшить

При ре-ревью, возможно всплывут комментарии, которые сейчас не всплыли

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/CommonComponents/SelectComponents.js
> +    return <div ref={inputRef} {...props} />;
разобрались, это он так называется, на самом деле это не сам инпут, а его обертка

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/CommonComponents/SelectComponents.js
> +};
разобрались, да

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/Header/AdminModeSwitch.js
> +                onChange={toggle}
Почему бы не в одну строку?

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +                    To add new relation, please enter following fields.
отступ

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/FormWrapper.js
> +    const [open, setOpen] = useState(false);
неподходящее название для переменной, управляющей диалогом, хотя бы dialogOpen

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/FormWrapper.js
> +            {relation ? <Edit className={classes.deleteRelationIcon} onClick={handleClickOpen} />
теперь это неподходящее название для класса

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/SelectRepository.js
> +        setRepository({
зачем два стейта? можно управлять стейтом сверху, как в приорити

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/SelectRepository.js
> +                isDisabled={Number(repositoryFor) === Number(repository.value)}
учитывая, что он иногда string - лучше преобразовывать в string

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/SelectRepository.js
> +            && <FormHelperText className={classes.errorText}>{repository.error}</FormHelperText>}
Если будет где-то третий раз эти же две строки, то лучше вынести

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/SelectRepository.js
> +            label: selected ? selected.label : '',
по сути, эта строка меняет объект и теперь у него появляется новое свойство, это не очень

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationItem.js
> +        setOpen(relation.repositoryToHasRelations && !open);
нужно пересмотреть все же именование переменных, непонятно

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/MainBlock/Repository/Repository.js
> +        if (formResult === undefined) return;
скобки

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/Utils/Validator.js
> +export default Validator;
ужасный код, сейчас так никто не делает, кто его писал вообще?!

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/Utils/Validator.js
> +
лишняя пустая строка

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/redux/models/Notification/notificationReducer.js
> +export const initialState = {
Вот прям тут массив

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/redux/models/Notification/notificationReducer.js
> +        return {
и тут чуть проще

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/redux/models/Relation/relationsSelectors.js
> +            label: item.substring(0, 1) + item.substring(1).toLowerCase(),
?
для капитализации можно использовать стили (https://css-tricks.com/almanac/properties/t/text-transform/)

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/Utils/Validator.js
> +        return CoreValidators[rule](value);
`return CoreValidators[rule] ? CoreValidators[rule](value) : false;`

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/MainBlock/Repository/Repository.js
> +            enqueueSnackbar(`Relation was successfully ${formResult.action}`, 'success');
учитывая вызовы enqueueSnackar из разных компонентов - наличие Notifier под вопросом

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/Utils/Validator.js
> +        const ruleSet = rules[name];
rules[name].map

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/redux/models/Notification/notificationActions.js
> +export const noticeMessage = (message, variant) => ({
можно перенести эту логику в addMessage, не могу придумать ситуации, когда нужна эта функция, и не нужна та

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/redux/models/Relation/relationsActions.js
> +export function resetFormSubmit() {
давай, просто resetFormResult, и экшен такой же (RESET_FORM_RESULT), вообще хороший тон повторять имена экшенов именами функций, а то у тебя каша какая-то: resetFormSubmit -> clearSubmitted -> RESET_SUBMITTED -> formResult

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/redux/models/Relation/relationsActions.js
> +export function resetFormSubmit() {
ну и вместо addFormProcessingResult тоже можно setFormResult

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/redux/models/Relation/relationsActions.js
> +export function resetFormSubmit() {
в итоге, я посмотрел этот файл и следующий, и предлагаю почти все переименовать

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/redux/models/Relation/relationsReducer.js
> +        return {
```
const newState = Object.assign({}, state);
newState.relationsByRepoId[repositoryId][newRelation.priority] = [].concat(
    newState.relationsByRepoId[repositoryId][newRelation.priority] || [], newRelation
);
return newState;
```
над остальными тоже можно в таком духе подумать

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/redux/models/Relation/relationsSelectors.js
> +export function getRelationsByRepoId(store, repositoryId) {
функции, имеющие BySomething в названии, последнее время довольно бессмысленны, если у тебя реально нет нескольких функций, которые возвращают одни и те же данные по разному набору параметров, или если ты используешь для кодинга блокнот, который не подсвечивает параметры

это опционально, там уже есть вне этого ПР такие функции и да, их тоже можно переименовать, если будет большое желание, просто до этого я как-то не обратил внимание

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/redux/models/Relation/relationsActions.js
> +            .catch(() => {
тут и ниже, кажется, можно обойтись одной строкой, даже если диспетч что-то возвращает, сломаться не должно

2019-04-18 19:11 UTC, gooverdian commented on frontend/src/redux/models/Repository/repositoriesSelectors.js
> +export const getAllRepos = store => store.repositories.list.items;
не вижу использований этой функции, и, кажется, ее результат тоже надо мапить

2019-04-19 22:28 UTC, K-ksenia reviewed
Опциональные замечания меняла не все, 
над ререндером notifications пока думаю,
defaultField в FormContent пока не выносила

Скриншот для демонстрации кнопки Submit 
<img width="581" alt="Снимок экрана 2019-04-20 в 1 32 42" src="https://user-images.githubusercontent.com/18597504/56446597-3fa44b80-630c-11e9-8e35-7e11332380fd.png">

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/CommonComponents/Notifier.js
> +            if (displayed.includes(notification.key)) return;
Добавила

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/CommonComponents/Notifier.js
> +    state => ({ notifications: state.notifications.messages }),
Исправила

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/CommonComponents/SelectComponents.js
> +};
Да, чтобы отображалось в стиле material-ui

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/Header/AdminModeSwitch.js
> +    label: {
упс

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/redux/models/Notification/notificationReducer.js
> +export const initialState = {
Угу, сделала

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +                    To add new relation, please enter following fields.
поправила

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +            repository: repositoryTo, priority, description,
видимо я посчитала это за универсальность🤷‍♀️
Мало ли какие правила добавятся, чтобы тут уже все готовенькое было
Но ты прав, незачем, так что убрала

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +        repositoryFrom: relation ? relation.repositoryFromId : repositoryId,
Сделано

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/DescriptionInput.js
> +            id="multiline-flexible"
затерялся
убрала

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/Header/AdminModeSwitch.js
> +                onChange={toggle}
Согласна

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +        setDescription(attributes.description);
Остальное эволюционировало, а про них забыла
Убираю, спасибо

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/Header/Header.js
> -                <UserBlock account={{ accountName: 'SuhoyVasya' }} />
Окей, удалила

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/Repository.js
> +            enqueueSnackbar(`Relation was successfully ${formResult.action}`, 'success');
тут enqueueSnackbar тот, что диспатчит экшн добавления нотификашки в стор
а в Notifier enqueueSnackbar штатный библиотечный, который становится просом, если компонент экспортируется с withSnackbar
Мб неправильно называть их одним именем. Опять таки брала из примера в доке

Если убрать Notifier, то придется навесить withSnackbar на кого-то еще. А зачем? Если можно его отдельненько обработать

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +        setDescription(attributes.description);
А нет, это нужно для того, чтобы error прокидывался

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +                <Button onClick={handleSubmit} className={classes.formButton}>
Спасибо, сделала

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/CommonComponents/SelectComponents.js
> +    innerProps: undefined,
Отключила правило react/require-default-props в ESLint и убрала все undefined в defaultProps

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/DeleteRelationDialog.js
> +import Delete from '@material-ui/icons/Delete';
Сделано

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/DeleteRelationDialog.js
> +function DeleteRelationDialog({ classes, relationId, repositoryId, deleteRelation }) {
в DeleteRelationButton переименовала, 
диалог вынесла, по идее теперь будет один создаваться

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/FormWrapper.js
> +    const [open, setOpen] = useState(false);
Переименовала

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/FormWrapper.js
> +            {relation ? <Edit className={classes.deleteRelationIcon} onClick={handleClickOpen} />
Угу
Переименовала в relationControlIcon

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/SelectRepository.js
> +        setRepository({
ой, да, спасибо

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/SelectRepository.js
> +            label: selected ? selected.label : '',
Почему новое?  В FormContent мы репозитории объявляем с label

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/SelectRepository.js
> +            && <FormHelperText className={classes.errorText}>{repository.error}</FormHelperText>}
Спасибо, учту

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/redux/models/Relation/relationsActions.js
> +            .catch(() => {
Сделала

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/redux/models/Relation/relationsActions.js
> +export function resetFormSubmit() {
Переименовала

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/redux/models/Relation/relationsSelectors.js
> +export function getRelationsByRepoId(store, repositoryId) {
сделала просто getRelations и getRelation
и в редьюсере убрала BySomething

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/Utils/Validator.js
> +        return CoreValidators[rule](value);
👌

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/Utils/Validator.js
> +        const ruleSet = rules[name];
👌👌

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/SelectRepository.js
> +                isDisabled={Number(repositoryFor) === Number(repository.value)}
Переделала

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/Utils/Validator.js
> +        const ruleSet = rules[name];
forEach, наверное, больше подойдет

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/redux/models/Notification/notificationActions.js
> +export const noticeMessage = (message, variant) => ({
Перенесла

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/redux/models/Repository/repositoriesSelectors.js
> +export const getAllRepos = store => store.repositories.list.items;
Вставила использование в Repositories.js

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/Repository.js
> +            enqueueSnackbar(`Relation was successfully ${formResult.action}`, 'success');
Переименовала enqueueSnackbar, который диспатчит экшн

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationItem.js
> +        setOpen(relation.repositoryToHasRelations && !open);
Если есть идеи, с удовольствием выслушаем
Ребята уже 2 раза переименовывали

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +    const defaultField = (value, label) => ({
Пока не придумала, как можно в валидатор унести

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/redux/models/Relation/relationsReducer.js
> +        }
Вот эта конструкция мне не нравится, так как если находится элемент, то пробегаюсь по массиву второй раз, чтобы положить результат в relation
Но что-то не могу сообразить, как за один пробег все сделать

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/redux/models/Relation/relationsReducer.js
> +        return {
Огонь! А то от этой многоступенчатости голова начинала болеть

2019-04-19 22:28 UTC, K-ksenia commented on frontend/src/redux/models/Relation/relationsSelectors.js
> +            label: item.substring(0, 1) + item.substring(1).toLowerCase(),
Не могу разобраться со стилями на < MenuItem >
никакие не действуют почему-то

Сделала немного более читаемый вариант

2019-04-20 07:50 UTC, K-ksenia commented
Унесла кнопку добавления связи вправо. Так гармоничнее, кажется
И задала фиксированную высоту этому блоку (Relations + кнопка), чтобы при переходе в режим админа ничего не скакало
<img width="843" alt="Снимок экрана 2019-04-20 в 10 43 51" src="https://user-images.githubusercontent.com/18597504/56454484-c03d6900-6359-11e9-873c-b2878ce160f6.png">

2019-04-20 14:35 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +    const defaultField = (value, label) => ({
как просто еще одну экспортируемую функцию, которая будет отсюда вызываться, я имел в виду

2019-04-20 17:30 UTC, gooverdian requested changes

2019-04-20 17:30 UTC, gooverdian commented on frontend/src/CommonComponents/Notifier.js
> +            setDisplayed([...displayed, notification.key]);
этот массив никогда не очищается, потенциальная дыра в памяти

2019-04-20 17:30 UTC, gooverdian commented on frontend/src/MainBlock/Repository/DeleteRelation/DeleteRelationDialog.js
> +                <Button onClick={handleClose} className={classes.formButton}>
у Button в material-ui есть проп variant, может, воспользоваться им?
https://material-ui.com/demos/buttons/

2019-04-20 17:30 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +            repository: repositoryTo, priority,
а почему не проверяется repositoryFrom?

2019-04-20 17:30 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +        setRepositoryTo({
я бы унес сеттеры в else блок условия про valid

2019-04-20 17:30 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/FormWrapper.js
> +                <DialogTitle>
если вот это вот все присутствует в html, пока диалог закрыт - надо повесить сюда условие, например dialogOpen, потому что для каждого релейшена все равно будет создано по форме.

Вообще - форма должна быть одна, ты же все равно туда все, что ей нужно передаешь. Ну и она в модальном диалоге, две одновременно все равно не увидеть. Если охота заморочиться - ее можно вынести так, чтобы она была вне всех списков и вызывалась диспетчем экшена

2019-04-20 17:30 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationItem.js
> +import EditRelationButton from './RelationForm/FormWrapper';
лучше все же прям настолько разительно не менять название, или поменять название самого компонента тогда

2019-04-20 17:30 UTC, gooverdian commented on frontend/src/Utils/Validator.js
> +    validate(rule, value) {
вот сюда добавить 
```
generateAttribute(value, rest = {}) {
    return {
        ...rest
        value,
        error: undefined,
    }
},
```

и в форме вызывать `Validator.generateAttribute(values.repositoryFrom, {label: labels.repositoryFrom});`

2019-04-20 17:30 UTC, gooverdian commented on frontend/src/redux/models/Relation/relationsReducer.js
> +        }
да, непорядок. Можно как-то так:
```
    let relation;
    relations && Object.keys(relations).forEach((priority) => {
        relation = relations[priority].find(item => item.relationId === relationId);
    }
    return relation || {};
```

2019-04-20 17:30 UTC, gooverdian commented on frontend/src/redux/models/Relation/relationsReducer.js
> +    [RESET_FORM_RESULT]: state => ({
я что-то посмотрел еще раз на форму, и не понял, зачем этот экшен вызывается при ошибке?

2019-04-20 17:30 UTC, gooverdian commented on frontend/src/redux/models/Relation/relationsReducer.js
> +const getRelationById = (relations, relationId) => {
все еще ById

2019-04-20 17:30 UTC, gooverdian commented on frontend/src/redux/models/Relation/relationsSelectors.js
> +            label: item[0] + item.slice(1).toLowerCase(),
Да, там flex, в котором текст лежит, по идее, вот такой класс прокатит, но может сломаться верстка:
```
    capitalize: {
      display: 'block',
      textTransform: 'lowercase',
      '&:first-letter': {
        textTransform: 'uppercase'
      }
    }
```

2019-04-20 19:33 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +    const defaultField = (value, label) => ({
Ок, сделала

2019-04-20 19:33 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +        setRepositoryTo({
да, логично, value ведь не меняется

2019-04-20 23:22 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
> +            repository: repositoryTo, priority,
обсудили

2019-04-20 23:22 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationItem.js
> +import EditRelationButton from './RelationForm/FormWrapper';
переименовала FormWrapper в OpenFormButton

2019-04-20 23:22 UTC, K-ksenia commented on frontend/src/Utils/Validator.js
> +    validate(rule, value) {
Спасибо! Сделала так

2019-04-20 23:22 UTC, K-ksenia commented on frontend/src/redux/models/Relation/relationsReducer.js
> +const getRelationById = (relations, relationId) => {
убрала
relationsByRepoId в state оставляю, ведь? Так как это не метод, а подсказка как отсортированы связи (аналогично repositoryById в repositoriesReducer)

2019-04-20 23:22 UTC, K-ksenia commented on frontend/src/redux/models/Relation/relationsReducer.js
> +    [RESET_FORM_RESULT]: state => ({
Если у нас есть что-то в formResult, то это что-то отображается пользователю в виде Snackbar (проверка и диспатч экшена добавления нотификашки происходит в Repository/Repository.js), а затем мы очищаем это поле, иначе данный Snackbar будет генерироваться и всплывать каждый раз при рендере этого компонента

2019-04-20 23:22 UTC, K-ksenia commented on frontend/src/redux/models/Relation/relationsSelectors.js
> +            label: item[0] + item.slice(1).toLowerCase(),
Если делать span, то без `display: 'block',` поле отображается с маленькой буквы
Так что display оставила

2019-04-20 23:22 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/FormWrapper.js
> +                <DialogTitle>
В html не присутствует, оставила, как есть

2019-04-20 23:22 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/DeleteRelation/DeleteRelationDialog.js
> +                <Button onClick={handleClose} className={classes.formButton}>
Сделала

2019-04-20 23:22 UTC, K-ksenia commented on frontend/src/redux/models/Relation/relationsReducer.js
> +        }
разрулили

2019-04-21 10:18 UTC, alinkov commented on frontend/src/redux/models/Repository/repositoriesActions.js
> +                dispatch(addMessage('Something went wrong', 'error'));
лучше писать какое-то более понятное сообщение.
`Error in fetching repositories`
чтобы было понятно при каком действии ошибка. А то получится, что вроде сайт работает, но что-то идет не так и не понятно что

2019-04-21 10:18 UTC, alinkov commented on frontend/src/CommonComponents/SelectComponents.js
> +                fontWeight: isSelected ? 500 : 400,
может в какие-то константы эти 500 и 400 ?

2019-04-21 10:18 UTC, alinkov commented on frontend/src/Header/AdminModeSwitch.js
> +    const toggle = () => {
может хотя бы `toggleMode` ?

2019-04-21 10:18 UTC, alinkov commented on frontend/src/MainBlock/Repository/Repository.js
> +            addMessage('Something went wrong', 'error');
тоже сделай сообщение чуть попонятнее

2019-04-21 10:18 UTC, alinkov commented on frontend/src/MainBlock/Repository/Repository.js
> +        if (formResult === undefined) {
может лучше 
```suggestion
        if (!formResult) {
```

2019-04-21 10:18 UTC, alinkov commented on frontend/src/Utils/Validator.js
> +        return !(
не тоже самое что
```javascript
!value || !(value === '0' || (value.length && value.length === 0))
```

2019-04-21 10:18 UTC, alinkov commented on frontend/src/Utils/constants.js
> +export const BASE_URL = 'http://localhost:8080/';
@gooverdian а можно как-то сделать prod constants и dev constants ?

2019-04-21 10:18 UTC, alinkov commented on frontend/src/redux/models/Notification/notificationsActions.js
> +            key: new Date().getTime() + Math.random(),
```suggestion
            key: Math.random().toString(36).substring(2),
```
можно так генерить

2019-04-21 12:30 UTC, gooverdian commented on frontend/src/Utils/Validator.js
> +        return !(
a(''); => false
b(''); => true

2019-04-21 15:24 UTC, gooverdian commented on frontend/src/Header/AdminModeSwitch.js
> +    const toggle = () => {
весь компонент про это, в нем больше нет переменных, я бы не стал

2019-04-21 15:25 UTC, gooverdian commented on frontend/src/Utils/constants.js
> +export const BASE_URL = 'http://localhost:8080/';
да, можно сделать условные константы, я попробую найти пример

2019-04-21 15:33 UTC, gooverdian commented on frontend/src/Utils/constants.js
> +export const BASE_URL = 'http://localhost:8080/';
Например, у нас подтягивался разный конфиг для стора, но тоже можно адаптировать, если нужно
https://github.com/gooverdian/employer-review/blob/master/frontend/src/store/configureStore.js

2019-04-21 17:12 UTC, K-ksenia commented on frontend/src/redux/models/Notification/notificationsActions.js
> +            key: new Date().getTime() + Math.random(),
брала генерацию из документации notistack
можно и как ты предложил, но зачем?

2019-04-21 17:12 UTC, K-ksenia commented on frontend/src/CommonComponents/SelectComponents.js
> +                fontWeight: isSelected ? 500 : 400,
В принципе, это можно убрать вообще

2019-04-21 17:12 UTC, K-ksenia commented on frontend/src/CommonComponents/Notifier.js
> +            setDisplayed([...displayed, notification.key]);
решили

2019-04-21 17:12 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/Repository.js
> +        if (formResult === undefined) {
Оки, исправила

2019-04-21 17:12 UTC, K-ksenia commented on frontend/src/redux/models/Repository/repositoriesActions.js
> +                dispatch(addMessage('Something went wrong', 'error'));
Спасибо, исправила

2019-04-21 17:12 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/Repository.js
> +            addMessage('Something went wrong', 'error');
а я не знаю что еще тут добавить
Error in edition/creation relation?
или же 
Error in submitting the form
Но если открыта форма, ты нажимаешь Submit и вылетает ошибка (при этом форма не закрывается)
и так понятно что ошибка в отправке формы.
Максимум что можно сделать для понятности, выдавать разные сообщения в зависимости от кода ошибки

2019-04-21 20:50 UTC, gooverdian approved these changes
Вполне приемлемо, но над последним комментарием, пожалуйста, подумай.

И еще над неймингом, но это больше к вопросам договоренностей в команде - repositoryFrom и repositoryTo - весьма сложные для понимания и восприятия названия, от этого страдает читаемость(мое предложение мы обсуждали в слаке - это source и target).

2019-04-21 20:50 UTC, gooverdian commented on frontend/src/MainBlock/Repository/DeleteRelation/DeleteRelationDialog.js
> +    deleteRelation }) {
а у нас линия-ограничитель на 120 символов, а не на 100 =)

2019-04-21 20:50 UTC, gooverdian commented on frontend/src/redux/models/Relation/relationsReducer.js
> +    [RESET_FORM_RESULT]: state => ({
Да вроде у тебя там стоит зависимость от formResult в хуке, не должно бы оно создавать новые снэкбары, потому как эффект не вызывается

2019-04-22 07:48 UTC, alinkov approved these changes

2019-04-22 12:56 UTC, K-ksenia commented on frontend/src/redux/models/Relation/relationsReducer.js
> +    [RESET_FORM_RESULT]: state => ({
Проверила, когда перехожу между /Repositories/:repositoryId1 и /Repositories/:repositoryId2, то не вызывается, да
А когда со страницы /Repositories на страницу /Repositories/:repositoryId, то вызывается

2019-04-22 14:45 UTC, SuhoyVasya approved these changes

2019-04-22 15:02 UTC, merged