back-28 Get data about maven dependency
hhru/hh-dep-monitoring pull request #32
Opened 2019-04-22 06:10 UTC by anickishin

2019-04-22 07:41 UTC, alinkov requested changes

2019-04-22 07:41 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/BambooLoader.java
> +public class BambooLoader {
Давай-ка назовём dependency loader или как-то так

2019-04-22 07:41 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +        Optional<String> oauthOptional = Optional.ofNullable(System.getProperty("github.oauth"));
Вынеси в метод

2019-04-22 07:41 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/ArtifactVersionDao.java
> +    public ArtifactVersion findArtifactByArtifactAndVersion(Artifact artifact, String version) {
только тут не `findArtifact`, а хотя бы `findVersion`
а то название не соответствует реальности

2019-04-22 07:41 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/config/TestConfig.java
> +        when(bambooLoader.getDataFromBamboo()).thenReturn(null);
лучше не `null`, а хоть пустую сущность

2019-04-22 07:41 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/bamboo/BambooArtifactDto.java
> +    public static final class BambooArtifactDtoBuilder {
а зачем тут билдер?
ведь у тебя эта сущность будет приходить и создавать ее не надо

2019-04-22 07:41 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/config/TestConfig.java
> +        when(bambooLoader.getDataFromBamboo()).thenReturn(null);
А лучше, чтобы он парсил реальный json, который я скидывал

2019-04-22 07:41 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/ArtifactVersion.java
> +        String[] versionArray = version.split("\\.", 4);
а что будет с такими версиями `5.1.6.RELEASE` ?
Это из спринга. Думаю, что лучше matcher заиспользовать
И на этот метод нужно обязательно тест написать.
Так что тут ему не место

2019-04-22 07:41 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/SyncService.java
> +                artifact = new Artifact();
сделай конструктор из 3 параметров

2019-04-22 07:41 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/SyncService.java
> +                artifactVersion = new ArtifactVersion();
тоже сделай конструктор для этой цели

2019-04-22 07:41 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/SyncService.java
> +    private void saveBambooDate(List<BambooArtifactDto> artifactDtoList, Repository parentRepository) {
логику нужно отсюда вытащить

2019-04-23 08:36 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +    private String getProperty(FileSettings fileSettings, String property) {
только приватные методы лучше в конец переносить, чтобы они с бинами не путались

2019-04-23 09:19 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/ArtifactVersion.java
> +        String[] versionArray = version.split("\\.", 4);
А в чём проблема c `5.1.6.RELEASE`? Разобьёт на `{"versionMajor": 5, "versionMinor": 1, "versionMicro": 6 и "version": "5.1.6.RELEASE"}`

2019-04-23 09:57 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/ArtifactVersion.java
> +        String[] versionArray = version.split("\\.", 4);
А если 5.1.RELEASE или что-нибудь такое?
Я тебе про то, что `Integer.parseInt` может выдать исключение. Поэтому лучше matcher

2019-04-24 05:43 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/config/TestConfig.java
> +        when(bambooLoader.getDataFromBamboo()).thenReturn(null);
я об этом думал, но решил, что с тестами (а соответственно с этим) позже разберусь

2019-04-25 17:21 UTC, alinkov requested changes

2019-04-25 17:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/ArtifactVersionDao.java
> +    public ArtifactVersion findByArtifactAndVersion(Artifact artifact, String version) {
сделай Optional<ArtifactVersion>

2019-04-25 17:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/DependencyDao.java
> +    public Dependency findByRepositoryAndArtifactVersion(Repository repository, ArtifactVersion artifactVersion) {
и тут Optional

2019-04-25 17:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryDaoImpl.java
> +    public Repository findRepositoryByName(String repositoryName) {
Тут тоже лучше Optional

2019-04-25 17:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/ArtifactVersion.java
> +    public ArtifactVersion(Artifact artifact, List<Integer> versionList, String version) {
давай лучше прям версии задавай. Можешь для этого отдельную сущность сделать

2019-04-25 17:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +                throw new IllegalArgumentException("Can't parse bamboo key to artifact name, group name and version (" +
как-то странно разнес

2019-04-25 17:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +                throw new IllegalArgumentException("Can't parse bamboo key to artifact name, group name and version (" +
И не стоит ошибку тут кидать, лучше пиши в лог. А то потом будет падать обновление из-за какого-нибудь одного сбоя

2019-04-25 17:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/StringUtils.java
> +public class StringUtils {
используй лучше org.apache.commons.lang3.StringUtils#isNumeric

2019-04-25 17:37 UTC, colorbash requested changes

2019-04-25 17:37 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/ArtifactVersion.java
> +        if (versionList.size() > 0) {
как-то не красиво(
давай свитч кейс или еще чего-нибудь?)

2019-04-25 17:37 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/ArtifactVersion.java
> +        if (versionList.size() > 0) {
```java
switch(versionList.size()) {
case 3:
  this.versionMicro = versionList.get(2);
case 2:
  this.versionMinor = versionList.get(1);
case 1:
  this.versionMajor = versionList.get(0);
  break;
}
```
Красота!)

2019-04-25 17:37 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +    private void saveBambooDate(List<BambooArtifactDto> artifactDtoList, Repository parentRepository) {
метод выглядит перегруженным, надо делить его

2019-04-25 17:37 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/StringUtils.java
> +    public static boolean isNumeric(String string) {
велосипеды это зло)
можно так
```java
public static boolean isNumeric(String strNum) {
    try {
        double d = Double.parseDouble(strNum);
    } catch (NumberFormatException | NullPointerException nfe) {
        return false;
    }
    return true;
}
```
а еще лучше погуглить где нибудь уже это написано.

2019-04-25 17:45 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +            if (keyList.length != 3) {
нужен класс который будет описывать версию! так оч плохо понятно что ты куда суешь по индексам
у класса можно сделать конструктор из строки и пустьтам парсим строку

2019-04-26 06:25 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +                throw new IllegalArgumentException("Can't parse bamboo key to artifact name, group name and version (" +
А как тут правильно было разнести?

2019-04-26 08:57 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +                artifactVersion = artifactVersionDao.findByArtifactAndVersion(artifact, keyList[2]);
еслы мы создаем артифакт только что у него нет версии?

2019-04-26 10:41 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +                artifactVersion = artifactVersionDao.findByArtifactAndVersion(artifact, keyList[2]);
Есть. Ниже создаётся. 104 строка.

2019-04-26 11:00 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +                List<Integer> versionList = getVersionList(version);
давай сделаем отдельную функцию получения ArtifactVersion из getVersionList(version); а не тут в коде это писать

2019-04-26 11:56 UTC, alinkov requested changes

2019-04-26 11:56 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +                log.error("Can't parse bamboo key to artifact name, group name and version (" + bambooArtifactDto.getKey() + ")");
Логирование лучше не конкатенацией делать
```suggestion
                log.error("Can't parse bamboo key to artifact name, group name and version ({})", bambooArtifactDto.getKey());
```

2019-04-26 11:56 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +            Repository repository = repositoryDao.findRepositoryByName(bambooArtifactDto.getRepoName()).orElse(null);
```suggestion
            Repository repository = repositoryDao.findRepositoryByName(bambooArtifactDto.getRepoName()).orElse(parentRepository);
```

2019-04-26 11:56 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +                log.error("Can't parse bamboo key to artifact name, group name and version (".concat(bambooArtifactDto.getKey()).concat(")"));
```suggestion
                log.error("Can't parse bamboo key to artifact name, group name and version ({})", bambooArtifactDto.getKey());
```

2019-04-26 11:56 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +                if (parentRepository != null) {
не совсем понятно зачем эта проверка

2019-04-26 11:56 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +    private void saveBambooDate(List<BambooArtifactDto> artifactDtoList, Repository parentRepository) {
метод точно нужно будет делать. И лучше вообще переименовать

2019-04-29 08:47 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +            Repository repositoryOfArtifact = repositoryOptional.orElse(null);
лучше `orElseThrow`, можно даже без параметров

2019-04-29 08:47 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +            Optional<Repository> repositoryOptional = repositoryDao.findRepositoryByName(bambooArtifactDto.getRepoName());
тут стоит искать только в том случае, если это имя есть

2019-04-29 08:47 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/SyncService.java
> +    @Scheduled(initialDelay = 2*60*1000L, fixedDelay = 15*60*1000L)
добавь все-таки пробелы
```suggestion
    @Scheduled(initialDelay = 2 * 60 * 1000L, fixedDelay = 15 * 60 * 1000L)
```

2019-04-29 08:47 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/SyncService.java
> +    @Transactional
можно перенести в `saveBambooData`

2019-04-29 08:47 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +            Optional<Dependency> dependencyOptional = artifactVersionOptional.isPresent() ?
зачем так?
```java
if (parentRepository != null && (artifactVersionOptional.isEmpty() || dependencyDao.findByRepositoryAndArtifactVersion(parentRepository, artifactVersion).isEmpty())) {
                Dependency dependency = new Dependency(parentRepository, artifactVersion);
                dependencyDao.create(dependency);
}
```
Просто зачем делать такую вложенность, если тут одна проверка

2019-04-29 08:47 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +    public void saveBambooData() {
название все-таки лучше другое сделать. Не очень хорошо `Bamboo` в названии

2019-05-06 07:15 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoader.java
> +    public void saveBambooData() {
название все-таки лучше другое сделать. Не очень хорошо `Bamboo` в названии

2019-05-06 07:15 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/ProdConfig.java
> -        DependencyLoader.class,
это можно было не менять, т.к. тест не интеграционный

2019-05-06 07:15 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoaderTest.java
> +        dependencyLoader.saveDependencyData(bambooArtifactDtoList, null);
и что тест проверяет?

2019-05-06 07:15 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/service/loaders/DependencyLoaderTest.java
> +        DependencyLoader dependencyLoader = new DependencyLoader("dependencies.json", repositoryDao, artifactDao, artifactVersionDao, dependencyDao);
```java
RepositoryDao repositoryDao = mock(RepositoryDao.class);
        ArtifactDao artifactDao = mock(ArtifactDao.class);
        ArtifactVersionDao artifactVersionDao = mock(ArtifactVersionDao.class);
        DependencyDao dependencyDao = mock(DependencyDao.class);
        DependencyLoader dependencyLoader = new DependencyLoader("dependencies.json", repositoryDao, artifactDao, artifactVersionDao, dependencyDao);
```
можно вынести в `@Before`

2019-05-12 09:48 UTC, alinkov approved these changes
Разрули конфликты, доделай тесты и забираем

2019-05-14 17:14 UTC, colorbash approved these changes

2019-05-15 11:34 UTC, merged