Front 16 правки по дизайну
hhru/hh-dep-monitoring pull request #35
Opened 2019-04-26 19:57 UTC by Afftobus

не судите строго, не кидайте помидорами, это мой первый ПР по фронту.

2019-04-27 14:21 UTC, K-ksenia requested changes
Что-то мне кажется, что теперь, когда все красное, как-то агрессивно выглядит, нет?

2019-04-27 14:21 UTC, K-ksenia commented on frontend/src/App.js
> +import MasterTheme from './MaterialTheme';
этот импорт, наверное, лучше вместе с нижними писать, так как он не от @material-ui/

2019-04-27 14:21 UTC, K-ksenia commented on frontend/src/Header/MainIcon.js
> +        backgroundColor: fade(theme.palette.common.white, 1),
можно просто '#fff', раз прозрачность не добавляешь

2019-04-27 14:21 UTC, K-ksenia commented on frontend/src/Header/MainIcon.js
> +        color: '#d6001c',
а тут не mainThemeColor (из commonStyles.js) должен быть?

2019-04-27 14:21 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/RepositoryItem.js
> +                    <ListItemInfo descr={repository.description === null ? '' : repository.description} date={repository.updatedAt} />}
ESLint не ругался на длину?

2019-04-28 06:31 UTC, SuhoyVasya approved these changes

2019-04-28 08:26 UTC, Afftobus commented on frontend/src/Header/MainIcon.js
> +        backgroundColor: fade(theme.palette.common.white, 1),
ок, тогда и fade пришлось убрать из импортов

2019-04-28 08:26 UTC, Afftobus commented on frontend/src/Header/MainIcon.js
> +        color: '#d6001c',
сделал ссылкой на цвет

2019-04-28 08:26 UTC, Afftobus commented on frontend/src/MainBlock/Repositories/RepositoryItem.js
> +                    <ListItemInfo descr={repository.description === null ? '' : repository.description} date={repository.updatedAt} />}
вроде как ограничение 150 символов, а у меня 136

2019-04-28 11:38 UTC, leonidfeskov commented
Общее замечание по оформлению ПР.
В описании ПР надо кратко описать что было сделано.
Если это какие-то изменения в дизайне, то лучше приложить 2 скриншота: ДО и ПОСЛЕ.
Так ревьюеру будет легче и быстрее вникнуть в код.

2019-04-29 10:40 UTC, K-ksenia approved these changes
У нас максимальная длина 120 символов, хотя и ESLint не ругается почему-то, я бы поправила
Остальное ок

2019-04-29 19:52 UTC, merged