Back 23
hhru/hh-dep-monitoring pull request #37
Opened 2019-04-28 13:57 UTC by SuhoyVasya

Фильтрация репозиториев по имени

2019-04-28 18:55 UTC, alinkov requested changes
Так вроде ничего, но тестов нужно сделать

2019-04-28 18:55 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryDaoImpl.java
> +        String searchString = pageRequestDto.getSearchString() + "%";
наверное тут лучше сделать `%` с двух сторон

2019-04-29 06:20 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryDaoImpl.java
> +        String searchString = pageRequestDto.getSearchString() + "%";
Не стоит ли searchString заполнять отдельной private функцией? Чтобы менять в одном месте

2019-04-29 06:20 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        int found = repositoryDao.count(pageRequestDto);
Может вместо `PageDto.PageDtoBuilder<RepositoryDto> builder = PageDto.builder();` и `return builder.withFound(found)` сделаешь `return PageDto.builder().withItems(repositoryDtos).withFound(found)`. Мне кажется, что так будет легче смотреться.

2019-04-29 06:42 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/RepositoryService.java
> +        int found = repositoryDao.count(pageRequestDto);
Легче смотреться не будет потомучто компилятор хочет чтобы там появились <> от дженериков. 
Я оставил как есть и немного переставил строки

2019-04-29 06:42 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryDaoImpl.java
> +        String searchString = stringToRegExp(pageRequestDto.getSearchString());
Вынес в отдельную функцию

2019-04-29 07:36 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    protected static String stringToRegExp(String str) {
название не совсем правильное
тут просто регулярки вообще нет
И стоит на null проверять

тут что-нибудь вроде `getContainsString`

2019-04-29 07:36 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryDaoImpl.java
> +                .createQuery("from " + Repository.class.getName() + " where name like :searchString order by name " + orderString, Repository.class)
тут кстати стоит искать ignore case

2019-04-29 07:48 UTC, colorbash requested changes

2019-04-29 07:48 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        return "%" + str + "%";
String.format()

2019-04-29 07:48 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryDaoImpl.java
> +                .uniqueResult().intValue();
.intValue(); на след строчку

2019-04-29 07:48 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +    @DefaultValue("100")
кажется DefaultValue на ресурсе достаточно? зачем дублировать в дто

2019-04-29 07:48 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/StructCreator.java
> +        repositoryDto.setName("Name" + String.format("%02d", id));
можт все в String.format( запихнем

2019-04-29 08:45 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    protected static String stringToRegExp(String str) {
поменял название и сделал проверки

2019-04-29 08:45 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        return "%" + str + "%";
переделал через формат

2019-04-29 08:45 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryDaoImpl.java
> +                .uniqueResult().intValue();
перенес

2019-04-29 08:45 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +    @DefaultValue("100")
убрал

2019-04-29 08:45 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/StructCreator.java
> +        repositoryDto.setName("Name" + String.format("%02d", id));
чет тупанул) переделал.

2019-04-29 10:53 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        return String.format("%%%s%%", str);
тут кажется нужно экранировать, работать не должно сейчас

2019-04-29 11:19 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        return String.format("%%%s%%", str);
%% это и есть экранирование

2019-04-29 12:14 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        return String.format("%%%s%%", str);
есмли работает - апрув, надеюсь ты тестил
я думал / над

2019-04-29 12:15 UTC, colorbash approved these changes

2019-04-29 12:15 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        return String.format("%%%s%%", str);
и почему с одной сторонв 3 а с другой 2 %

2019-04-29 12:23 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        return String.format("%%%s%%", str);
там получается так %%->%  %s->str  
два первых процента после формата переводятся в символ процента.
%s - вместо него подставляется аргумент
ну и после - аналагично первому случаю

2019-04-29 12:33 UTC, alinkov approved these changes

2019-04-29 12:33 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        return String.format("%%%s%%", str);
формат выглядит ужасно...

2019-05-04 08:42 UTC, merged