back-1 Database creation
hhru/hh-dep-monitoring pull request #4
Opened 2019-03-01 11:42 UTC by K-ksenia

2019-03-01 12:19 UTC, alinkov requested changes
Добавь символы переноса и отформатируй поля, чтобы отступы были одинаковыми

2019-03-01 12:40 UTC, alinkov requested changes

2019-03-01 12:40 UTC, alinkov commented on hh-dep-monitoring-service/src/main/resources/scripts/create_account.sql
> +    login varchar(110) NOT NULL,
используй одинаковый формат.
Либо все ключевые SQL функции большими, либо маленькими.
Но не так, чтобы в одном месте был один формат, а в другом другой

2019-03-01 12:40 UTC, alinkov commented on hh-dep-monitoring-service/src/main/resources/scripts/create_account.sql
> +    login varchar(110) NOT NULL,
и обсудите, какие поля действительно нужны.
Просто зачем добавлять вообще все

2019-03-01 15:25 UTC, K-ksenia commented on hh-dep-monitoring-service/src/main/resources/scripts/create_account.sql
> +    login varchar(110) NOT NULL,
Это мы уже обсудили) и я убрала часть
Но согласна, можно что-то еще убрать, например, site_admin, blog, hireable, bio

2019-03-02 13:01 UTC, SuhoyVasya approved these changes

2019-03-02 18:07 UTC, anickishin requested changes

2019-03-02 18:07 UTC, anickishin commented on hh-dep-monitoring-service/src/main/resources/scripts/create_repository.sql
> +);
Сделай необходимый минимум. Если что-то понадобится, то добавим потом. Например, зачем нам знать про fork-и, stargazers, watchers?

2019-03-02 18:07 UTC, anickishin commented on hh-dep-monitoring-service/src/main/resources/scripts/create_repository.sql
> +);
Таблицу пользователей тоже надо прочистить

2019-03-02 18:52 UTC, anickishin requested changes

2019-03-02 18:52 UTC, anickishin commented on hh-dep-monitoring-service/src/main/resources/scripts/create_account.sql
> +CREATE TABLE IF NOT EXISTS account (
Нужно ли нам знать location, public_repos, public_gists, followers, following, created_at, updated_at?

2019-03-02 18:52 UTC, anickishin commented on hh-dep-monitoring-service/src/main/resources/scripts/create_account.sql
> +    type account_type NOT NULL,
Может, если оставлять организации, стоит их вытащить в отдельную таблицу?

2019-03-02 18:52 UTC, anickishin commented on hh-dep-monitoring-service/src/main/resources/scripts/create_account.sql
> +    company VARCHAR(110),
Если у нас в базе есть организации, то стоит ли у пользователя заводить отдельную строку с названием организации?

2019-03-02 21:20 UTC, colorbash commented on hh-dep-monitoring-service/src/main/resources/scripts/create_dependency.sql
> +);
пустая строка в конце файла должна быть https://stackoverflow.com/questions/5813311/no-newline-at-end-of-file

2019-03-02 21:41 UTC, K-ksenia commented on hh-dep-monitoring-service/src/main/resources/scripts/create_account.sql
> +CREATE TABLE IF NOT EXISTS account (
Ну вот и я говорю😅 нужно ли? Вообще, оставляла это для какой-нибудь статистики или графиков. Но, если следовать совету Никиты "не пишем код который может быть использован потом", то убираем это все

2019-03-02 21:42 UTC, K-ksenia commented on hh-dep-monitoring-service/src/main/resources/scripts/create_account.sql
> +    type account_type NOT NULL,
Мне кажется не надо, поля то все равно одинаковыми будут

2019-03-02 21:45 UTC, K-ksenia commented on hh-dep-monitoring-service/src/main/resources/scripts/create_account.sql
> +    company VARCHAR(110),
ну это как связь - в какой организации работает пользователь
на данном этапе можем не хранить это

2019-03-03 05:45 UTC, anickishin commented on hh-dep-monitoring-service/src/main/resources/scripts/create_account.sql
> +    company VARCHAR(110),
Связь делается через id, а не через название.
Тогда не надо и организации хранить.

2019-03-03 11:04 UTC, K-ksenia commented on hh-dep-monitoring-service/src/main/resources/scripts/create_account.sql
> +    company VARCHAR(110),
Окей, соглашусь
Но вообще, учитывая, что у нас все репозитории в рамках компании hh, можно компании не хранить, как думаешь?

2019-03-03 14:44 UTC, alinkov commented on hh-dep-monitoring-service/src/main/resources/scripts/create_dependency.sql
> +    -- dependency_type dependency_type
Давай всё-таки переименуем.
Будут зависимости, но они не будут иметь репозитория. Это те, что будем брать из maven.

И будут ещё связи. Наверное правильнее relation назвать. Связи будут задаваться вручную и у них ещё будет приоритет или как ты назвала dependency_type.

2019-03-03 14:44 UTC, alinkov commented on hh-dep-monitoring-service/src/main/resources/scripts/create_repository.sql
> +    account_id INT REFERENCES account NOT NULL,
Тут что именно указывается?
Это владелец или создатель?

2019-03-03 14:44 UTC, alinkov commented on hh-dep-monitoring-service/src/main/resources/scripts/create_account.sql
> +    avatar_url VARCHAR(255) NOT NULL,
Точно not null?

2019-03-04 05:19 UTC, anickishin commented on hh-dep-monitoring-service/src/main/resources/scripts/create_account.sql
> +    company VARCHAR(110),
Согласен

2019-03-04 05:33 UTC, anickishin requested changes

2019-03-04 05:33 UTC, anickishin commented on hh-dep-monitoring-service/src/main/resources/scripts/create_account.sql
> +CREATE TYPE account_type AS ENUM (
Раз уж мы компании не храним, то и енум этот не нужен

2019-03-04 05:33 UTC, anickishin commented on hh-dep-monitoring-service/src/main/resources/scripts/create_repository.sql
> +    subscribers_count INT
Для чего нам нужно знать кол-во подписчиков?
На что будет влиять приватность и запрет на запись?

2019-03-04 12:02 UTC, K-ksenia commented on hh-dep-monitoring-service/src/main/resources/scripts/create_repository.sql
> +    account_id INT REFERENCES account NOT NULL,
Изначально был владелец
Но, в принципе, раз владелец будет у всех один, можно это поле убрать

2019-03-04 12:04 UTC, K-ksenia commented on hh-dep-monitoring-service/src/main/resources/scripts/create_repository.sql
> +    account_id INT REFERENCES account NOT NULL,
У нас же у всех репозиториев владелец hh?

2019-03-04 12:08 UTC, K-ksenia commented on hh-dep-monitoring-service/src/main/resources/scripts/create_dependency.sql
> +    -- dependency_type dependency_type
Переименовала

2019-03-04 12:29 UTC, alinkov commented on hh-dep-monitoring-service/src/main/resources/scripts/create_repository.sql
> +    account_id INT REFERENCES account NOT NULL,
Владелец нам не нужен. А вот мейнтейнеры будут полезны

2019-03-04 20:05 UTC, alinkov approved these changes
Перед мержем надо будет схлопнуть коммиты

2019-03-05 08:24 UTC, anickishin approved these changes

2019-03-05 08:29 UTC, merged