Front 8 Add repositoryLinks administration
hhru/hh-dep-monitoring pull request #42
Opened 2019-05-11 09:27 UTC by K-ksenia

1) Добавлены добавление, редактирование и удаление ссылок
2) formResult в redux store перемещен из Relations в Notifications
3) Исправлен repoLinkIconWrapper

<img width="976" alt="Снимок экрана 2019-05-11 в 12 23 59" src="https://user-images.githubusercontent.com/18597504/57567843-00878880-73e8-11e9-8a5b-85955f974fd8.png">
<img width="979" alt="Снимок экрана 2019-05-11 в 12 25 02" src="https://user-images.githubusercontent.com/18597504/57567851-08dfc380-73e8-11e9-8125-26b7ed69685b.png">
<img width="973" alt="Снимок экрана 2019-05-11 в 12 24 22" src="https://user-images.githubusercontent.com/18597504/57567856-0d0be100-73e8-11e9-9182-83dfff55c564.png">
<img width="978" alt="Снимок экрана 2019-05-11 в 12 24 35" src="https://user-images.githubusercontent.com/18597504/57567857-0ed5a480-73e8-11e9-8e70-77b75aa36d06.png">

2019-05-12 08:49 UTC, gooverdian requested changes

2019-05-12 08:49 UTC, gooverdian commented on frontend/src/MainBlock/RepositoryLinks/DeleteLinkButton.js
> +        float: 'right',
Крайне желательно обходиться без float, он заставляет делать странные вещи, например, распологать элементы не так, как они будут выглядеть в итоге, может, как-то можно флексом?

2019-05-12 08:49 UTC, gooverdian commented on frontend/src/MainBlock/RepositoryLinks/FormContent.js
> +            { rule: 'required', message: 'Link url is required to be selected' },
Selected?

2019-05-12 08:49 UTC, gooverdian commented on frontend/src/MainBlock/RepositoryLinks/FormContent.js
> +    link }) {
зачем так? длина - 96 символов

2019-05-12 08:49 UTC, gooverdian commented on frontend/src/MainBlock/RepositoryLinks/FormContent.js
> +        <Fragment>
Я что-то только что понял, что несмотря на то, что тут форма - на самом деле - самой формы (тег form) нет.. а чего так?

2019-05-12 08:49 UTC, gooverdian commented on frontend/src/MainBlock/RepositoryLinks/FormContent.js
> +    },
тут тоже можно в одну строку и в файле ниже тоже, и вообще, лучше везде одинаково )

2019-05-12 08:49 UTC, gooverdian commented on frontend/src/MainBlock/RepositoryLinks/LinkTypeSelect.js
> +          && linkTypes.map(item => (
что-то уехало

2019-05-12 08:49 UTC, gooverdian commented on frontend/src/MainBlock/RepositoryLinks/OpenFormButton.js
> +    }, [linkTypes]);
здесь нужна эта зависимость? linkTypes нигде не удаляется, значит fetch будет вызван один раз, а функция зачем-то дважды

2019-05-12 08:49 UTC, gooverdian commented on frontend/src/MainBlock/RepositoryLinks/RepositoryLinks.js
> +                        <a href={item.linkUrl}>
Почему не Link? чтобы он нормально работал с внешними ссылками, нужно обязательно указывать схему

2019-05-12 08:49 UTC, gooverdian commented on frontend/src/MainBlock/RepositoryLinks/RepositoryLinks.js
> +    const sizer = {
можно вынести из компонента

2019-05-12 08:49 UTC, gooverdian commented on frontend/src/MainBlock/RepositoryLinks/UrlInput.js
> +            && <FormHelperText className={classes.errorText}>{url.error}</FormHelperText>}
тоже можно в одну строку

2019-05-12 08:49 UTC, gooverdian commented on frontend/src/Utils/Validator.js
> +                !attributeResult.error && (attributeResult.error = rule.message || `Invalid value of field ${name}`);
Можно просто сделать return и не проверять дальше

2019-05-12 08:49 UTC, gooverdian commented on frontend/src/redux/models/Repository/repositoriesActions.js
> +                dispatch(setFormResultAction(true, 'Link', 'deleted'));
если эти экшены диспэтчатся всегда парой - почему бы их не объединить?

2019-05-13 10:13 UTC, K-ksenia commented on frontend/src/MainBlock/RepositoryLinks/DeleteLinkButton.js
> +        float: 'right',
не хотела флексом, так как тогда надо создавать еще один div
но раз с float неочень, сделала флексоми

2019-05-13 10:13 UTC, K-ksenia commented on frontend/src/MainBlock/RepositoryLinks/FormContent.js
> +    link }) {
Исправила

2019-05-13 10:13 UTC, K-ksenia commented on frontend/src/MainBlock/RepositoryLinks/FormContent.js
> +            { rule: 'required', message: 'Link url is required to be selected' },
ой, исправила на filled

2019-05-13 10:13 UTC, K-ksenia commented on frontend/src/MainBlock/RepositoryLinks/FormContent.js
> +    },
А я делала, что если одно свойство, то в одну строку, а если больше, то в несколько
Мне кажется, так удобнее читается 
Правда у меня не во всех местах одинаково, исправила

2019-05-13 10:13 UTC, K-ksenia commented on frontend/src/MainBlock/RepositoryLinks/LinkTypeSelect.js
> +          && linkTypes.map(item => (
Спасибо

2019-05-13 10:13 UTC, K-ksenia commented on frontend/src/MainBlock/RepositoryLinks/OpenFormButton.js
> +    }, [linkTypes]);
Исправила

2019-05-13 10:13 UTC, K-ksenia commented on frontend/src/MainBlock/RepositoryLinks/RepositoryLinks.js
> +    const sizer = {
вынесла

2019-05-13 10:13 UTC, K-ksenia commented on frontend/src/MainBlock/RepositoryLinks/UrlInput.js
> +            && <FormHelperText className={classes.errorText}>{url.error}</FormHelperText>}
угу

2019-05-13 10:13 UTC, K-ksenia commented on frontend/src/Utils/Validator.js
> +                !attributeResult.error && (attributeResult.error = rule.message || `Invalid value of field ${name}`);
сделала через some, так как return для forEach цикл не прерывает

2019-05-13 10:13 UTC, K-ksenia commented on frontend/src/redux/models/Repository/repositoriesActions.js
> +                dispatch(setFormResultAction(true, 'Link', 'deleted'));
потому что первый экшн вызывается для разных редьюсеров
ну то есть тут для Repository
есть еще для Relation
```
dispatch(deleteRelationAction(repositoryId, relationId));
dispatch(setFormResultAction(true, 'Relation', 'deleted'));
```
Или можно все равно как-то объединить, при этом не дублируя formResult для каждой сущности?

2019-05-13 10:13 UTC, K-ksenia commented on frontend/src/MainBlock/RepositoryLinks/RepositoryLinks.js
> +                        <a href={item.linkUrl}>
исправила на Link, наличие схемы проверяется в валидаторе при добавлении ссылки

2019-05-13 10:13 UTC, K-ksenia commented on frontend/src/MainBlock/RepositoryLinks/FormContent.js
> +        <Fragment>
тег form добавила

2019-05-13 10:49 UTC, gooverdian requested changes
Не спеши

2019-05-13 10:49 UTC, gooverdian commented on frontend/src/CommonComponents/Form.js
> +    children: PropTypes.array.isRequired,
для чего-то, что можно отрендерить, используется PropTypes.node

2019-05-13 10:49 UTC, gooverdian commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
>                      Submit
type="submit" и убрать onClick

2019-05-13 10:49 UTC, gooverdian commented on frontend/src/redux/models/Repository/repositoriesActions.js
> +                dispatch(setFormResultAction(true, 'Link', 'deleted'));
вызывать setFormResultAction из предыдущего экшена, например?

2019-05-13 10:49 UTC, gooverdian commented on frontend/src/MainBlock/Repository/DeleteRelation/DeleteRelationDialog.js
> +                    <Button onClick={handleSubmit} variant="contained" color="primary">
type="submit" и убрать onClick

2019-05-13 12:06 UTC, gooverdian commented on frontend/src/redux/models/Repository/repositoriesActions.js
> +                dispatch(setFormResultAction(true, 'Link', 'deleted'));
обсудили, это я погорячился

2019-05-13 12:09 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/DeleteRelation/DeleteRelationDialog.js
> +                    <Button onClick={handleSubmit} variant="contained" color="primary">
поспешила

2019-05-13 12:09 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/RelationForm/FormContent.js
>                      Submit
спасибо

2019-05-13 12:09 UTC, K-ksenia commented on frontend/src/CommonComponents/Form.js
> +    children: PropTypes.array.isRequired,
Спасибо

2019-05-13 12:09 UTC, K-ksenia commented on frontend/src/redux/models/Repository/repositoriesActions.js
> +                dispatch(setFormResultAction(true, 'Link', 'deleted'));
обсудили в слаке

2019-05-13 12:30 UTC, gooverdian approved these changes

2019-05-13 17:02 UTC, alinkov commented on frontend/src/CommonComponents/Form.js
> +        if (valid) {
думаю, что лучше так
```javascript
if (valid) {
onSubmit && onSubmit();
} else {
onErrors && onErrors(attributes);
}
```
т.е. без return обойтись

2019-05-13 17:02 UTC, alinkov commented on frontend/src/MainBlock/Repository/DeleteRelation/DeleteRelationDialog.js
> +                <DialogTitle>Are you sure, that you want to delete this relation?</DialogTitle>
`,` здесь не нужна

2019-05-13 17:02 UTC, alinkov commented on frontend/src/MainBlock/RepositoryLinks/DeleteLinkButton.js
> +        setOpen(false);
а не должно ли это быть в `handleClose` ?

2019-05-13 17:02 UTC, alinkov commented on frontend/src/MainBlock/RepositoryLinks/FormContent.js
> +        clearForm();
а зачем это при закрытии?
чтобы при следующем запуске ничего лишнего не было? если так, то думаю, что лучше будет при открытии это очищать

2019-05-13 19:13 UTC, K-ksenia commented on frontend/src/CommonComponents/Form.js
> +        if (valid) {
а я сначала так и сделала, но Никита говорит, что лучше без else

2019-05-13 19:13 UTC, K-ksenia commented on frontend/src/MainBlock/Repository/DeleteRelation/DeleteRelationDialog.js
> +                <DialogTitle>Are you sure, that you want to delete this relation?</DialogTitle>
исправила

2019-05-13 19:13 UTC, K-ksenia commented on frontend/src/MainBlock/RepositoryLinks/DeleteLinkButton.js
> +        setOpen(false);
нет
setDialogOpen (тот что в handleClose) - закрывает окно удаления, а переданный извне setOpen, закрывает внешнее окно редактирования
кнопка удаления находится в окне редактирования, поэтому при простом закрытии формы удаления должна закрываться только она сама, а при сабмите форма удаления и редактирования
Т. е. при сабмите должны вызваться обе функции, при отмене удаления, только setDialogOpen

2019-05-13 19:13 UTC, K-ksenia commented on frontend/src/MainBlock/RepositoryLinks/FormContent.js
> +        clearForm();
да, чтобы поля очищались
но сейчас попробовала clearForm убрать, и походу, после того, как я добавила тег form, они и сами очищаются 🤔

2019-05-14 04:55 UTC, SuhoyVasya approved these changes

2019-05-14 14:48 UTC, alinkov approved these changes

2019-05-14 16:16 UTC, merged