Back 30 add artifact to repository resource
hhru/hh-dep-monitoring pull request #43
Opened 2019-05-11 22:05 UTC by Afftobus

ArtifactDao будет конфликтовать, скопипамтил из задачи Андрея. 
Не стал делать отдельного ресурса, для получения артефактов по репозиторию этого вполне хватает.

2019-05-12 09:57 UTC, alinkov approved these changes

2019-05-12 09:57 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/ArtifactDto.java
> +    public static final class ArtifactDtoBuilder {
в классе 4 поля, так что вполне себе можно было обойтись без билдера.
Билдер обычно нужен для создания более сложных объектов, чтобы не делать конструктор из 100500 полей

2019-05-13 05:53 UTC, SuhoyVasya approved these changes

2019-05-13 11:18 UTC, colorbash requested changes

2019-05-13 11:18 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/service/mapper/RepositoryMapperTest.java
>      //private final RepositoryMapper repositoryMapper = new RepositoryMapper();
зачем эта строчка в коде?

2019-05-13 11:18 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/StructCreator.java
> +    public static Artifact createArtifactEntity(Long repositoryId){
){ -> ) {

2019-05-13 11:18 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    public Integer addItemToArtifactTable(Long repositoryId){
){ -> ) {

2019-05-13 11:18 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/ArtifactMapper.java
> +        entity.setRepository(repositoryDao
а почему бы не делать findOne в самом начале? если эксепшн кинется зачем мы предыддущую работу делали?

2019-05-13 11:18 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/ArtifactDto.java
> +    @NotNull
не уверен но если NotNull то наверное можно заменить на примитивы? инт и лонг, джексон сам кинет исключение и NotNull не нужен, н надо проверить

2019-05-13 19:36 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/service/mapper/RepositoryMapperTest.java
>      //private final RepositoryMapper repositoryMapper = new RepositoryMapper();
это не я. 
это кто-то за собой не убрал :-)

2019-05-13 19:36 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/ArtifactDto.java
> +    @NotNull
мы изначально пошли таким путём, чтобы исключить "значения по умолчанию", характерные для примитивов и валидировать уже аннотациями.

2019-05-13 19:36 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/ArtifactMapper.java
> +        entity.setRepository(repositoryDao
ок.

2019-05-13 19:36 UTC, Afftobus commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    public Integer addItemToArtifactTable(Long repositoryId){
блин, сижу думаю, что означают эти таинственные символы. 
обернуть в лямбду?
переделать в функциональном стиле? 
и только потом понял, что пробела не хватает :-)

2019-05-14 17:00 UTC, colorbash approved these changes

2019-05-14 17:00 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/mapper/ArtifactMapper.java
> +        entity.setRepository(repositoryDao
я имел ввиду `repositoryDao.dto.getRepositoryId())` вынести в локальныю переменную прям перед `Artifact entity = new Artifact()`

2019-05-15 11:47 UTC, anickishin requested changes

2019-05-15 11:47 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/ArtifactDto.java
> +    private Long repositoryId;
У артефакта может не быть репозитория

2019-05-19 05:34 UTC, anickishin approved these changes

2019-05-20 06:24 UTC, merged