Back 29 Сортировка по нескольким полям
hhru/hh-dep-monitoring pull request #45
Opened 2019-05-15 11:43 UTC by SuhoyVasya

2019-05-15 12:55 UTC, colorbash requested changes

2019-05-15 12:55 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryDaoImpl.java
> +        }
я бы написал тело цикла так 
```java
if (getFieldNames().contains(orderPoint.getField())) {
                var someNameVariable = repository.get(orderPoint.getField())
                cq.orderBy(orderPoint.isAscending() ? 
                                           cb.asc(someNameVariable) :
                                           cb.desc(someNameVariable));
}
```

2019-05-15 12:55 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +        if (builder.orderPointList != null) {
тут тож тернарный лаконичнее

2019-05-15 12:55 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +            if (string == null || string.isEmpty()) {
StringUtils.isBlank()

2019-05-15 12:55 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +            if (field == null || field.isEmpty()) {
StringUtils.isBlank

2019-05-15 12:55 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +            string = string.substring(1, string.length() - 1);
это что и зачем? хоть коммент оставь

2019-05-15 12:55 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/wtf")
wtf?

2019-05-15 12:55 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/StructCreator.java
> +            return "";
это прям странная логика, хочешь для тестов сделать - делай метод с чекед эксепшенами, так удобнее

2019-05-15 13:21 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryDaoImpl.java
> +        }
прям так и сделал

2019-05-15 13:21 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +        if (builder.orderPointList != null) {
поменял на тернарный

2019-05-15 13:21 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +            if (field == null || field.isEmpty()) {
поправил

2019-05-15 13:21 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +            if (string == null || string.isEmpty()) {
поправил

2019-05-15 13:21 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +            string = string.substring(1, string.length() - 1);
убрать скобку слева и справа))))

2019-05-15 13:21 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +    @Path("/wtf")
забыл убрать

2019-05-15 13:21 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/StructCreator.java
> +            return "";
не очень понял что тут не так и как правильно

2019-05-15 14:27 UTC, alinkov requested changes

2019-05-15 14:27 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +import org.eclipse.jetty.util.StringUtil;
не надо этот класс использовать. Используй из apache.commons

2019-05-15 14:27 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +    public static final class OrderPoint {
сделай Serializable + дефолтный конструктор. Также не очень нравится название.
Можно назвать `PageSort`, как это сделано в спринге

2019-05-15 14:27 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +        private String field;
лучше property

2019-05-15 14:27 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +            if (StringUtil.isBlank(field)) {
давай эту проверку в сам ресурс

2019-05-15 14:27 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +            string = string.substring(1, string.length() - 1);
а зачем вообще тут скобки?

2019-05-15 14:27 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +     * request like host/repository/page?order={name,true}&order={createdAt,true}&perPage=10
Лучше так:
`order=createdAt,asc`

true только в ступор поставит. Да и эти скобки не нужны

2019-05-15 14:27 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryDaoImpl.java
> +        }
Нужно бы эту логику в AbstractDao

2019-05-15 14:27 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +        this.orderPointList = builder.orderPointList != null ? builder.orderPointList : new ArrayList<>();
```suggestion
        this.orderPointList = Objects.requireNonNullElseGet(builder.orderPointList, List::of);
```

2019-05-15 14:27 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
>      private PageRequestDto() {
хм. А почему конструктор приватный?

2019-05-15 14:27 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/StructCreator.java
> +            return "";
а для каких символов тут понадобился URLEncoder ?

2019-05-15 14:45 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/StructCreator.java
> +            return "";
ты этот код используешь ток в тестах ну и сделай до упора throws UnsupportedEncodingException на каждом методе пока он не упрется в метод теста

2019-05-16 06:16 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryDaoImpl.java
> +        }
ок, но прийдется в pageRequestDto добавить поле по которому будет фильтрация через like.

2019-05-16 06:16 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +import org.eclipse.jetty.util.StringUtil;
поменял

2019-05-16 06:16 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
>      private PageRequestDto() {
поменял. А зачем он должен быть public?

2019-05-16 06:16 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +        this.orderPointList = builder.orderPointList != null ? builder.orderPointList : new ArrayList<>();
поменял

2019-05-16 06:16 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +    public static final class OrderPoint {
сделал

2019-05-16 06:16 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +        private String field;
сделал

2019-05-16 06:16 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +            string = string.substring(1, string.length() - 1);
request like host/repository/page?order={name,true}&order={createdAt,true}&perPage=10 
скобки чтобы отделить отделить параметр-объект от остального. По аналогии с json. Сделал это потому что @QueryParam может сам парсить List<T> где T отдается методом T.valueOf(String)

2019-05-16 06:16 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +            string = string.substring(1, string.length() - 1);
вместо скобок можно все что угодно кроме запятых наверное

2019-05-16 06:16 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +            if (StringUtil.isBlank(field)) {
зачем она в ресурсе? я специально сделал чтобы в ресурс уже приходил готовый объект

2019-05-16 06:16 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +     * request like host/repository/page?order={name,true}&order={createdAt,true}&perPage=10
true/false поменял на asc/desс
скобки не трогал

2019-05-16 06:16 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/StructCreator.java
> +            return "";
> а для каких символов тут понадобился URLEncoder ?

в тесте target.queryParam() ругается на запятую



> ты этот код используешь ток в тестах ну и сделай до упора throws UnsupportedEncodingException на каждом методе пока он не упрется в метод теста

сделал

2019-05-16 08:12 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/RepositoryResource.java
> +     * request like host/repository/page?order={name,true}&order={createdAt,true}&perPage=10
А чем тебе эти скобки нравятся? Без них же проще. Потом эти скобки нужно будет еще на фронте добавлять. Был бы в них хоть какой-то смысл

2019-05-16 08:14 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryDaoImpl.java
> +        }
Можно добавить метод в AbstractDao getDefaultFilterField, который возвращает null (в таком случае не фильтруется), но этот метод можно переопределить. Ну или какой-то такой вариант. К примеру метод addFilter, который можно будет переопределить

2019-05-16 08:14 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +            string = string.substring(1, string.length() - 1);
убери их тогда вообще. Они только сложности добавят

2019-05-16 13:28 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +            string = string.substring(1, string.length() - 1);
убрал

2019-05-16 13:28 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryDaoImpl.java
> +        }
первый вариант сделал

2019-05-17 11:32 UTC, alinkov reviewed
В общем уже более менее норм

2019-05-17 11:32 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        cq.where(cb.like(cb.lower(root.get(getDefaultFilterField())), searchString.toLowerCase()));
давай это лучше под условие. Если  searchString не пустая

2019-05-17 11:32 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    public Set<String> getFieldNames() {
меняй на protected

2019-05-17 11:32 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    public String getDefaultFilterField() {
тут тоже на protected
и лучше возвращай null. В таком случае нет фильтрации

2019-05-17 11:32 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +            if (isBlank(array[1]) || (!array[1].equals("asc") && !array[1].equals("desc"))) {
equalsIgnoreCase
и сделал бы этот параметр не обязательным, чтобы по дефолту было asc

2019-05-17 12:46 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        cq.where(cb.like(cb.lower(root.get(getDefaultFilterField())), searchString.toLowerCase()));
сделал

2019-05-17 12:46 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    public Set<String> getFieldNames() {
поменял

2019-05-17 12:46 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    public String getDefaultFilterField() {
поменял

2019-05-17 12:46 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/PageRequestDto.java
> +            if (isBlank(array[1]) || (!array[1].equals("asc") && !array[1].equals("desc"))) {
сделал. Оставил проверку на мусор

2019-05-17 13:58 UTC, alinkov approved these changes

2019-05-20 08:17 UTC, colorbash approved these changes

2019-05-21 06:43 UTC, merged