Front 7 Add repositories pagination
hhru/hh-dep-monitoring pull request #49
Opened 2019-05-21 10:20 UTC by K-ksenia

Добавлена постраничность репозиториев с возможностью указывать количество элементов на странице
<img width="1440" alt="Снимок экрана 2019-05-21 в 13 18 46" src="https://user-images.githubusercontent.com/18597504/58088313-0d1b9600-7bcb-11e9-8a25-b30da984f486.png">
<img width="1440" alt="Снимок экрана 2019-05-21 в 13 19 09" src="https://user-images.githubusercontent.com/18597504/58088316-0f7df000-7bcb-11e9-9415-1ddcdd4d9eb4.png">

2019-05-22 11:10 UTC, gooverdian requested changes

2019-05-22 11:10 UTC, gooverdian commented on frontend/src/MainBlock/Pagination/PaginationWidget.js
> +        } else {
Тут можно было сделать return, но лучше вообще обойтись без условия

2019-05-22 11:10 UTC, gooverdian commented on frontend/src/MainBlock/Pagination/PaginationWidget.js
> +        (newPage !== page && setPage) && setPage(newPage);
почему при изменении страницы вызывается **set**Page, а при изменении количества элементов на странице - **on**PerPageChange ?

2019-05-22 11:10 UTC, gooverdian commented on frontend/src/MainBlock/Pagination/PaginationWidget.js
> +            {(pagination.page !== page || pagination.pages !== pages) ? regenerateCache() : cache}
вызов regenerateCache приведет к ререндеру всего компонента, в итоге, компонент будет рисоваться два раза за каждое изменение в страницах

2019-05-22 11:10 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/Repositories.js
> +            {repositories[page] && (
Если репозиториев нет на этой странице - пагинация тоже не выводится, почему так?
Кажется, что данные пагинации лучше не хранить внутри каждой страницы

2019-05-22 11:10 UTC, gooverdian commented on frontend/src/redux/models/Repository/repositoriesReducer.js
> +            ...state,
информацию о пагинации лучше хранить где-то здесь, потому что она не зависит от содержимого страницы

2019-05-22 11:10 UTC, gooverdian commented on frontend/src/redux/models/Repository/repositoriesSelectors.js
> +    }
А как так получается, что есть и просто фетч репозиториев, и постраничный фетч?

2019-05-23 11:18 UTC, K-ksenia commented on frontend/src/MainBlock/Pagination/PaginationWidget.js
> +        (newPage !== page && setPage) && setPage(newPage);
ой, сделала одинаково

2019-05-23 11:18 UTC, K-ksenia commented on frontend/src/MainBlock/Pagination/PaginationWidget.js
> +        } else {
Исправила на предложенный тобою вариант

2019-05-23 11:18 UTC, K-ksenia commented on frontend/src/redux/models/Repository/repositoriesReducer.js
> +            ...state,
Сделала

2019-05-23 11:18 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/Repositories.js
> +            {repositories[page] && (
Разделила

2019-05-23 11:18 UTC, K-ksenia commented on frontend/src/redux/models/Repository/repositoriesSelectors.js
> +    }
Просто фетч нам нужен, чтобы получить данные для поля с селектом в форме

2019-05-23 11:18 UTC, K-ksenia commented on frontend/src/MainBlock/Pagination/PaginationWidget.js
> +            {(pagination.page !== page || pagination.pages !== pages) ? regenerateCache() : cache}
Сделала pagination и cache обычными переменными

2019-05-23 11:25 UTC, gooverdian commented on frontend/src/redux/models/Repository/repositoriesSelectors.js
> +    }
они как-то отличаются по размеру приходящих данных по каждому репозиторию?

2019-05-23 15:46 UTC, gooverdian requested changes
Наличие двух эндпоинтов, отдающих одинаковые данные, и дублирование данных в сторе - это плохо.

2019-05-23 15:46 UTC, gooverdian commented on frontend/src/MainBlock/Pagination/PaginationButton.js
> +    onClick: PropTypes.func,
ты не проверяешь, передали тебе этот проп, или нет, либо нужно проверять, либо добавить isRequired

2019-05-23 15:46 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/Repositories.js
> +        setPage(0);
чисто теоретически, можно было бы по текущим page и perPage вычислять страницу, на которую нужно отправить пользователя, потому как меня, например, прям расстраивает, когда при изменении размера страницы на сайтах меня перекидывает обратно на первую, но это по желанию, конечно

2019-05-23 15:46 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/Repositories.js
> +        clearRepositoriesPages();
Эту функцию лучше вызвать до остальных. Вызовы, конечно, асинхронные и это не влияет ни на что, но так кажется, логичнее

2019-05-23 15:46 UTC, gooverdian commented on frontend/src/redux/models/Repository/repositoriesSelectors.js
> +    }
нет, судя по условию выше - не отличаются, то есть ты хранишь, а бэк отдает одинаковые данные и постранично, и одним скопом - не надо так, это прям какой-то дикий костыль

2019-05-23 17:55 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/Repositories.js
> +        setPage(0);
да, полностью согласна 
мне почему-то казалось это невозможным/сложным
сделала с вычислением

2019-05-23 17:55 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/Repositories.js
> +        clearRepositoriesPages();
Окей

2019-05-23 17:55 UTC, K-ksenia commented on frontend/src/MainBlock/Pagination/PaginationButton.js
> +    onClick: PropTypes.func,
Сделала проверку

2019-05-23 17:55 UTC, K-ksenia commented on frontend/src/redux/models/Repository/repositoriesSelectors.js
> +    }
Сделала, как обсудили

2019-05-24 07:54 UTC, gooverdian approved these changes
так норм

2019-05-24 07:54 UTC, gooverdian commented on frontend/src/MainBlock/Pagination/PaginationWidget.js
> +        (newPage !== page && onPageChange) && onPageChange(newPage);
можно не проверять onPageChange, потому что isRequired

2019-05-24 10:55 UTC, SuhoyVasya approved these changes

2019-05-24 16:07 UTC, alinkov approved these changes

2019-05-24 16:15 UTC, merged