add hibernate DAO entitys
hhru/hh-dep-monitoring pull request #5
Opened 2019-03-02 12:45 UTC by Afftobus

2019-03-02 13:07 UTC, SuhoyVasya approved these changes

2019-03-02 13:30 UTC, alinkov requested changes

2019-03-02 13:30 UTC, alinkov commented on hh-dep-monitoring-service/pom.xml
> +            <groupId>javax.persistence</groupId>
Давай лучше затащим nab-hibernate
Эта зависимость там уже будет

2019-03-02 13:30 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/Account.java
> +    private String login; // varchar(110) NOT NULL,
Комментарии для полей лучше оставлять не так, а сверху
```/**Comment*/```
Тогда можно будет как JavaDoc читать

2019-03-02 13:30 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/Account.java
> +    private String login; // varchar(110) NOT NULL,
Ограничения лучше не комментарием, а аннотациями добавь
```@NotNull``` и тд

2019-03-02 13:30 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/Account.java
> +    private Boolean isHireable; // bool,
Лучше используй boolean, чтобы потом не иметь проблем с null

2019-03-02 13:30 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/Account.java
> +package ru.hh.school.depmonitoring.dao;
Нужно положить в другой package.
К примеру entities или entity
DAO не подходит для сущностей

2019-03-02 13:30 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/Account.java
> +public class Account {
Добавь геттеров и сеттеров

2019-03-02 18:55 UTC, alinkov reviewed
Ещё желательно переопределить equals/hashCode
В них достаточно сравнения по id полю.

2019-03-02 19:56 UTC, Afftobus commented
> Ещё желательно переопределить equals/hashCode
> В них достаточно сравнения по id полю.

Добавил

2019-03-02 21:20 UTC, colorbash commented on hh-dep-monitoring-service/pom.xml
>  </project>
пустая строка в конце файла должна быть https://stackoverflow.com/questions/5813311/no-newline-at-end-of-file

2019-03-03 10:14 UTC, Afftobus commented on hh-dep-monitoring-service/pom.xml
>  </project>
добавил

2019-03-03 14:46 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/DaoFactory.java
> +public class DaoFactory {
А что это и зачем?

2019-03-03 14:46 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/HibetnateDaoFactory.java
> +public class HibetnateDaoFactory {
Не совсем понятно назначение данных классов

2019-03-03 16:17 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/HibetnateDaoFactory.java
> +public class HibetnateDaoFactory {
с очередным комитом забыл отключить эти файлы. 
делал на будущее, пушить не планировал.
сейчас убрал

2019-03-04 12:31 UTC, alinkov commented
У меня замечаний нет, но забирать можно будет только после модели

2019-03-04 12:31 UTC, alinkov approved these changes

2019-03-05 16:24 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/Relation.java
> +    private Integer repositoryFromId;
не уверен, что есть смысл в двух полях.
Но в общем решайте сами

2019-03-05 16:24 UTC, alinkov approved these changes

2019-03-05 18:03 UTC, merged