Front 21 artifact tree page
hhru/hh-dep-monitoring pull request #52
Opened 2019-05-26 13:52 UTC by Afftobus

2019-05-26 15:50 UTC, K-ksenia requested changes
То, что код DependencyItem почти дублирует код ArtifactRepositoryItem, и код ArtifactRepositories дублирует DependencyItems кажется не совсем правильным
Надо подумать, как можно сделать иначе

2019-05-26 15:50 UTC, K-ksenia commented on frontend/src/MainBlock/Artifacts/ArtifactRepositories.js
> +import { withStyles } from '@material-ui/core';
Этот импорт надо повыше перенести

2019-05-26 15:50 UTC, K-ksenia commented on frontend/src/MainBlock/Artifacts/ArtifactRepositories.js
> +        <Fragment>
Так как компонент обрамляется в List, Fragment можно убрать

2019-05-26 15:50 UTC, K-ksenia commented on frontend/src/MainBlock/Artifacts/ArtifactRepositoryItem.js
> +import { genericLink, nestedBlock, secondaryItemColor } from 'Utils/commonStyles';
этот импорт надо перенести вниз к `import DependencyItems from './DependencyItems';`

2019-05-26 15:50 UTC, K-ksenia commented on frontend/src/MainBlock/Artifacts/ArtifactRepositoryItem.js
> +import classNames from 'classnames';
этот наверх к 
```
import React, { Fragment, useState } from 'react';
import PropTypes from 'prop-types';
```

2019-05-26 15:50 UTC, K-ksenia commented on frontend/src/MainBlock/Artifacts/ArtifactRepositoryItem.js
> +import { withStyles } from '@material-ui/core/styles';
а этот ко всем от material-ui

2019-05-26 15:50 UTC, K-ksenia commented on frontend/src/MainBlock/Artifacts/ArtifactRepositoryItem.js
> +    const haveDependencies = typeof repository.dependencies !== 'undefined'
По идее вместо `typeof repository.dependencies !== 'undefined' &&` можно просто писать  `repository.dependencies &&`

2019-05-26 15:50 UTC, K-ksenia commented on frontend/src/MainBlock/Artifacts/Artifacts.js
> +import { fetchArtifactTree } from '../../redux/models/Artifact/artifactsActions';
когда в from начинаются ../, лучше писать абсолютный путь (относительно src), т.е. просто 'redux/models/Artifact/artifactsActions'

2019-05-26 15:50 UTC, K-ksenia commented on frontend/src/MainBlock/Artifacts/DependencyItem.js
> +import { withStyles } from '@material-ui/core/styles';
в общем импорты надо везде поправить в соответствии с предыдущими комментариями

2019-05-26 15:50 UTC, K-ksenia commented on frontend/src/MainBlock/Artifacts/Artifacts.js
> +                    Artifacts not found
Отступ большеват

2019-05-26 15:50 UTC, K-ksenia commented on frontend/src/MainBlock/Artifacts/Artifacts.js
> +                <ArtifactRepositories items={artifactTree} />
вообще, мне кажется, можно не создавать отдельный компонент ArtifactRepositories, а его содержимое уместить прям тут

2019-05-26 15:50 UTC, K-ksenia commented on frontend/src/MainBlock/Artifacts/DependencyItem.js
> +:
это : не должно быть с отступом, как соседние строки?

2019-05-26 15:50 UTC, K-ksenia commented on frontend/src/MainBlock/Artifacts/DependencyItem.js
> +                            {' '}
можно так {'ver. '}
или даже так 
```
{`ver. ${dependency.artifactVersion.versiom}`} 
```

2019-05-26 15:50 UTC, K-ksenia commented on frontend/src/MainBlock/Artifacts/DependencyItems.js
> +        <Fragment>
тут аналогично комментарию выше, можно обойтись без Fragment

2019-05-27 08:41 UTC, gooverdian requested changes
Есть что поправить

2019-05-27 08:41 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/ArtifactRepositoryItem.js
> +        && repository.dependencies.length > 0;
`> 0` ни к чему, ты уже проверил, что это массив, а 0 является фолси

2019-05-27 08:41 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/Artifacts.js
> +    if (typeof artifactTree !== 'undefined' && Array.isArray(artifactTree)) {
```suggestion
    if (artifactTree) {
```
То, что это массив определяется PropTypes

2019-05-27 08:41 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/Artifacts.js
> +                    {artifactTree && artifactTree.map(repository => (
ты уже проверил это выше

2019-05-27 08:41 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/Artifacts.js
> +    );
я бы сделал это тернарником, но это по желанию

2019-05-27 08:41 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/DependencyItem.js
> +        && dependency.childs.length > 0;
Это условие делает тоже самое, что и в ArtifactRepositoryItem.js, но выглядит по-другому..
нужно убрать проверку типа и длины, и желательно использовать слово children, потому что https://english.stackexchange.com/questions/308706/can-childs-ever-be-the-plural-of-child-in-standard-english

2019-05-27 08:41 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/DependencyItem.js
> +                {haveDependencies && (
Это подозрительно напоминает ArtifactRepositoryItem.js, и еще какой-то компонент, который уже есть, не хочешь вынести общую логику из всех похожих, вместо копипаста?

2019-05-27 08:41 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/DependencyItem.js
> +                    secondary={`ver. ${dependency.artifactVersion.versiom}`}
versio**m** ?

2019-05-27 08:41 UTC, gooverdian commented on frontend/src/redux/models/Artifact/artifactsActions.js
> +                        versiom: '1.2.654',
тоже versio**m**

2019-05-27 08:41 UTC, gooverdian commented on frontend/src/redux/models/Artifact/artifactsActions.js
> +        //     });
зачем он здесь? И так понятно, что текущее решение временное. Комменты, которые содержат код и не являются частью документации - недопустимы, документация - ок, остальные комменты - нежелательны, поскольку код должен быть понятен и без них.

2019-05-27 08:41 UTC, gooverdian commented on frontend/src/redux/models/Artifact/artifactsActions.js
> +                    childs:
children

2019-05-27 08:41 UTC, gooverdian commented on frontend/src/redux/models/Artifact/artifactsActions.js
> +// import {addMessageAction} from "../Notification/notificationsActions";
я там ниже про комменты написал

2019-05-27 08:57 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/ArtifactRepositories.js
> +        <Fragment>
На всякий случай, чуть более подробно: Fragment используется в случаях, когда ты не хочешь обрамлять несколько компонентов или тегов в реальный html тег, но хочешь вернуть несколько элементов вне массива. Реакт позволяет на верхнем уровне вернуть только один элемент, поэтому в ситуациях типа
```
return (
    <Fragment>
        <A/>
        <B/>
    </Fragment>
);
```
Он нужен, а вот в
```
return (
    <div>
        <A/>
        <B/>
    </div>
);
```
или
return ( 
    <A/>
);
```
не нужен

2019-05-28 18:49 UTC, K-ksenia commented on frontend/src/MainBlock/Artifacts/ArtifactListItem.js
> +import PropTypes from 'prop-types';
Импорт затерялся, надо наверх

2019-05-28 18:49 UTC, K-ksenia commented on frontend/src/MainBlock/Artifacts/Artifacts.js
> +    }
я бы как-то так сделала
```
        return (
            <Paper className={classes.root}>
                <Typography variant="h4">
                    Artifacts {!artifactTree && ' not found'}
                </Typography>
                {artifactTree && <List>
                    {artifactTree.map(repository => (
                        <Fragment key={repository.repositoryId}>
                            <Divider />
                            <ArtifactRepositoryItem repository={repository} />
                        </Fragment>
                    ))}
                </List>}
            </Paper>
        );
```
или тернарником, как сказал Никита

2019-05-28 18:49 UTC, K-ksenia commented on frontend/src/Utils/constants.js
> +export const BASE_URL = 'http://localhost:8080/';
Это надо возвращать обратно, иначе наш докер не запустится, насколько я поняла

2019-05-28 18:49 UTC, K-ksenia commented on frontend/src/MainBlock/Artifacts/DependencyItems.js
> +            {dependencies && dependencies.map(dependency => (
По идее, если у тебя в `defaultProps` указано, что `dependencies: []`, то вот это условие `dependencies && ` всегда будет выполняться

2019-05-28 19:54 UTC, gooverdian requested changes
из ArtifactListItem.js получилась неплохая обертка, нельзя ли ее применить к тому компоненту, из которого ты сделал эти два?

в остальном стало лучше, но кое-что точно нужно поправить

2019-05-28 19:54 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/Artifacts.js
> +                    {' '}
пробел вполне можно объединить с надписью Artifacts

2019-05-28 19:54 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/ArtifactListItem.js
> +
?

2019-05-28 19:54 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/ArtifactRepositoryItem.js
> +        marginLeft: '60px',
этот стиль дублируется, надо вынести

2019-05-28 19:54 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/Artifacts.js
> +    return (
это и условие для проверки artifactTree можно удалить, ты теперь проверяешь тоже самое внутри

2019-05-28 19:54 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/Artifacts.js
> +    }
так лучше )

2019-05-28 19:54 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/Artifacts.js
> +    );
Ксения предложила отличный вариант

2019-05-28 19:54 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/DependencyItems.js
> +    root: {
этот класс тоже дублируется

2019-05-30 18:04 UTC, Afftobus reviewed
Да, было бы круто обернуть и relations, но там немного по-другому устроен компонент. 
исходя из того, что у нас поджимает время, я бы не стал заморачиваться над этим сейчас

2019-05-30 18:04 UTC, Afftobus commented on frontend/src/MainBlock/Artifacts/Artifacts.js
> +    return (
тупо забыл убрать...

2019-05-30 18:04 UTC, Afftobus commented on frontend/src/MainBlock/Artifacts/Artifacts.js
> +                    {' '}
это так eslint  пофиксил. 
делаю всё текстом

2019-05-30 18:51 UTC, gooverdian reviewed
Несколько минорных замечаний

2019-05-30 18:51 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/Artifacts.js
> +        fetchArtifactTree();
чтобы не перегружать сервак, сюда можно добавить проверку
```suggestion
        !artifactTree && fetchArtifactTree();
```

2019-05-30 18:51 UTC, gooverdian commented on frontend/src/MainBlock/Artifacts/Artifacts.js
> +                {'Artifacts '}
а этот пробел тут, кстати, ваще зачем?

2019-05-30 18:51 UTC, gooverdian commented on frontend/src/redux/models/Artifact/artifactsActions.js
> +        ));
лучше в одну строку

2019-05-30 18:52 UTC, K-ksenia approved these changes

2019-05-30 19:10 UTC, gooverdian approved these changes

2019-05-30 19:31 UTC, merged