Back 42 Coverage Loader
hhru/hh-dep-monitoring pull request #53
Opened 2019-05-27 08:35 UTC by SuhoyVasya

2019-05-27 12:32 UTC, Afftobus reviewed
а зачем нам нужны разные DTO`шки для покрытия из разных источников?
у нас же Entity всё равно универсальные будут..

2019-05-27 12:32 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/SyncService.java
> +    @Scheduled(initialDelay = 2 * 60 * 1000L, fixedDelay = 15 * 60 * 1000L)
а тут точно должны быть магические цифры?
мож их куда-то в настройки вынести?

2019-05-27 12:34 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/SyncService.java
> +    @Scheduled(initialDelay = 2 * 60 * 1000L, fixedDelay = 15 * 60 * 1000L)
Дтошки разные потому что из разных источников приходят разные ЖСОНы.
Числа можно и вынести. Они сейчас везде одинаковые.

2019-05-27 13:16 UTC, colorbash requested changes

2019-05-27 13:16 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/coveragesourceimpl/SonarCloudCoverageSource.java
> +    private final String sonarURI = "sonarcloud.io/api/measures/component";
sonarURI -> static SONAR_URI

2019-05-27 13:16 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/coveragesourceimpl/SonarCloudCoverageSource.java
> +        return Float.NaN;
может исключение кидать?

2019-05-27 13:16 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/CoverageLoader.java
> +    private void loadCoverageFromSource(Repository repository, RepositoryLink link) {
Transactional не дружит с private

2019-05-27 13:16 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/CoverageLoader.java
> +    public CoverageLoader(RepositoryDao repositoryDao, CoverageDao coverageDao, RepositoryLinkDao repositoryLinkDao) {
мы инжект над конструктором не пишем?

2019-05-27 13:16 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/CoverageDaoImpl.java
> +                .setMaxResults(1)
setMaxResults нужон если uniqueResultOptional и так?

2019-05-27 14:56 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/CoverageDaoImpl.java
> +                .setMaxResults(1)
убрал

2019-05-27 14:56 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/CoverageLoader.java
> +    public CoverageLoader(RepositoryDao repositoryDao, CoverageDao coverageDao, RepositoryLinkDao repositoryLinkDao) {
не пишем

2019-05-27 14:56 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/CoverageLoader.java
> +    private void loadCoverageFromSource(Repository repository, RepositoryLink link) {
поменял на public

2019-05-27 14:56 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/coveragesourceimpl/SonarCloudCoverageSource.java
> +    private final String sonarURI = "sonarcloud.io/api/measures/component";
Поменял

2019-05-27 14:56 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/coveragesourceimpl/SonarCloudCoverageSource.java
> +        return Float.NaN;
переделал под исключения

2019-05-28 16:21 UTC, colorbash approved these changes

2019-05-29 07:19 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/CoverageDao.java
> +    Optional<Coverage> findLastForRepositoryByType(long id, CoverageSourceType type);
только лучше не просто id, а repositoryId

Причем в impl у тебя именно так и называется

2019-05-29 07:19 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/CoverageDaoImpl.java
> +                .uniqueResultOptional();
исключение же будет, если больше, чем 1 результат.
Надо тогда где-нибудь явно лимит проставить

2019-05-29 07:19 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/coverage/SonarCloudCoverageDto.java
> +    public SonarCloudCoverageDto() {
если нет других конструкторов, то дефолтный объявлять не обязательно

2019-05-29 07:19 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/Coverage.java
> +    public Coverage(LocalDateTime analizeTime, @NotNull CoverageSourceType sourceType, Long repositoryId, Float coverage) {
тут нужно использовать `@Nonnull` а не `@NotNull`
вторая аннотация используется именно для валидации, а первая для обозначения контракта

2019-05-29 07:19 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/CoverageLoader.java
> +    private void loadCoverageFromSonarCloud(Repository repository, RepositoryLink link) {
только это не тут должно быть, а в `SonarCloudCoverageSource`

2019-05-29 11:25 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/CoverageDao.java
> +    Optional<Coverage> findLastForRepositoryByType(long id, CoverageSourceType type);
исправил

2019-05-29 11:25 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/CoverageDaoImpl.java
> +                .uniqueResultOptional();
добавил setMaxResults

2019-05-29 11:25 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/coverage/SonarCloudCoverageDto.java
> +    public SonarCloudCoverageDto() {
убрал

2019-05-29 11:25 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/Coverage.java
> +    public Coverage(LocalDateTime analizeTime, @NotNull CoverageSourceType sourceType, Long repositoryId, Float coverage) {
я ее вообще убрал

2019-05-29 11:25 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/service/loaders/CoverageLoader.java
> +    private void loadCoverageFromSonarCloud(Repository repository, RepositoryLink link) {
переместил

2019-05-31 06:32 UTC, alinkov approved these changes
Апрув поставил. Но замечания можешь поправить

2019-05-31 06:32 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    @Transactional
где не нужно, лучше ставить транзакции на чтение

2019-05-31 06:32 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/service/loaders/coveragesourceimpl/SonarCloudCoverageSourceTest.java
> +        assertTrue(covereage == 10.0f);
скорее всего падать будет иногда.
Есть assertEquals который дельту принимает

2019-05-31 06:32 UTC, alinkov commented on hh-dep-monitoring-service/src/etc/service.properties
> +sonarCloud.link=https://sonarcloud.io/api/measures/component
перенос

2019-05-31 06:32 UTC, alinkov commented on hh-dep-monitoring-service/src/test/resources/coverage.json
> +}
и тут перенос

2019-05-31 08:47 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/etc/service.properties
> +sonarCloud.link=https://sonarcloud.io/api/measures/component
поставил

2019-05-31 08:47 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/service/loaders/coveragesourceimpl/SonarCloudCoverageSourceTest.java
> +        assertTrue(covereage == 10.0f);
поменял на assertEquals

2019-05-31 08:47 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/utils/DBUtils.java
> +    @Transactional
Добавил readonly

2019-05-31 08:47 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/test/resources/coverage.json
> +}
добавил

2019-05-31 08:59 UTC, merged