Front 20 Add repository search and sorting
hhru/hh-dep-monitoring pull request #55
Opened 2019-05-28 21:20 UTC by K-ksenia

Добавлена строка поиска по имени репозитория и возможность сортировки по следующим полям: name, createdAt, updatedAt, repositoryType.
Порядок сортировки определяется порядком нажатия на поле с атрибутом сортировки. 
У каждого поля есть 3 состояния: 
1) не участвует в сортировке
2) сортировать по возрастанию
3) сортировать по убыванию
При нажатии на поле состояние переходит в следующее за текущим
<img width="1440" alt="Снимок экрана 2019-05-28 в 23 55 09" src="https://user-images.githubusercontent.com/18597504/58512688-62950b80-81a6-11e9-9e3f-645bb7d1c621.png">
<img width="1440" alt="Снимок экрана 2019-05-28 в 23 55 27" src="https://user-images.githubusercontent.com/18597504/58512694-64f76580-81a6-11e9-976f-34e3f96fe09d.png">
<img width="1440" alt="Снимок экрана 2019-05-28 в 23 55 41" src="https://user-images.githubusercontent.com/18597504/58512700-6759bf80-81a6-11e9-8a58-ee0814e72998.png">
<img width="1440" alt="Снимок экрана 2019-05-29 в 0 04 08" src="https://user-images.githubusercontent.com/18597504/58512712-6cb70a00-81a6-11e9-8729-fb978a45cc50.png">

2019-05-29 07:27 UTC, alinkov commented on frontend/src/redux/models/Repository/repositoriesActions.js
> +        const searchParam = searchString === '' ? searchString : `&searchString=${searchString}`;
а `orderParams` в нормальном виде приходят?

2019-05-29 07:27 UTC, alinkov commented on frontend/src/MainBlock/Repositories/FetchingParams.js
> +        marginBottom: '10px',
может это лучше в `rem` считать?

2019-05-29 07:27 UTC, alinkov commented on frontend/src/MainBlock/Repositories/SortingAttributes.js
> +            i + 1 !== availableStates.length
тут лучше if сделать
как-то не очень тернарный оператор подходит

2019-05-29 10:48 UTC, gooverdian requested changes

2019-05-29 10:48 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/SortingAttributes.js
> +    for (let i = 0; i < availableStates.length; i++) {
все прям гораааздо проще
```
const currentStateIndex = availableStates.indexOf(currentState);
return availableStates[(currentStateIndex + 1) % availableStates.length];
```

2019-05-29 10:48 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/SortingAttributes.js
> +        sortOrder.forEach((attributesName) => {
я бы отдавал отсюда объект, а урл формировал либо в редьюсере, либо в родителе

2019-05-29 10:48 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/SortingAttributes.js
> +    };
нужны подробности про этот компонент, выглядит сложно, написал в слаке

2019-05-29 10:48 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/SortingAttribute.js
> +                onClick={() => handleClick(name)}
при каждом обновлении компонента, будет создаваться новая функция, так неправильно, нужно вынести ее в константу и вызывать именем

2019-05-29 10:48 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/SortingAttributes.js
> +        setOrderString(orderString);
при каждом клике будет уходить новый фетч, чтобы отсортировать по убыванию по двум столбцам, серверу придется ответить на 5 запросов, может, подумать над кнопкой "Применить"?

2019-05-29 12:03 UTC, gooverdian reviewed
еще немного нашлось

2019-05-29 12:03 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/Repositories.js
> +        fetchRepositoriesPage(perPage, event.target.value, orderString);
кажется, это не нужно, потому что сработает эффект

2019-05-29 12:03 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/Repositories.js
> +        fetchRepositoriesPage(perPage, searchString, newString, page);
и тут можно вместо этого вызвать setPage(0);

2019-05-29 12:16 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/SortingAttributes.js
> +    for (let i = 0; i < availableStates.length; i++) {
или даже так
```
const getNextState = (currentState) => availableStates[
    (availableStates.indexOf(currentState) + 1) % availableStates.length
];
```

2019-05-30 19:53 UTC, K-ksenia reviewed
<img width="1057" alt="Снимок экрана 2019-05-30 в 22 50 46" src="https://user-images.githubusercontent.com/18597504/58660229-a36b5c80-832d-11e9-98df-23c737c4a08c.png">
<img width="1056" alt="Снимок экрана 2019-05-30 в 22 50 56" src="https://user-images.githubusercontent.com/18597504/58660233-a6fee380-832d-11e9-95e6-7561a102149a.png">

2019-05-30 19:53 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/Repositories.js
> +        fetchRepositoriesPage(perPage, event.target.value, orderString);
Сработает, но только если текущая страница не нулевая

2019-05-30 19:53 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/Repositories.js
> +        fetchRepositoriesPage(perPage, searchString, newString, page);
тоже не подходит для случая, когда page уже 0

2019-05-30 19:53 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/SortingAttribute.js
> +                onClick={() => handleClick(name)}
Вынесла, спасибо

2019-05-30 19:53 UTC, K-ksenia commented on frontend/src/redux/models/Repository/repositoriesActions.js
> +        const searchParam = searchString === '' ? searchString : `&searchString=${searchString}`;
Да, строку формирую еще в компоненте

2019-05-30 19:53 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/SortingAttributes.js
> +        sortOrder.forEach((attributesName) => {
Чуток переделала

2019-05-30 19:53 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/SortingAttributes.js
> +    for (let i = 0; i < availableStates.length; i++) {
Я чувствовала, что простое решение где-то рядом

2019-05-30 19:53 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/SortingAttributes.js
> +        setOrderString(orderString);
Сделала в итоге фетч при выходе из меню

2019-05-31 06:32 UTC, alinkov approved these changes

2019-05-31 09:01 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/FetchingParams/FetchingParams.js
> +    const handleClose = () => {
```suggestion
    const handleSortMenuClose = () => {
```
Кажется, такое имя будет более подходящим, потому как мы не весь компонент закрываем

2019-05-31 09:01 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/FetchingParams/SortingAttributes.js
> +            }
Хоба, и вместо 3O(n) у нас теперь 1O(n). Если такой вариант не нравится, то хотя бы нужно поменять `Object.assign` на `...rest`, потому что у тебя массив, нечего с ним общаться, как будто он объект (хотя, конечно, он объект, но все равно).
```
const attributeSortIndex = sortedAttributes.findIndex(item => item.name === attributeName);
const newSortOrder = [...sortedAttributes];

if (newState && attributeSortIndex === -1) {
    // Сортировка есть, атрибута нет - добавляем
    newSortOrder.push(getAttribute(attributeName));
}

if (attributeSortIndex !== -1) {
    if (newState) {
        // Сортировка есть, атрибут есть - обновляем
        newSortOrder[attributeSortIndex] = getAttribute(attributeName);
    } else {
        // Сортировки нет, атрибут есть - удаляем
        newSortOrder.splice(attributeSortIndex, 1);
    }
}
// Сортировки нет, атрибута нет - ничего не делаем

setSortedAttributes(newSortOrder);
```

Подробно про копирование массивов https://www.samanthaming.com/tidbits/35-es6-way-to-clone-an-array

2019-05-31 09:01 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/Repositories.js
> +    };
Мне все равно кажется, не очень хорошим решением, что компонент что-то знает, о том, как будут получены данные, и кажется, что урл нужно формировать в редьюсере или модели. Но можно оставить, если тебе думается по-другому.

2019-05-31 11:26 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/FetchingParams/FetchingParams.js
> +    const handleClose = () => {
Да, спасибо

2019-05-31 11:26 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/FetchingParams/SortingAttributes.js
> +            }
😍 красота! Аж полегчало
Спасибо, почитаю

2019-05-31 11:26 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/Repositories.js
> +    };
Да я согласна, просто хотелось поскорее
Перенесла формирование строки в fetchRepositoriesPage

2019-05-31 11:40 UTC, gooverdian approved these changes
Все ок, из-за спешки и невнимательности пропустил передачу GET параметров в axios, но сейчас уже будет много изменений

2019-05-31 11:40 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/FetchingParams/SortingAttributes.js
> +        if (!Object.prototype.hasOwnProperty.call(sortAttributes, attributeName)) {
```suggestion
        if (!sortAttributes[attributeName]) {
```
Это IDEA так посоветовала?

2019-05-31 11:40 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/FetchingParams/SortingAttributes.js
> +                // Сортировка есть, атрибут есть - обновляем
можно оставить, но вроде, и без него понятно, это я просто для того, чтобы следить за ходом мысли

2019-05-31 14:23 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/FetchingParams/SortingAttributes.js
> +                // Сортировка есть, атрибут есть - обновляем
Поспешила
Убрала

2019-05-31 14:23 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/FetchingParams/SortingAttributes.js
> +        if (!Object.prototype.hasOwnProperty.call(sortAttributes, attributeName)) {
Исправила

2019-05-31 14:30 UTC, merged