back-45 Add bamboo resource
hhru/hh-dep-monitoring pull request #56
Opened 2019-05-30 10:37 UTC by anickishin

2019-05-30 12:27 UTC, SuhoyVasya approved these changes

2019-05-30 17:56 UTC, colorbash requested changes

2019-05-30 17:56 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/BambooResource.java
> +    public void syncBambooWithOwnLink(String bambooLink) {
а что мешает нам читать bambooLink из конфига как раньше? или хотя бы если она не пришла то брать из конфига?

2019-05-31 06:33 UTC, alinkov approved these changes

2019-06-03 06:00 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/BambooResource.java
> +    public void syncBambooWithOwnLink(String bambooLink) {
старый способ остался. В этом же ресурсе есть @Path("/sync"), который берёт bambooLink из конфига.

2019-06-03 07:19 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/BambooResource.java
> +    public void syncBambooWithOwnLink(String bambooLink) {
ну можно было просто добавить  bambooLink в "/sync"), а если не пришло то брать из конфига

2019-06-03 07:19 UTC, colorbash approved these changes

2019-06-03 07:21 UTC, merged