Front 14 Add repository type
hhru/hh-dep-monitoring pull request #59
Opened 2019-06-01 21:21 UTC by K-ksenia

Добавлено отображение типа репозитория и возможность его редактирования
<img width="1440" alt="Снимок экрана 2019-06-02 в 0 12 13" src="https://user-images.githubusercontent.com/18597504/58753694-288c7800-84cc-11e9-8422-b8c32a419631.png">
<img width="1440" alt="Снимок экрана 2019-06-02 в 0 12 24" src="https://user-images.githubusercontent.com/18597504/58753698-37732a80-84cc-11e9-967d-a0d91cd71e86.png">
<img width="1440" alt="Снимок экрана 2019-06-02 в 0 12 36" src="https://user-images.githubusercontent.com/18597504/58753699-38a45780-84cc-11e9-8e69-4eb5b0f1575d.png">

2019-06-02 10:27 UTC, gooverdian requested changes
Вполне неплохо, есть пара мелких моментов

2019-06-02 10:27 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/ListItemInfo.js
> +    description: PropTypes.string.isRequired,
как-то странно, ты пишешь здесь required, а потом сама же пытаешься обойти это присылая пустую строку, может, просто убрать required?

2019-06-02 10:27 UTC, gooverdian commented on frontend/src/MainBlock/Repositories/RepositoryItem.js
> +                    description={repository.description === null ? '' : repository.description}
и если там не будет required, то тут не понадобится тернарник

2019-06-02 10:27 UTC, gooverdian commented on frontend/src/MainBlock/RepositoryType/RepositoryTypeLabel.js
> +            icon={<TypeIcon className={classes.chipIcon} />}
хорошая идея

2019-06-02 10:27 UTC, gooverdian commented on frontend/src/redux/models/Repository/repositoriesReducer.js
> +        Object.keys(newState.pages).forEach((page) => {
может, some? а то если мы его найдем на первой странице, все дальнейшие действия бессмысленны

2019-06-02 10:27 UTC, gooverdian commented on frontend/src/MainBlock/RepositoryType/OpenFormButton.js
> +function OpenFormButton({ classes, repository, repositoryTypes, fetchRepositoryTypes, editRepositoryType }) {
TypesMenuButton?

2019-06-02 11:36 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/ListItemInfo.js
> +    description: PropTypes.string.isRequired,
Пустую строку присылали, потому что иначе он null так и выводил (вот тут скриншотики и исправление https://github.com/hhru/hh-dep-monitoring/pull/35)
Хотя сейчас, если я убираю условие на `null` и передаю всегда `description` (без всяких пустых строк) почему-то он не выводит этот `null`, а все нормально отображается🤔

2019-06-02 11:36 UTC, K-ksenia commented on frontend/src/MainBlock/RepositoryType/OpenFormButton.js
> +function OpenFormButton({ classes, repository, repositoryTypes, fetchRepositoryTypes, editRepositoryType }) {
ой, да
спасибо

2019-06-02 11:36 UTC, K-ksenia commented on frontend/src/MainBlock/RepositoryType/RepositoryTypeLabel.js
> +            icon={<TypeIcon className={classes.chipIcon} />}
😊

2019-06-02 11:36 UTC, K-ksenia commented on frontend/src/redux/models/Repository/repositoriesReducer.js
> +        Object.keys(newState.pages).forEach((page) => {
Исправила на some

2019-06-02 11:36 UTC, K-ksenia commented on frontend/src/MainBlock/Repositories/RepositoryItem.js
> +                    description={repository.description === null ? '' : repository.description}
исправила

2019-06-03 05:38 UTC, gooverdian approved these changes

2019-06-03 07:50 UTC, Afftobus approved these changes

2019-06-03 11:57 UTC, merged