Front 1
hhru/hh-dep-monitoring pull request #6
Opened 2019-03-02 21:24 UTC by SuhoyVasya

add modules: header, current troubles, about service, feature overview.

2019-03-03 06:45 UTC, alinkov commented
Давай сделаем для фронтенда maven модуль.
А в самом модуле добавим plugin
frontend-maven-plugin

И всю сборку можно будет запускать через maven

2019-03-03 11:02 UTC, K-ksenia requested changes

2019-03-03 11:02 UTC, K-ksenia commented on frontend/src/Header/Header.js
> +                </div>
Вот этот код можно чем-то таким заменить
```
function Navbar(props) {
    return (
        <div className="navbar_block">
            {this.props.navbarItems.map(item => (
                <div className="navbar_element navbar_button">
                    <a key={item} name={item}>{item}</a>
                </div>
            ))}
        </div>
    );
}
```
и в эту функцию передавать параметр `navbarItems`, который в данном случае равен `["Feed", "Search", "Repositories", "Ratings", "Users", "Troubles", "About"]`

2019-03-03 11:08 UTC, alinkov requested changes
Очень много лишних стилей.
Надо бы их привести в порядок.
Для этого можно заиспользовать какую-нибудь библиотечку (лучше всего блоко)

И может быть стоит подумать в сторону less?

2019-03-03 11:08 UTC, alinkov commented on frontend/pom.xml
> +</project>
новую строчку добавь

2019-03-03 11:08 UTC, alinkov commented on frontend/yarn.lock
> +yarn@^1.13.0:
этот файл вроде как в .gitignore должен быть
надо бы выпилить

2019-03-03 11:08 UTC, alinkov commented on frontend/src/Footer.js
> +}
тут тоже символ переноса

2019-03-03 11:08 UTC, alinkov commented on frontend/src/Header/Header.css
> +    font-size:12px;
размеры шрифтов лучше в отдельный класс

2019-03-03 11:08 UTC, alinkov commented on frontend/src/Header/Header.js
> +        console.log(event.target.value);
это не надо оставлять

2019-03-03 11:08 UTC, alinkov commented on frontend/src/Header/Header.css
> +.bloko-icon {
давай лучше bloko как зависимость прикрутим и большую часть стилей выпилим

2019-03-03 11:08 UTC, alinkov commented on frontend/src/MainBlock/MainBlock.css
> +
зачем так много переносов?

2019-03-03 15:12 UTC, SuhoyVasya commented on frontend/src/Header/Header.js
> +                </div>
да, я переделаю. Встречный вопрос - это все описывает кнопки. им можно дать либо ссылки либо onClick. Как по-твоему лучше?

2019-03-04 06:35 UTC, SuhoyVasya commented on frontend/src/MainBlock/MainBlock.css
> +
убрал

2019-03-04 06:35 UTC, SuhoyVasya commented on frontend/src/Header/Header.js
> +        console.log(event.target.value);
убрал

2019-03-04 06:36 UTC, SuhoyVasya commented on frontend/src/Footer.js
> +}
убрал файл. Он не используется

2019-03-04 06:45 UTC, SuhoyVasya commented on frontend/pom.xml
> +</project>
добавил

2019-03-04 06:46 UTC, SuhoyVasya commented on frontend/src/Header/Header.js
> +                </div>
сделал пока просто массив имен

2019-03-04 06:51 UTC, SuhoyVasya commented on frontend/yarn.lock
> +yarn@^1.13.0:
выпилил

2019-03-04 11:30 UTC, gooverdian requested changes
В целом нормально
Есть много вопросов по компоновке и стилям
Сам JS код пока не смотрел, желательно раскидать компоненты по разным файлам - так будет проще

2019-03-04 11:30 UTC, gooverdian commented on frontend/src/App.css
> +body{
можно добавить normalizr для margin и padding

2019-03-04 11:30 UTC, gooverdian commented on frontend/pom.xml
> +</project>
Пустая строка в конце файла обязательна, почти все IDE могут ставить ее автоматически при сохранении, достаточно в настройках это указать

2019-03-04 11:30 UTC, gooverdian commented on frontend/src/Header/Header.css
> +.footer{
Почему правила футера в header.css ?

2019-03-04 11:30 UTC, gooverdian commented on frontend/src/Header/Header.css
> +.header_bars_wrapper{
Нужно называть классы по БЭМ, для блоков разделителем является дефис (`header-bars-wrapper`)
Разделитель между блоком и элементом - два андерскора (например `header-bars__item`)
Разделитель между блоком/элементом и модификатором - один андерскор (например `header-bars__item_attractive`)
Это касается всего этого файла
После названия обязателен пробел
Для соблюдения этих правил можно настроить stylelint

Также, очень удобно разделить блоки по разным файлам и импортить их (нужен LESS)

2019-03-04 11:30 UTC, gooverdian commented on frontend/src/Header/Header.css
> +    font-size:12px;
Тут зависит от того, будет ли это еще использоваться - если это общая вещь, которую используют куча разных блоков - лучше вынести в отдельный файл variables.less (опять же нужен LESS)

2019-03-04 11:30 UTC, gooverdian commented on frontend/src/Header/Header.js
> +        console.log(event.target.value);
Кажется, console.log так и остался

2019-03-04 11:30 UTC, gooverdian commented on frontend/src/Header/Header.js
> +function MainIcon(){
Нужно вынести каждый компонент в отдельный файл, когда они обрастут логикой - это будет гораздо удобнее, чем файл на 100 строк

2019-03-04 11:30 UTC, gooverdian commented on frontend/src/Header/Header.js
> +                </div>
Весь этот компонент можно рендерить одним циклом, который будет перебирать массив, содержащий названия

2019-03-04 11:30 UTC, gooverdian commented on frontend/src/MainBlock/MainBlock.css
> +.mainblock_wrapper{
Все, что я говорил в предыдущем CSS файле

2019-03-04 11:30 UTC, gooverdian commented on frontend/src/MainBlock/MainBlock.css
> +}
Все же нужно как-то автоматом или вручную ставить пустую строку в конец

2019-03-04 11:30 UTC, gooverdian commented on frontend/src/Header/Header.css
> +    background-color:red;
Лучше всегда и везде использовать HEX или rgba

2019-03-04 11:30 UTC, gooverdian commented on frontend/src/MainBlock/MainBlock.js
> +/*здесь костыль - поле в props еще и имя css класса*/
Таких комментов не должно быть в коде

2019-03-04 11:33 UTC, gooverdian commented
Еще общий комментарий: больше коммитов - лучше - после ревью их можно засквошить, если это критично, но во время ревью гораздо проще смотреть код, разделенный по смыслу коммитами

2019-03-04 11:41 UTC, gooverdian commented on frontend/src/MainBlock/MainBlock.css
> +
Нет, не убрал, или не запушил

2019-03-04 12:52 UTC, SuhoyVasya commented on frontend/yarn.lock
> +yarn@^1.13.0:
показалось. работаю

2019-03-04 12:54 UTC, SuhoyVasya commented on frontend/src/MainBlock/MainBlock.css
> +
теперь еще и запушил

2019-03-04 12:55 UTC, SuhoyVasya commented on frontend/src/Header/Header.css
> +.footer{
убрал

2019-03-04 12:56 UTC, SuhoyVasya commented on frontend/pom.xml
> +</project>
добавил пустые строки в конце

2019-03-04 12:56 UTC, SuhoyVasya commented on frontend/src/Header/Header.js
> +        console.log(event.target.value);
убрал

2019-03-04 12:56 UTC, SuhoyVasya commented on frontend/src/Header/Header.js
> +                </div>
изменил на один цикл

2019-03-04 12:56 UTC, SuhoyVasya commented on frontend/src/MainBlock/MainBlock.css
> +}
добавил строку

2019-03-04 12:56 UTC, SuhoyVasya commented on frontend/src/MainBlock/MainBlock.js
> +/*здесь костыль - поле в props еще и имя css класса*/
убрал

2019-03-04 12:57 UTC, SuhoyVasya commented on frontend/src/Header/Header.js
> +function MainIcon(){
разделил компоненты по файлам

2019-03-04 16:28 UTC, gooverdian commented on frontend/yarn.lock
> +yarn@^1.13.0:
обычно, он как раз включается в репу, чтобы гарантировано поставить определенные версии пакетов с помощью `yarn install --frozen-lockfile`

2019-03-05 09:23 UTC, alinkov commented
Еще несколько замечаний по структуре, чтобы сделать нормальный maven проект.
1. Нужно добавить модуль в основной pom.xml. Для этого нужно сделать rebase текущей ветки на master и добавить 2 профиля. `back` и `front`
Например вот так:
```xml
        <profile>
            <id>back</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <modules>
                <module>hh-dep-monitoring-service</module>
            </modules>
        </profile>
        <profile>
            <id>front</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <modules>
                <module>frontend</module>
            </modules>
        </profile>
```

 И поправить профиль `codecoverage`. В него нужно добавить оба модуля
```xml
<modules>
   <module>hh-dep-monitoring-service</module>
   <module>frontend</module>
</modules>
```
2. Нужно следовать положению кода в maven. Т.е. весь код frontend модуля перенести в `src/main/js` или `src/main/webapp`
просто сейчас все получается по сути в корне, а это не очень хорошо.

2019-03-05 09:32 UTC, alinkov requested changes

2019-03-05 09:32 UTC, alinkov commented on frontend/pom.xml
> +                        </configuration>
<phase>process-resources</phase>

2019-03-05 09:32 UTC, alinkov commented on frontend/pom.xml
> +                        </configuration>
Также хорошо бы добавить тесты
```xml
                    <execution>
                        <id>yarn test</id>
                        <goals>
                            <goal>yarn</goal>
                        </goals>
                        <configuration>
                            <arguments>test</arguments>
                        </configuration>
                        <phase>test</phase>
                    </execution>
```

2019-03-06 12:06 UTC, SuhoyVasya commented
![default](https://user-images.githubusercontent.com/45092642/53880181-64c15100-4021-11e9-9af7-a0712dcf49f6.png)

2019-03-06 12:35 UTC, alinkov approved these changes

2019-03-06 19:18 UTC, K-ksenia approved these changes

2019-03-06 21:32 UTC, gooverdian requested changes

2019-03-06 21:32 UTC, gooverdian commented on frontend/src/App.js
> +        <div className="App">
Давайте везде маленькие буквы для классов, и ни к чему классы для которых нет правил

2019-03-06 21:32 UTC, gooverdian commented on frontend/src/Header/MainIcon.js
> +    width:theme.spacing.unit * 9,
здесь и далее, надо определиться, ставишь ты пробел после двоеточия и перед фигурными скобками, или нет, гораздо приятнее читать код, который одинаково скомпонован и стилизован, тоже самое про `function a(){` и `React.Component{`, в стайлгайде пробел ставится.

Это можно не править, это FYI и на будущее

2019-03-06 21:32 UTC, gooverdian commented on frontend/src/Header/MainIcon.js
> +  }
и про запятую после последнего элемента массива или объекта - тоже всегда ставится, если это не JSON, хотя и он тоже уже поддерживает эту штуку

2019-03-06 21:32 UTC, gooverdian commented on frontend/src/Header/Navbar.js
> +    var navbarItems = [
Это `const`. Вообще - всегда старайся использовать const, и отказываться от него, если переменная действительно меняется в процессе выполнения. Ну и эту константу можно вынести из компонента, чтобы он не был ситуативным и одноразовым и, либо расположить рядом со стилями, либо передавать в props компонента откуда-то из родителя.

И раз уж ты пишешь ES6 - то забудь про var, используй let вместо него, только почитай чем они отличаются.

2019-03-06 21:32 UTC, gooverdian commented on frontend/src/Header/Header.js
> +export default class Header extends Component {
Используя Component, ты будешь вызывать новый render каждый раз, при изменении любых props компонента или его детей, советую использовать PureComponent везде, где для одинаковых пропс всегда одинаковый результат.

Почитать про отличия между ними можно вот тут: https://reactjs.org/docs/react-api.html#reactcomponent

2019-03-06 21:32 UTC, gooverdian commented on frontend/src/Header/Navbar.js
> +function Navbar(props) {
Функциональные компоненты - это хорошо, react потихоньку как раз отказывается от классовых компонентов и переходит к функциональным, аналогом PureComponent для функционального компонента является React.memo. Можно, кстати, вообще все сделать функциональными, и использовать реакт хуки, но настаивать не буду.

2019-03-06 21:32 UTC, gooverdian commented on frontend/src/Header/UserBlock.js
> +        var piclink="https://avatars.githubusercontent.com/"+account.accountName;
const

2019-03-06 21:32 UTC, gooverdian commented on frontend/src/MainBlock/Repositories.js
> +var repositories=[
const. И еще, непонятно, почему оно тут, а не наверху

2019-03-06 21:32 UTC, gooverdian commented on frontend/src/MainBlock/MainBlock.js
> +    const { classes } = this.props;
отступ, и чтобы не возникало таких комментов - можно установить eslint

2019-03-06 21:32 UTC, gooverdian commented on frontend/src/Header/UserBlock.js
> +    }
отступ

2019-03-06 21:32 UTC, gooverdian commented on frontend/src/Header/MainIcon.js
> +class MainIcon extends React.Component{
не похоже на Icon =)

2019-03-06 21:32 UTC, gooverdian commented on frontend/src/MainBlock/Repositories.js
> +                            <ListItemText primary={repo.comitterName+"/"+repo.repoName}/>
можно использовать templateString 
```
`${repo.comitterName}/${repo.repoName}`
```

2019-03-06 21:32 UTC, gooverdian commented on frontend/src/Header/Navbar.js
> +    ]
;

2019-03-07 07:15 UTC, SuhoyVasya commented on frontend/src/App.js
> +        <div className="App">
класс был лишним. убрал

2019-03-07 07:17 UTC, SuhoyVasya commented on frontend/src/Header/MainIcon.js
> +    width:theme.spacing.unit * 9,
поправил

2019-03-07 07:18 UTC, SuhoyVasya commented on frontend/src/Header/MainIcon.js
> +  }
добавил

2019-03-07 07:19 UTC, SuhoyVasya commented on frontend/src/Header/Navbar.js
> +    var navbarItems = [
поменял на const

2019-03-07 07:19 UTC, SuhoyVasya commented on frontend/src/Header/Header.js
> +export default class Header extends Component {
по подсказкам ESLint все сделал на функциональных компонентах

2019-03-07 07:20 UTC, SuhoyVasya commented on frontend/src/Header/Navbar.js
> +function Navbar(props) {
не менял

2019-03-07 07:21 UTC, SuhoyVasya commented on frontend/src/Header/UserBlock.js
> +        var piclink="https://avatars.githubusercontent.com/"+account.accountName;
исправил

2019-03-07 07:21 UTC, SuhoyVasya commented on frontend/src/MainBlock/Repositories.js
> +var repositories=[
исправил и переместил

2019-03-07 07:21 UTC, SuhoyVasya commented on frontend/src/MainBlock/MainBlock.js
> +    const { classes } = this.props;
устанвил eslint и прошелся по проекту eslint --fix'ом

2019-03-07 07:22 UTC, SuhoyVasya commented on frontend/src/Header/UserBlock.js
> +    }
eslint их отформатировал

2019-03-07 07:22 UTC, SuhoyVasya commented on frontend/src/Header/MainIcon.js
> +class MainIcon extends React.Component{
не понимаю суть вопроса. Я неправильно назвал компонент?

2019-03-07 07:22 UTC, SuhoyVasya commented on frontend/src/MainBlock/Repositories.js
> +                            <ListItemText primary={repo.comitterName+"/"+repo.repoName}/>
eslint сам исправил

2019-03-07 07:23 UTC, SuhoyVasya commented on frontend/src/Header/Navbar.js
> +    ]
добавил

2019-03-07 09:34 UTC, gooverdian approved these changes
Все ок, есть минорные комменты

Ну и плюс надо в eslint поставить отступ в 4 пробела, а не в два, так будет привычнее

2019-03-07 09:34 UTC, gooverdian commented on frontend/.eslintrc.js
> +};
потерялась пустая строка

2019-03-07 09:34 UTC, gooverdian commented on frontend/src/MainBlock/Repositories.js
> +                    Repositories
Странный отступ в строке, в нем есть смысл?

2019-03-07 09:34 UTC, gooverdian commented on frontend/src/MainBlock/Repositories.js
> +function ListItemLink(props) {
Пока терпимо тут, но потом лучше вынести в другой файл

2019-03-07 09:34 UTC, gooverdian commented on frontend/src/Header/MainIcon.js
> +            dm
Странный отступ

2019-03-07 09:34 UTC, gooverdian commented on frontend/src/Header/MainIcon.js
> +    height: theme.spacing.unit * 9,
Пока мало файлов - ок, но потом лучше вынести повторяющиеся значения в отдельный файл и брать их оттуда - это удобно

2019-03-09 12:47 UTC, merged