back-2 Added Github integration
hhru/hh-dep-monitoring pull request #7
Opened 2019-03-04 09:09 UTC by anickishin

2019-03-04 09:24 UTC, SuhoyVasya reviewed
Раз уж используешь отдельно классы Repository и GHRepository лучше сделать конструктор Repository(GHRepository repository). тогда и метода repositoryToList будет аккуратней.
В классе Repository почему repositoryId имеет тип Long а не long?
 Кстати как комменты к отдельным файлам вставлять?

2019-03-04 10:28 UTC, SuhoyVasya requested changes

2019-03-04 10:28 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/github/Repository.java
> +    public Long getRepositoryId() {
почему Long а не long?

2019-03-04 10:28 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/github/Repository.java
> +
добавь конструктор public Repository(GHRepository repository)

2019-03-04 10:28 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/GithubIntegration.java
> +    }
return repositoryMap.values().stream().map(Repository::new).collect(Collectors.toList());

2019-03-04 10:32 UTC, SuhoyVasya approved these changes

2019-03-04 12:44 UTC, alinkov requested changes

2019-03-04 12:44 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/Main.java
> +    for (int i = 0; i < args.length; i++) {
Как-то не очень.
Бери из системных свойств

2019-03-04 12:44 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/GithubIntegration.java
> +public class GithubIntegration {
Сделай бином.
И давай название поменяем

2019-03-04 12:44 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/GithubIntegration.java
> +        if (oauth !=null) {
Блин, похоже checkstyle отвалился.
После != нужен пробел

2019-03-04 12:44 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/GithubIntegration.java
> +        return organization.getRepositories().values().stream().map(Repository::new).collect(Collectors.toList());
Разнеси на несколько строчек

2019-03-04 14:33 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +  GithubLoader githubLoader() {
Так. Давай немного по-другому сделаем.

Вот так можно сделать CommonConfig
```java
@Configuration
@Import({
    GithubLoader.class,
    Resource.class
})
public class CommonConfig {
  @Bean
  protected String oauthToken(FileSettings fileSettings) {
    return Optional.ofNullable(System.getProperty("github-oauth"))
        .orElseGet(() -> fileSettings.getString("github.oauth"));
  }
}
```

Потом в GithubLoader добавляешь аннотации `@Named` и `@Singleton`
И делаешь один конструктор 
```java
    public GithubLoader(String oauthToken) {
        this.oauthToken = oauthToken;
    }
```

P.S. над Resource тоже надо будет поставить `@Named` и `@Singleton`

2019-03-05 08:52 UTC, alinkov requested changes

2019-03-05 08:52 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
```java
  private final FileSettings fileSettings;
  private final String serviceName;
  private final AppMetadata appMetadata;

  @Inject
  public CommonConfig(FileSettings fileSettings, String serviceName, AppMetadata appMetadata) {
    this.fileSettings = fileSettings;
    this.serviceName = serviceName;
    this.appMetadata = appMetadata;
  }
```
Удали этот кусок. Он не нужен

2019-03-05 08:52 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/GithubLoader.java
> +package ru.hh.school.depmonitoring.utils;
не нравится название пакета.
Не utils это

2019-03-05 08:52 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/GithubLoader.java
> +        return organization.getRepositories()
давай лучше заведем свое исключение.
AppRuntimeException или как-то так

2019-03-05 08:52 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/GithubLoader.java
> +        return organization.getRepositories()
И давай напишем unit-тест на это дело

2019-03-05 16:34 UTC, alinkov requested changes

2019-03-05 16:34 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/GithubLoaderTest.java
> +@Named
это тут не нужно.

2019-03-05 16:34 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/config/TestConfig.java
> +public class TestConfig {
у тебя этот класс бесполезен получается

Нужно сделать какой-то TestBaseClass и в нем этот конфик прописать

2019-03-05 16:34 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/config/TestConfig.java
> +public class TestConfig {
В качестве основы возьми https://github.com/alinkov/test-practice/blob/integration-test/src/test/java/ru/hh/school/test/practice/ExampleResourceTest.java

Там есть еще и конфиг

2019-03-05 16:34 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/loaders/GithubLoader.java
> +            throw new AppRuntimeException("Error on getReposOfOrganization", e, 1);
Давай где-нибудь эти коды хранить. А то просто 1 выглядит магическим числом

2019-03-05 20:45 UTC, colorbash commented on hh-dep-monitoring-service/pom.xml
>  </project>
добавь строку пожлуйста

2019-03-05 20:54 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/exceptions/AppRuntimeException.java
> +    private final int errorCode;
На первый взгляд кажется, что это код ответа сервера, а на деле это код исключительной ситуации.
На мой взгляд это можно заменить Енумом, а еще лучше вообще под каждую исключительную ситуевину делать свое исключение.

2019-03-05 20:57 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/loaders/GithubLoader.java
> +    private String oauthToken;
final ?

2019-03-05 21:01 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/github/Repository.java
> +            createdAt = null;
зачем нулу присваивать если он и так нул?
когда ghRepository.getCreatedAt() кидает исключение, createdAt не успевает присвоить значение правой части, а при инстанции класса createdAt и так нул

2019-03-05 21:58 UTC, colorbash requested changes

2019-03-05 21:58 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/github/Repository.java
> +    public Repository(GHRepository ghRepository) {
Если это дто и потом мы будем его сериализовать, то нужен пустой конструктор.
А вообще не очень кошерно делать конструктор который в себя принимает какой-то тяжелый классец из либы, дто часто шарятся между проектами и в таком варианте его будет сложно зашарить без kohsuke.github.GHRepository, тк он зависит от GHRepository, лучше сделать класс конвертер, или на худой конец статический метод преобразвания, но не конструктор

2019-03-05 22:01 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/GithubLoaderTest.java
> +public class GithubLoaderTest {
что проверяет этот тест?
что GitHub.connectUsingOAuth упадет от пустой строки?
кажется юнит тесты должны проверять свой код

2019-03-06 06:53 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/exceptions/AppRuntimeException.java
> +    private final int errorCode;
лучше enum или список констант.
На каждую ситуацию отдельное исключение, слишком кашерно.
Обычно заводится несколько штук, чтобы понимать на каком уровне ошибка и все

2019-03-06 07:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/exceptions/LoadType.java
> +    Repos
так не именуются енамы
Должно быть `REPOS`

2019-03-06 08:07 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/exceptions/LoadType.java
>  public enum LoadType {
теперь это LoadExceptionType

2019-03-06 12:08 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/GithubLoaderTest.java
> +@ContextConfiguration(classes = TestConfig.class)
это не нужно

2019-03-06 12:08 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/exceptions/LoadExceptionType.java
> +    ORGANIZATION,
такое название не понятно
LoadExceptionType.ORGANIZATION

2019-03-06 12:08 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/GithubLoaderTest.java
> +public class GithubLoaderTest extends NabTestBase {
`extends NabTestBase`
нужно для интеграционных тестов

2019-03-06 12:08 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/GithubLoaderTest.java
> +    private GithubLoader githubLoader;
лучше как-то так
```java
private String token = "TEST_TOKEN";
private GithubLoader githubLoader = new GithubLoader(token);
```

2019-03-07 08:09 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/exceptions/LoadType.java
> +public enum LoadType {
а зачем опять переименовал?

2019-03-07 11:04 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/RepositoryConverter.java
> +            e.printStackTrace();
в лог пиши. 
```java
e.printStackTrace();
```
не используй

2019-03-07 11:04 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/RepositoryConverter.java
> +        } catch (IOException | IllegalStateException e) {
убери `| IllegalStateException`
Если пришло `IllegalStateException` то пусть так и идет дальше

2019-03-07 11:04 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/ProdConfig.java
> +    GithubLoader.class
это в  `CommonConfig`

2019-03-11 06:08 UTC, alinkov requested changes
Поправь замечания и сделай ребейз

2019-03-11 06:08 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/loaders/GithubLoader.java
> +        } catch (NullPointerException e) {
Так с нулом не работают.
Вдруг в другом месте выскочит?
Поэтому нужно явно проверять на null
И не new LinkedList, а лучше просто List.of()

2019-03-11 06:08 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/RepositoryConverter.java
> +            System.out.println("IOException in RepositoryConverter");
В лог

2019-03-11 10:48 UTC, alinkov approved these changes

2019-03-11 14:13 UTC, colorbash requested changes

2019-03-11 14:13 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/github/Repository.java
> +        private long repositoryId;
А в чем прикол? зачем дублировать все поля если можно внутрь запихнуть в билдер только `Repository repository` и уже сеттить ему поля, а в build() вернуть this.repositorу?

2019-03-11 14:13 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/github/Repository.java
> +        private RepositoryBuilder() {
дефолтный пустой конструктор есть и так, если ты не обьявляешь конструктор с параметрами

2019-03-11 14:13 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/github/Repository.java
> +public class Repository implements Serializable {
если мы будем этот класс десериализовать то нужны сеттеры

2019-03-11 14:13 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/GHConverter.java
> +    private GHConverter() {}
перенос строчки нужен

2019-03-11 14:13 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/GithubLoaderTest.java
> +    private String token = "TEST_TOKEN";
private static final String TOKEN = 
константы обычно так обьявляются

2019-03-11 14:13 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/GithubLoaderTest.java
> +        assertEquals(0, repositoryList.size());
assertThat("assert test text", !repositoryList.isEmpty());

2019-03-11 14:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/github/Repository.java
> +        private long repositoryId;
чтобы поля были final. Специально так сделано

2019-03-11 14:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/github/Repository.java
> +        private RepositoryBuilder() {
так тут приватный

2019-03-11 14:22 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dto/github/Repository.java
> +public class Repository implements Serializable {
для final полей сеттеры не получится

2019-03-11 14:23 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/GHConverter.java
> +    private GHConverter() {}
на самом деле спорный момент.
Я тоже за вариант с добавлением переноса, но много кто против.
Поэтому хорошо бы определиться, как будем делать

2019-03-11 14:44 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/utils/GHConverter.java
> +    private GHConverter() {}
но сейчас в любом случае 
```java
private RepositoryBuilder() {
}
```
Написано с переносом. Так что хорошо бы сделать единообразно

2019-03-11 14:48 UTC, alinkov commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/GithubLoaderTest.java
> +        assertEquals(0, repositoryList.size());
```java
assertFalse(repositoryList.isEmpty());
```

2019-03-12 17:37 UTC, colorbash approved these changes
ОК! :)

2019-03-12 17:37 UTC, colorbash commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/GithubLoaderTest.java
> +    private final String token = "TEST_TOKEN";
token -> TOKEN - константы обычно в верхнем регистре, не критично но набудущее

2019-03-12 18:11 UTC, colorbash approved these changes

2019-03-12 18:42 UTC, anickishin commented on hh-dep-monitoring-service/src/test/java/ru/hh/school/depmonitoring/GithubLoaderTest.java
> +    private final String token = "TEST_TOKEN";
[ERROR] src\test\java\ru\hh\school\depmonitoring\GithubLoaderTest.java:[25,26] (naming) MemberName: Name 'TOKEN' must match pattern '^[a-z][a-zA-Z0-9]*$'.

2019-03-12 18:43 UTC, merged