Back 6
hhru/hh-dep-monitoring pull request #8
Opened 2019-03-10 12:21 UTC by Afftobus

2019-03-10 12:29 UTC, alinkov requested changes

2019-03-10 12:29 UTC, alinkov commented on hh-dep-monitoring-service/src/etc/hibernate.properties
> +hibernate.jdbc.batch_size=10
Перенос добавь

2019-03-10 12:29 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +    this.dataSource = dataSource;
Зачем?
Эти параметры вообще убираются в соседнем PR

2019-03-10 12:29 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/ProdConfig.java
> +    @Autowired
Не нужна

2019-03-10 12:29 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/ProdConfig.java
> +    protected DataSource dataSource(DataSourceFactory dataSourceFactory, FileSettings fileSettings) {
Лучше в CommonConfig

2019-03-10 12:29 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RelationDao.java
> +    int addNew(Repository from, Repository to, RepositoryRelationPriority priority);
Такие названия не подойдут.
persist, save, update...

get... fetch для получения

2019-03-10 12:29 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RelationDaoImpl.java
> +    @Transactional()
Зачем скобки?

2019-03-10 12:29 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RelationDao.java
> +    int setDescription(int idFrom, int idTo, String description);
Такой метод не нужен

2019-03-10 12:29 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/Resource.java
> +        ApplicationContext context = new AnnotationConfigApplicationContext(NabHibernateCommonConfig.class);
Так с бинами не работают...

2019-03-11 07:34 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +    @Bean(name = "dataSource", destroyMethod = "")
сделай просто `@Bean`

пока остальное не нужно, лучше не использовать

2019-03-11 07:34 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RepositoryDao.java
> +public interface RepositoryDao {
вот давай приведем к таком формату

```java
public interface Dao<T> {
     
    Optional<T> get(int id);
     
    List<T> getAll();
     
    void save(T t);
     
    void update(T t);
     
    void delete(T t);
}
```

А остальные DAO будут его расширять и, по необходимости, добавлять новые методы

Плюс можно сделать AbstractDao, в котором эти методы уже будут реализованы

2019-03-11 07:34 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RelationDaoImpl.java
> +    @Autowired
`@Autowired` не нужно. 
Если хочешь поставить аннотацию, то ставь везде `@Inject`

2019-03-11 07:34 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RelationDaoImpl.java
> +    @Transactional
после тестов, надо будет убрать.
За транзакции должен отвечать сервисный уровень

2019-03-12 18:51 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +//import ru.hh.nab.starter.AppMetadata;
Убирай это

2019-03-12 18:51 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +    @Bean(name = "DataSource", destroyMethod = "")
Оставь только @Bean остальное убери

2019-03-12 18:51 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/RepositoryRelationPriority.java
> +    critical,
Так не пойдет

2019-03-12 19:22 UTC, colorbash submitted a review, later dismissed

2019-03-12 19:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +//import ru.hh.nab.starter.AppMetadata;
забыл убрать?

2019-03-12 19:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +//import javax.inject.Inject;
тоже самое

2019-03-12 19:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryDaoImpl.java
> +        return session.createQuery("SELECT r FROM Repository r WHERE is_active = true", Repository.class)
@alinkov все запросы через HQL будут? Кажется что простенькие через критерию можно, а если уж ей совсем не обойтись то и уж HQL заюзать? ИМХО критерия более правильный путь

2019-03-12 19:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RelationDaoImpl.java
> +        session.persist(relation);
вроде читаемость не ухудшится если `sessionFactory.getCurrentSession().persist(relation)`
но как тебе больше нравится оставь)
или сделать метод `private persist(Relation relation) { sessionFactory.getCurrentSession().persist(relation) }`
и его везде использовать, чтоб лишние строки каждый раз не писать

2019-03-12 19:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RelationDaoImpl.java
> +        session.persist(relation);
или метод `Session getSession() {return sessionFactory.getCurrentSession()}`
тогда будет `getSession().persist(relation);`

2019-03-12 19:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RelationDaoImpl.java
> +        session.persist(relation);
подумай что лучше

2019-03-12 19:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/Relation.java
> +        return (relationId ^ (relationId >>> 16));
мы сейчас суем эту ентитю в мапу/сет или еще куда? это надо было писать?
если нужно то наверное надо сделать чтоб хешь зависил от всех полей?
Самое простое Objects.hash(...)

2019-03-12 19:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/RepositoryRelationPriority.java
> +    critical,
Раньше было по стайлгайду, верни плиз

2019-03-12 19:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/PostgreSQLEnumType.java
> +            PreparedStatement st,
обычно первый параметр остается на строчке где обьявляется метод если хватает места и можно его назвать preparedStatement
идея же сама автодополняет

2019-03-12 19:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/PostgreSQLEnumType.java
> +        if (value == null) {
```java
  if (value == null) {
            st.setNull(index, Types.OTHER);
            return;
  }
  st.setObject(
                    index,
                    value.toString(),
                    Types.OTHER
  );
}
```
красивее, нет?

2019-03-12 19:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/PostgreSQLEnumType.java
> +        if (value == null) {
смотри по вкусу

2019-03-12 19:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/Resource.java
> +    // TODO:
что туду?

2019-03-12 19:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/Resource.java
> +        return repositoryDao.getAll();
вроде как была задачка фронт 5 в ней договаривались о формате общения фронта с беком?
```
{
items: [
{
repositoryId: 123,
name: 'abc',
htmlUrl: 'http...'
description: 'aaabbbccc',
isArchived: true,
createdAt: '2019-01-20T18:25:55',
updatedAt: '2019-02-23T18:25:43'
},
{}, ...]
}
```

2019-03-12 19:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/Resource.java
> +        return repositoryDao.getAll();
пока ты возвращаешь лист

2019-03-12 19:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/Resource.java
> +        RepositoryDaoImpl repositoryDao = new RepositoryDaoImpl(dataSource.getObject());
я думаю у тебя RepositoryDaoImpl должен быть бином, не надо его самому создавать, лучше заинжектить в ресурс

2019-03-12 19:22 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/Relation.java
> +    @Type(type = "priority")
честно уже не помню, но разве обычный 
```java
@Column(name="...")
private RepositoryRelationPriority repositoryRelationPriority;
```
не будет работать?

2019-03-12 20:24 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/RepositoryRelationPriority.java
> +    critical,
у нас в .sql написано в нижнем регистре, я на это и ориентировался, чтоб не лезть в чужую утверждённую задачу.

2019-03-12 20:50 UTC, colorbash commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RelationDaoImpl.java
> +public class RelationDaoImpl extends AbstractDao implements RelationDao   {
много пробелов

2019-03-13 05:12 UTC, K-ksenia commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/Resource.java
> +//
забыл пустой коммент убрать

2019-03-13 05:24 UTC, SuhoyVasya commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +public class AbstractDao<T extends Serializable> implements Dao<T> {
почему именно  "T extends Serializable"?
и почему класс объявлен абстрактным?

2019-03-13 06:18 UTC, anickishin requested changes

2019-03-13 06:18 UTC, anickishin commented on hh-dep-monitoring-service/src/etc/service.properties
> +master.jdbcUrl=jdbc:postgresql://127.0.0.1:5432/monitoring?useUnicode=true&characterEncoding=UTF8
с localhost не будет работать?
на винде можно будет hosts поправить и подключаться к postgres

2019-03-13 06:18 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    private Class<T> clazz;
А зачем этот clazz?

2019-03-13 06:18 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    SessionFactory sessionFactory;
Если тут делать SessionFactory, то:
```suggestion
    protected final SessionFactory sessionFactory;
```
и убирать из наследников

2019-03-13 06:18 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +public class AbstractDao<T extends Serializable> implements Dao<T> {
Если класс абстрактный, то, может быть, стоит так:
```suggestion
public abstract class AbstractDao<T extends Serializable> implements Dao<T> {
```

2019-03-13 06:18 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    protected final Session getCurrentSession() {
Тогда уж сократить название до getSession() и использовать в наследниках

2019-03-13 06:18 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RelationDaoImpl.java
> +        return session.createQuery("SELECT r FROM Relation r WHERE repository_from_id = :repositoryId", Relation.class)
```suggestion
        return getSession().createQuery("FROM Relation WHERE repository_from_id = :repositoryId", Relation.class)
```

2019-03-13 06:18 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/Resource.java
> +    private final RepositoryDao repositoryDao;
А нужен ли нам такой ресурс в мастере?

2019-03-13 07:42 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/Relation.java
> +    @Type(type = "priority")
вот с этим тоже вчера бился, 
энум джавовский на энум постгрёвый не мапится без спец. средств. 
в итоге только текущий вариант взлетел.

2019-03-13 07:44 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +public class AbstractDao<T extends Serializable> implements Dao<T> {
это StackOverFlow CopyPaste Porgramming Style 
в следующих коммитах уберу.

2019-03-13 07:45 UTC, Afftobus commented on hh-dep-monitoring-service/src/etc/service.properties
> +master.jdbcUrl=jdbc:postgresql://127.0.0.1:5432/monitoring?useUnicode=true&characterEncoding=UTF8
тут мож вообще круче будет вынести строку подключения куда-нибудь в конфиг...

2019-03-13 07:46 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    private Class<T> clazz;
чтобы потом явно указывать кто у меня будет вместо дженерика

2019-03-13 08:04 UTC, SuhoyVasya approved these changes

2019-03-13 09:25 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/RepositoryRelationPriority.java
> +    critical,
Так не пойдет.
Т.е. либо правь схему, либо правь PostgreSQLEnumType

2019-03-13 09:26 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryDaoImpl.java
> +        return session.createQuery("SELECT r FROM Repository r WHERE is_active = true", Repository.class)
Не уверен, что criteria правильный путь...
`@NamedQuery` никто не отменял

2019-03-13 09:44 UTC, alinkov requested changes

2019-03-13 09:44 UTC, alinkov commented on hh-dep-monitoring-service/src/etc/service.properties
> +master.jdbcUrl=jdbc:postgresql://127.0.0.1:5432/monitoring?useUnicode=true&characterEncoding=UTF8
конфиг для конфига? Это уж слишком.
Пишите лучше DNS

2019-03-13 09:44 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/Dao.java
> +    public T findOne(int id);
Optional<T>

2019-03-13 09:44 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RelationDao.java
> +    List<T> getRelatedFrom(int repositoryId);
не нужны эти методы

2019-03-13 09:44 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RepositoryDao.java
> +    List<T> searchByName(String name);
убирай пока. Тоже пока не нужно

2019-03-13 09:44 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/Resource.java
> +    private final RepositoryDao repositoryDao;
удаляй лишнее. Не надо тестового кода в репозитории

2019-03-13 18:15 UTC, anickishin requested changes

2019-03-13 18:15 UTC, anickishin commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    protected Session getSession() {
У тебя теперь 2 одинаковые функции getSession и getCurrentSession. Удали лишнее.

2019-03-13 18:28 UTC, alinkov requested changes

2019-03-13 18:28 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    private Class<T> clazz;
```suggestion
    private final Class<T> clazz;
```

2019-03-13 18:28 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/ProdConfig.java
> +
убери лишний

2019-03-13 18:28 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    public final void setClazz(Class<T> clazzToSet) {
убери эту функцию

2019-03-13 18:28 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        return (Optional<T>) getCurrentSession().get(clazz, id);
Так не работает
```suggestion
        return Optional.ofNullable(getCurrentSession().get(clazz, id));
```

2019-03-13 18:28 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    public void create(Optional<T> entity) {
не входной параметр не должен быть Optional
```suggestion
    public void create(@Nonnull T entity) {
```

2019-03-13 18:28 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    public void update(Optional<T> entity) {
тоже Optional убирай

2019-03-13 18:28 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    public void delete(Optional<T> entity) {
и тут

2019-03-13 18:28 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        delete(entity);
```suggestion
        entity.ifPresent(this::delete);
```

2019-03-13 18:28 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/Dao.java
> +public interface Dao<T> {
приведи в порядок

2019-03-13 18:28 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    private Class<T> clazz;
и можешь получать через generic

2019-03-13 18:28 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RelationDao.java
> +public interface RelationDao extends Dao<Relation> {
убери все методы, пока не нужны

2019-03-13 18:28 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RepositoryDao.java
> +    List<Repository> searchByName(String name);
думаю, что стоит пока убрат

2019-03-13 18:28 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/Relation.java
> +        return (relationId ^ (relationId >>> 16));
```suggestion
        return Objects.hash(relationId);
```

2019-03-13 18:28 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/Repository.java
> +        int result = (repositoryId ^ (repositoryId >>> 16));
```suggestion
       return Objects.hash(repositoryId);
```

2019-03-13 19:31 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/PostgreSQLEnumType.java
> +package ru.hh.school.depmonitoring.rs;
не тут должно быть

2019-03-13 19:31 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/PostgreSQLEnumType.java
> +public class PostgreSQLEnumType extends org.hibernate.type.EnumType {
`org.hibernate.type.EnumType` -> ` EnumType`

2019-03-13 20:36 UTC, Afftobus commented on hh-dep-monitoring-service/src/etc/hibernate.properties
> +hibernate.jdbc.batch_size=10
ok

2019-03-13 20:37 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/ProdConfig.java
> +    @Autowired
убрал

2019-03-13 20:39 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RelationDaoImpl.java
> +        session.persist(relation);
ОК

2019-03-13 20:41 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/Resource.java
> +    // TODO:
это я чтоб не забыть убрать, там много нерабочего накомитил, чтоб показать код и просить помощи,

2019-03-14 16:13 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/ProdConfig.java
> +    protected DataSource dataSource(DataSourceFactory dataSourceFactory, FileSettings fileSettings) {
ок

2019-03-14 16:14 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RelationDao.java
> +    int addNew(Repository from, Repository to, RepositoryRelationPriority priority);
ок

2019-03-14 16:14 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RelationDaoImpl.java
> +    @Transactional()
убрал

2019-03-14 16:16 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RelationDao.java
> +    int setDescription(int idFrom, int idTo, String description);
убрал все лишние

2019-03-14 16:17 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/Resource.java
> +        ApplicationContext context = new AnnotationConfigApplicationContext(NabHibernateCommonConfig.class);
переделал

2019-03-14 16:17 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +    @Bean(name = "dataSource", destroyMethod = "")
ок

2019-03-14 16:17 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RepositoryDao.java
> +public interface RepositoryDao {
ок

2019-03-14 16:17 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +    this.dataSource = dataSource;
смерджил

2019-03-14 16:18 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RelationDaoImpl.java
> +    @Autowired
ok

2019-03-14 16:19 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RelationDaoImpl.java
> +    @Transactional
убрал

2019-03-14 16:19 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +//import ru.hh.nab.starter.AppMetadata;
подчистио все комменты

2019-03-14 16:19 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +    @Bean(name = "DataSource", destroyMethod = "")
ок

2019-03-14 16:19 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/RepositoryRelationPriority.java
> +    critical,
поправил SQL

2019-03-14 16:20 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +//import ru.hh.nab.starter.AppMetadata;
ок

2019-03-14 16:20 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/config/CommonConfig.java
> +//import javax.inject.Inject;
ок

2019-03-14 16:21 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RepositoryDaoImpl.java
> +        return session.createQuery("SELECT r FROM Repository r WHERE is_active = true", Repository.class)
ну эти методы я всё равно убрал

2019-03-14 16:21 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/Relation.java
> +        return (relationId ^ (relationId >>> 16));
ресурс был для тестов, уже убрал

2019-03-14 16:22 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/RepositoryRelationPriority.java
> +    critical,
рк

2019-03-14 16:26 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/PostgreSQLEnumType.java
> +            PreparedStatement st,
да, так красивее :-)

2019-03-14 16:26 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/PostgreSQLEnumType.java
> +        if (value == null) {
поправил

2019-03-14 16:27 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/Resource.java
> +        return repositoryDao.getAll();
пока убрал ресурс вообще

2019-03-14 16:27 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/Resource.java
> +        RepositoryDaoImpl repositoryDao = new RepositoryDaoImpl(dataSource.getObject());
ок

2019-03-14 16:27 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RelationDaoImpl.java
> +public class RelationDaoImpl extends AbstractDao implements RelationDao   {
ок

2019-03-14 16:28 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/Resource.java
> +//
ок

2019-03-14 16:28 UTC, Afftobus commented on hh-dep-monitoring-service/src/etc/service.properties
> +master.jdbcUrl=jdbc:postgresql://127.0.0.1:5432/monitoring?useUnicode=true&characterEncoding=UTF8
да, это же уже и есть конфиг О_о
тошда просто смотрю на localhost

2019-03-14 16:29 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    private Class<T> clazz;
ok

2019-03-14 16:29 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    SessionFactory sessionFactory;
ok

2019-03-14 16:30 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +public class AbstractDao<T extends Serializable> implements Dao<T> {
ok

2019-03-14 16:30 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    protected final Session getCurrentSession() {
ok

2019-03-14 16:30 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/impl/RelationDaoImpl.java
> +        return session.createQuery("SELECT r FROM Relation r WHERE repository_from_id = :repositoryId", Relation.class)
ok

2019-03-14 16:30 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/Resource.java
> +    private final RepositoryDao repositoryDao;
ok

2019-03-14 16:31 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RelationDao.java
> +    List<T> getRelatedFrom(int repositoryId);
убрал

2019-03-14 16:31 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    protected Session getSession() {
ок

2019-03-14 16:32 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    public final void setClazz(Class<T> clazzToSet) {
ок

2019-03-14 16:32 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +        return (Optional<T>) getCurrentSession().get(clazz, id);
поправил

2019-03-14 16:32 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    public void create(Optional<T> entity) {
ок

2019-03-14 16:32 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/RelationDao.java
> +public interface RelationDao extends Dao<Relation> {
ок

2019-03-14 16:32 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/entities/Repository.java
> +        int result = (repositoryId ^ (repositoryId >>> 16));
ок

2019-03-14 16:33 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/PostgreSQLEnumType.java
> +package ru.hh.school.depmonitoring.rs;
ок

2019-03-14 16:33 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/rs/PostgreSQLEnumType.java
> +public class PostgreSQLEnumType extends org.hibernate.type.EnumType {
ок

2019-03-14 17:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    protected SessionFactory sessionFactory;
```suggestion
    protected final SessionFactory sessionFactory;
```

2019-03-14 17:21 UTC, alinkov commented on hh-dep-monitoring-service/src/etc/service.properties
> +github.oauth=TEST_TOKEN
Добавь перенос

2019-03-14 17:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    protected final Session getSession() {
Обычно вначале public, потом остальные
И protected final SessionFactory sessionFactory можно сделать private. Пусть везде через этот метод

2019-03-14 17:21 UTC, alinkov commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/Main.java
> +public class   Main {
не надо пробелов

2019-03-14 17:22 UTC, alinkov approved these changes

2019-03-14 18:59 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    private final SessionFactory sessionFactory;
сделал private final

2019-03-14 18:59 UTC, Afftobus commented on hh-dep-monitoring-service/src/main/java/ru/hh/school/depmonitoring/dao/AbstractDao.java
> +    protected final Session getSession() {
унёс protecter метод вниз

2019-03-14 18:59 UTC, Afftobus commented on hh-dep-monitoring-service/src/etc/service.properties
> +github.oauth=TEST_TOKEN
добавил перенос в конце

2019-03-15 05:50 UTC, anickishin approved these changes

2019-03-15 05:59 UTC, merged