Back 13 Database init instruction
hhru/hh-dep-monitoring pull request #9
Opened 2019-03-11 13:03 UTC by SuhoyVasya

2019-03-11 14:19 UTC, alinkov requested changes

2019-03-11 14:19 UTC, alinkov commented on db/database_init_instruction.md
> +    1.3 Узнаем адрес docker-machine(по умолчанию 192.168.99.100)
а зачем?
через `127.0.0.1` будет доступен

2019-03-11 14:19 UTC, alinkov commented on db/database_init_instruction.md
> +		docker pull suhoyvasya/postgres-monitoring
Сам Dockerfile, который лежит в registry обязательно сюда добавь.
Чтобы потом можно было концы найти

2019-03-11 14:19 UTC, alinkov commented on db/database_init_instruction.md
> +2) Подключение к базе данных, вводим пароль когда консоль попросит
Это отдельным пунктом. Подключение через консоль (если оно нужно будет

2019-03-12 08:10 UTC, alinkov commented on db/.dockerignore
> +*.md
это нужно еще?

2019-03-12 08:10 UTC, alinkov commented on db/database_init_instruction.md
> +            docker run -p 5432:5432 -e POSTGRES_PASSWORD=123 -e POSTGRES_USER=monitoring -d postgres
Достаточно просто
`docker run -p 5432:5432 -d postgres`
А эти -e POSTGRES_PASSWORD=123 -e POSTGRES_USER=monitoring нужны, если пароль нужно будет поменять

2019-03-12 09:05 UTC, SuhoyVasya commented on db/.dockerignore
> +*.md
Для наших целей в нем нет необходимости

2019-03-12 09:16 UTC, SuhoyVasya commented on db/database_init_instruction.md
> +            docker run -p 5432:5432 -e POSTGRES_PASSWORD=123 -e POSTGRES_USER=monitoring -d postgres
сорян, я вроде убирал это и опять вылезло. Поправлю

2019-03-12 09:21 UTC, SuhoyVasya commented on db/database_init_instruction.md
> +            docker run -p 5432:5432 -e POSTGRES_PASSWORD=123 -e POSTGRES_USER=monitoring -d postgres
сделал

2019-03-12 09:29 UTC, alinkov approved these changes

2019-03-12 18:41 UTC, colorbash approved these changes

2019-03-12 18:41 UTC, colorbash commented on db/database_init_instruction.md
> +﻿0) Установка на машину docker.
и postgres-а самого, psql не запустится

2019-03-12 18:51 UTC, merged